### ISSUE TITLE
Optimize space usage of the "Other videos" column (and its miniatures)

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1022]
The current interface for the "other videos" in the watch view has room for improvement: it could at least lose less space in some of the situations explained below.

The situations occur at different screen resolutions. We especially care for small resolutions, but improving the appearance for large displays could be good too. It is just less problematic.

---

### Situation 1 (less problematic): 1300px of width and more

![peertube_other_videos_side](https://user-images.githubusercontent.com/6329880/45180474-cdb74000-b21b-11e8-84de-82124b0fc982.png)

The "other videos" appear with a noticeable margin on the right. It could probably use a bit more width off the main column too, but the problem remains the same: the UI has a fixed size and the miniature is not scaling (just scaling the miniature is ugly…).

### Situation 2: < 1300px width.

![peertube_other_videos_bottom](https://user-images.githubusercontent.com/6329880/45181012-74501080-b21d-11e8-9554-f1f9b651234e.png)

Below 1300px, the column switches to the bottom of the UI to avoid reducing the video information and commentary width. However, by doing so, it keep the format of a column, which looses 3/4 of the space available.

---

How others are doing it.

## Vimeo

Vimeo kinda sucks at it :slightly_frowning_face: 

![vimeo_other_videos_side](https://user-images.githubusercontent.com/6329880/45181265-40291f80-b21e-11e8-9041-11a502430299.png)

## YouTube

YouTube however does great. But they make some assumptions that are radically different from ours. For instance they close the left sliding menu by default when watching a video. That gives them more space, and they use all of it:

![youtube_other_videos_side_big](https://user-images.githubusercontent.com/6329880/45181513-fb51b880-b21e-11e8-92d2-d63462da01de.png)

This is even more visible when they viewport size is reduced, because they place the "other videos" right below the video information and description, and before the comments (isn't that telling of how they consider they comments…) here below 800px of width:

![youtube_other_videos_side_small](https://user-images.githubusercontent.com/6329880/45181593-2c31ed80-b21f-11e8-9046-e92d21760e3e.png)

---

What do you think? Is this really an issue (I guess we're fine since we do better than Vimeo :wink: but… still.)

If you have other inspirations, or mockups answering even partially to this problem, that would be of great help. No need to directly show code, we can do that once we've settled on the design to adopt.

**Comment by Bugsbane** [comment]
Ok, so here's my feedback, in order of importance:

1. Firstly, we waste a lot of space by keeping all of the space to the right and left of the video empty.
2. The size of the player, the most important element on the page, doesn't change size to fill the space at all. As the most important element, it should be using everything it can get, without obscuring the interface.
3. There is a lot of space wasted by the Privacy / Category / License / Language / Tags section, which can more compactly be moved elsewhere (my mockup below keeps all of them).
4. When the screen width goes below 1300px the other videos goes underneath the comments... which is good, however it's still a column, instead of a row, which doesn't make sense for it's new position.
5. Currently the uploader avatar is about 1/4 of the size of the avatars of anyone commenting on the video. Who made / uploaded the video it is far more relevant to the viewer, than who commented on it, so it should be larger.
5. As pointed out, in YouTube, the left column automatically minimizes, giving more space for the player. Having "Overview, Trending, Recently added" etc, might make sense on the home page, where people are presumably looking for something to watch. On the page for a specific video though, they're there to watch *that* video, and the other stuff is just a distraction. Note: the login / create account buttons in these mockups are moved out of the left bar, so they are still visible when the left bar is hidden.

So what does this look like in practice? Here's a screenshot I grabed of beta 12 playing a random video, and below it a mockup (sorry about the different font) to demonstrate my suggestions:

**Original:**
![screenshot_2018-09-12 let s de-google-ify the internet 4](https://user-images.githubusercontent.com/401733/45439335-84397b80-b687-11e8-9fbf-2fca26686ebe.png)

**Suggested (wide screen):**
![peertube-rework](https://user-images.githubusercontent.com/401733/45438286-bf867b00-b684-11e8-82a4-75e01dd53212.png)

When screen real estate gets smaller, I suggest we hide the bar on the left, first, having it overlay when the hamburger button is pressed:
![peertube-rework-medium](https://user-images.githubusercontent.com/401733/45438436-26a42f80-b685-11e8-9ee3-cd6299394214.png)

**Suggested (thin screen)**:
Finally when width gets smaller again, we move the "other" videos below the comments *as a row*:
![peertube-thin](https://user-images.githubusercontent.com/401733/45439030-c7471f00-b686-11e8-9a00-4506e4fa1599.png)
Note, at this width the video player should always use 100% width - padding, with everything else being pushed down below it. "Other video" thumbnails could remain the same size (although ideally they'd scale down a bit, too), displaying as many as can fit horizontally, with auto spacing between them.

**Comment by rigelk** [comment]
@PhieF also [did a mockup](https://crazynoisybizarre.town/@PhieLaidMignon/100717559159996106) resembling yours @Bugsbane - at least on the fact of displacing the videos to make a third column.

![bb5a3756ffd9dc2d](https://user-images.githubusercontent.com/6329880/45555051-05377500-b838-11e8-948d-63fd93bb4e58.png)

We then commented the issue of having a third column. My opinion is that it kind of misses the point. The problem is not only wether to have video on the side of the player or not. It's more about thinking up a format of miniatures that better uses the space.

**Comment by PhieF** [comment]
I finally implemented here with css https://lostpod.space/videos/watch/e871e182-7cc6-49d0-a966-0e2f7b778492

**Comment by Bugsbane** [comment]
> It's more about thinking up a format of miniatures that better uses the space.

OK, in terms of using the space for the thumbnails, right now we use 4 lines for text which is excessive and has many unnecessary details which distract from the main content, meanwhile we keep the images (the most important part) relatively small and obscure part of them with a play time.

Please look at the mockup below full size (ie click on the image). The top "other video" image is how we do it now. The bottom is my proposal:
![thumb](https://user-images.githubusercontent.com/401733/45700365-5302f480-bb3a-11e8-852c-f0be72609782.png)

Features:
1. It doesn't block any part of the creators image (with the play length)
2. Images are slightly larger in the same space so the viewer can see more of the image and title
3. It only uses 1 line for the title (we can elipses ... overflow) allowing us to fit more videos vertically.
4. It uses a common username, instead of the login credential. People care more that it's by "The Blender Foundation" than @video@video.blender.org ).
5. It adds a mini avatar, for quick, visual recognition
6. It uses a lighter font on the second line to keep emphasis on the title more.
7. It still shows views, however this could be swapped for how long ago it was uploaded on "Latest" pages, or whatever the most relevant info is for that page.

**Comment by rigelk** [comment]
@Bugsbane this. this is exactly what I had in mind. I'd show the user handle at least on hover, though.

I'm also wondering if we should allow the text to be displayed on the right of the video thumbnail when the screen width is big enough.

**Comment by Bugsbane** [comment]
I agree on abbreviating numbers. On wide screens we could show text to the right, however personally I find it a bit ugly. It does allow fitting more videos onscreen though.

I find that YouTube at least, let's the side text width get unreadably thin before moving the video column underneath. I would say that when the text is to the right, that it's column should be at least as wide as the video thumbnail (remembering that I'm arguing for larger thumbnails already, especially when they're placed underneath the comments).

I'd really like to see adaptive width used much more, both for the size of the player and the video thumbnails.

**Comment by voidzero** [comment]
> I finally implemented here with css https://lostpod.space/videos/watch/e871e182-7cc6-49d0-a966-0e2f7b778492

Sorry to contact you here @PhieF but do you administer lostpod.space? How can I contact you? I have a question about my account on lostpod.space.

**Comment by Chocobozzz** [comment]
@rigelk had made some improvements to the "Other videos" section.
