### ISSUE TITLE
Dark theme administration lists is white on white.

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1028]
* **PeerTube version or URL:**
Develop 4e554c4a2d5ea2cd98ce5545d81431100de43b23
* **Browser name/version:**
Firefox

* **What is the expected behaviour?**
With dark theme background is suposed to be gray and text white.
* **What do you see instead?**
Both are white :
![both are white](https://image.noelshack.com/fichiers/2018/36/5/1536327991-capture-du-2018-09-07-15-45-46.png)

**Comment by rigelk** [comment]
Hi @Jorropo - the dark theme is not complete, as you noticed. There are plenty of other issues with it, mostly in the administration interface (nav-list headers being full white, etc.). Since only the administration interface is problematic, I released nonetheless. You are welcome to contribute.

Mostly the changes required amount to:

- detecting the class/id styling the element
- replacing the color by one of the variables introduced in 9a0fc8409c7a783348ec212fa9f38d0a98413467

**Comment by rigelk** [comment]
Fixed in 1fd3ef3fb49cf5482f2ab6f827a2b059a44f409c.
