### ISSUE TITLE
Streaming from remotes supported by youtube-dl

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1045]
The issue was initiated by a [discussion in framacolibri (in french)](https://framacolibri.org/t/niquer-youtube-en-affichant-leurs-videos/3542). (I do not endorse the title :sweat_smile:)

We already bundle youtube-dl to import videos from multiple remotes. It can resolve the URL to the video ressources to stream, just from their watch page URL. We could add this resolution to the search engine, so that a URL pasted in the search form redirects to a PeerTube watch view streaming the video from the resolved ressource URL.

It would help replace YouTube's bloated tracking interface, and open further interaction possibilities (see #1044).

**Comment by rigelk** [comment]
I don't think we should say we only do *video hosting*. That is simply not true even now : we already try to implement standard protocols which don't have anything to do with hosting but have a lot to do with the user habits and experience. We also try to play nice with other services via the import feature or even taking into account Twitter embeds. YouTube is no different, if not even more important since our users' habits come from there.

**Comment by Chocobozzz** [comment]
> I don't think we should say we only do video hosting.

I did not say we only do video hosting, I just say the main goal of PeerTube is to decentralize video hosting, and, in the future, interactions around these videos.

> We also try to play nice with other services via the import feature or even taking into account Twitter embeds. 

We implement standards that facilitate peertube videos sharing on other centralized platforms, but not the opposite. And we implement tools so people can easily migrate/duplicate their videos from centralized platform to a decentralized one.

**Comment by rigelk** [comment]
Well, I stand corrected. According to that, we shouldn't land this in core at least.

**Comment by Chocobozzz** [comment]
I agree with that, a plugin should be the way to go.

**Comment by trymeouteh** [comment]
If a video is uploaded to Peertube that is from YouTube. I think Peertube should not dish our the peertube copy of the video but grab the video from YouTube but block the ads and tracker and not webtorrent the video. Now if Peertube cannot grab the YouTube video because it has been taken down from YouTube, it will fallback and use the Peertube copy and webtorrent the Peertube copy.

I think this will reduce the bandwidth drastically since YouTube will dish out the bandwidth. Many of us dislike YouTube, but minus well let them pay for dishing out the bandwidth whenever we can. Invidious is built on this model since Invidious is a alternative YouTube front end but relies on YouTube to dish out the video and Invidious blocks the ads and trackers. So your privacy is respected, less bandwidth required from a peertube instance and Google is the one having to provide the video and pay for the bandwidth. Why not make Google pay for bandwidth when we have nothing to lose.

**Comment by Chocobozzz** [comment]
Closing, please create dedicated issues for plugin hooks you need.
