### ISSUE TITLE
Allow import from local disk for the system user

### ISSUE THREAD

**Issue by m333w** [Chocobozzz/PeerTube#1084]
Hello, 

I would like to know if is a possible way to import content directly from HDD ? 
That it is not recreated at import in "/var/www/peertube/storage/videos". 

I have videos in /home/share and I would like it to be readable directly by peertube even if it means specifying the path. Is that possible? 

(sorry for my bad english)

Best regards.

**Comment by scanlime** [comment]
I'm not sure this would help as much as you expect; the main cost in preparing a new video to host is the transcoding, not copying the file itself. I imagine you could make a manual import tool that uses symlinks if you already have video that's transcoded properly, but I'm not sure it would make sense for peertube to support arbitrary paths instead of the current UUID-based scheme?

**Comment by NitroNils** [comment]
(What bad English? U are missing an 'it', that's all.)

**Comment by Chocobozzz** [comment]
You'll need to use import or upload tools: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md

But you cannot just specify a path, because like @scanlime said peertube process videos on upload.
