### ISSUE TITLE
Downloads of videos for redundancy create files with arbitrary paths including "/"

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1125]
I'm running v1.0.0-beta14 and I've been experimenting with the redundancy feature.

The downloads seem to go directly into the video storage directory with a path that depends on the video title.

This is quite possibly a giant security hole... and it's already leaving me with directories inside 'storage' any time it downloads a video with a slash in the title.

**Comment by scanlime** [comment]
noting a related problem with captions and previews. this doesn't look okay...

`const destPath = join(CACHE.VIDEO_CAPTIONS.DIRECTORY, videoCaption.getCaptionName())`

**Comment by Chocobozzz** [comment]
In the latest develop the downloaded data is put in an `import` directory. Even if it creates directories, they are deleted at the end of the process. The paths should be safe: https://github.com/webtorrent/parse-torrent/blob/master/index.js#L172

It's weird you still have these directories but we may have fixed this bug in develop (I'll do some tests).

> noting a related problem with captions and previews

Please paste the URL of the file/line number. Because I don't see what's the problem here.

**Comment by scanlime** [comment]
To answer my own question... (if anyone else is following this?) the validation seems okay at the point where a video is imported from a remote server; the UUID is checked against a regex using:

https://github.com/chriso/validator.js/blob/master/lib/isUUID.js

then we generate paths for captions and previews that are based only on that and on constants from the source.

**Comment by scanlime** [comment]
Re the original bug, it does look like torrent files turn into local filesystem paths (parse-torrent -> webtorrent -> fs-chunk-store) without any validation other than making sure it's a utf-8 string.

I'm not sure how you would prefer to solve this, but the 1:1 match between untrusted filenames in the torrent and local filenames in the fs-chunk-store seems like a hazard for sure, and it might be sufficient to put the torrent in a temp directory and use hashes for all filenames rather than allowing any unvalidated text to end up in a filesystem path.

**Comment by scanlime** [comment]
If my analysis is right, this is definitely a security bug. Untrusted torrents could write to, for example, the peertube configuration file, or write over source code that would be executed in the future, giving effectively unrestricted access to the peertube user account.

**Comment by Chocobozzz** [comment]
In the code I linked, the path should be safe because of `path.join.apply(null, [path.sep].concat(parts)).slice(1)`

The key is the `path.sep` variable at the beginning of the string. So `../hello` becomes `/../hello` and `join` returns `/hello`. The `/` at the beginning of the string prevents the escape of the `import` directory.

**Comment by scanlime** [comment]
Thanks for the explanation, I didn't realize path.join() would normalize the resulting path as if it's absolute. This seems safe (albeit annoying) unless there are symlinks or other ways to escape the import directory with a specially written name. Is it still a concern that any filename can be overwritten?

**Comment by Chocobozzz** [comment]
>  Is it still a concern that any filename can be overwritten?

No because we are in the `import` directory.
