### ISSUE TITLE
peertube-upload.js to a specific channel

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#1134]
When uploading a folder of videos, I'd like to be able to tell the script to put them on a specific channel using a channel ID. The upload script does not seem to support this however. Is it supported on the upload endpoint?

If so, would appreciate script support for it :)

**Comment by scanlime** [comment]
I'd enjoy this feature too!

Fwiw this is possible right now if you feel like (1) editing the source code and (2) manually determining which channelId in the database corresponds with the channel you want.

You can edit the videoAttributes initializer in server/tools/import-videos.ts (or js, I just edited the compiled source instead of recompiling). In my case I set some tags and a default language and license also, 

```
        const videoAttributes = {
            name: lodash_1.truncate(videoInfo.title, {
                'length': initializers_1.CONSTRAINTS_FIELDS.VIDEOS.NAME.max,
                'separator': /,? +/,
                'omission': ' […]'
            }),
            category,
//            licence,
//            language,
            nsfw: isNSFW(videoInfo),
            waitTranscoding: true,
            commentsEnabled: true,
            description: videoInfo.description || undefined,
            support: undefined,
//            tags,
  
license: 1,          
channelId: 3,
tags: [ 'scanlime', 'live', 'electronics', 'stream' ],
language: 'en',

            privacy: videos_1.VideoPrivacy.PUBLIC,
            fixture: videoPath,
            thumbnailfile,
            previewfile: thumbnailfile
        };
```

**Comment by anoadragon453** [comment]
So it's possible by just sending a channelId to the endpoint? If so, I believe a PR is in order.
