### ISSUE TITLE
Investigating using webseed for the server instead of WebRTC

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#12]
Instead of using WebRTC to send the videos to clients, a PeerTube server could use the webeed protocol (throught HTTP protocol). The main goal is to remove the Electron dependency that requires many GNU/Linux dependencies, and could consume a lot of memory & CPU (depending on the number of seeded files).

**pros:**
 * The server would not need the Electron process anymore (less OS
dependencies, no memory & CPU overhead)
 * The server would not have to seed videos at each startup (which could
be long on big files): it just has to serve the static files
 * Less code complexity (we don't need IPC/seperate Electron process)

**cons:**
 * Server has less control: it can't limit bandwitdh/number of peers per
file
 * Webseeding seems to be less efficient on the client side (especially
on Firefox). Seems to be due to the number of requests (small chunks) on
high speed networks

Webseed seems to be the right solution for the PeerTube server, but we need to wait for some ameliorations in the WebTorrent library:
 * https://github.com/feross/webtorrent/issues/650
 * https://github.com/feross/webtorrent/issues/896

PeerTube webseed demonstration: http://peertube-webseed.cpy.re

**Comment by fredhampton** [comment]
Thanks !!


On October 5, 2016 at 6:55:47 AM, Bigard Florian (notifications@github.com) wrote:

Instead of using WebRTC to send the videos to clients, a PeerTube server could use the webeed protocol (throught HTTP protocol). The main goal is to remove the Electron dependency that requires many GNU/Linux dependencies, and could consume a lot of memory & CPU (depending on the number of seeded files).

pros:

The server would not need the Electron process anymore (less OS dependencies, no memory & CPU overhead)
The server would not have to seed videos at each startup (which could be long on big files): it just has to serve the static files
Less code complexity (we don't need IPC/seperate Electron process)
cons:

Server has less control: it can't limit bandwitdh/number of peers per file
Webseeding seems to be less efficient on the client side (especially on Firefox). Seems to be due to the number of requests (small chunks) on high speed networks
Webseed seems to be the right solution for the PeerTube server, but we need to wait for some ameliorations in the WebTorrent library:

feross/webtorrent#650
feross/webtorrent#896
PeerTube webseed demonstration: http://peertube-webseed.cpy.re

**Comment by fredhampton** [comment]
Should we wait for webseed to be ready before we deploy to large user base ?

**Comment by Chocobozzz** [comment]
I think the webseed will be more performant for large users, because Electron process seems to consums a lot of CPU when sending data to users.

**Comment by feross** [comment]
Yeah, web seeds are a super lightweight on your server since you can just host the static files with Apache or nginx. If you're gonna have a centralized host for when there are no peers, there's no need to use webrtc on the server. HTTP works really well and is lighter weight. :)

**Comment by Chocobozzz** [comment]
Thanks @feross!
I'll switch to the webseed implementation soon.

**Comment by Chocobozzz** [comment]
The webseed implementation is now merged in master. The [demo server](http://peertube.cpy.re) was updated. Thanks :)
