### ISSUE TITLE
Pods mutual authentication

### ISSUE THREAD

**Issue by Irkam** [Chocobozzz/PeerTube#120]
Pods mutually authenticate by sending their respective RSA public keys and URLs. Architecture documentation doesn't cover (for now) key exchange protocol. Thus:
* Only RSA public keys ? No other cipher suites ?
* Plain public keys don't feature useful information such as key expiration time, owner, CN... 

These could be addressed by using something like X.509 certs and key negotiation (like TLS) or wrapped symmetric keys (like PGP/GPG).

Maybe this is just not documented yet, or it has been ditched in favour of ease of setup.

**Comment by Chocobozzz** [comment]
With the new [ActivityPub](https://github.com/Chocobozzz/PeerTube/issues/104) federation, we will use [Linked Data Signatures](w3c-dvcg.github.io/ld-signatures/). In PeerTube we will use RSA keys, but this should be compatible with other signature algorithm (using [jsonld-signature library](https://github.com/digitalbazaar/jsonld-signatures)).

We don't use expiration time but I'm not sure we need this: if the signature check fails (because the remote account regenerated the keys), we could update the remote public key (with webfinger) and retry. The keys are self signed and will be assigned to a specific account that has a name, email etc so are the X.509 information really useful?

**Comment by Irkam** [comment]
>The keys are self signed and will be assigned to a specific account that has a name, email etc so are the X.509 information really useful?

The X.509 could contain all that too, and can be signed and encrypted depending on the format, but as I said maybe it's quite overkill, unless you intend to set up a PKI which is another whole discussion (i.e. relatively big pod provider spawning thousands of pods over a cloud service that need to mutually authenticate across data centres for some reason).

However [Linked Data Signatures](https://w3c-dvcg.github.io/ld-signatures/) seem to do quite the job as well, while having more or less the same functionalities as X.509 without the centralised clutter. Definitely seems worth having a look.
