### ISSUE TITLE
How does the "Trending" algorithm work?

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1207]
Looking at the [trending page of my instance](https://peertube.social/videos/trending), it is not clear to me how this is generated. For example, the trending videos interval in the config is set to 7, but I see videos that are more than half a year old. I also couldn't find any info in the Github repo how this works exactly. It would be good if this could be added to the user documentation or somewhere else.

**Comment by Chocobozzz** [comment]
Ping @rigelk 

The trending algorithm takes into account views from the last *x* days (specified in the admin configuration), regardless of the videos published date.

**Comment by McFlat** [comment]
Would it be possible to expose some kind of settings for the trending algorithm in the admin?

**Comment by Chocobozzz** [comment]
@McFlat What kind of settings?

**Comment by McFlat** [comment]
@Chocobozzz To be able to:
1. specify a list of video to exclude from trending
2. update trending interval days in the frontend "Administration" for admins
3. have a list of videos to include in trending or possibly a new section for "Featured Videos" would be nicer, on the trending page. So that the page can have some featured videos at the top, which would be selected out of a list of videos by the admin

**Comment by buoyantair** [comment]
I have an idea of sorts, can users actually implement their own trending algorithms? 
We can actually extract the component that implements the current trending algorithm into it's own package of sorts that can be plugged into Peertube. This means that later on anybody can change their trending algorithms by creating a new plugin and then connecting it to Peertube

**Comment by Chocobozzz** [comment]
Closing this issue, the algorithm is now explained in a tooltip.
