### ISSUE TITLE
Headless seeding

### ISSUE THREAD

**Issue by arthurlutz** [Chocobozzz/PeerTube#122]
This might just be a documentation request : is there a way to add a seed server without having to open a browser with a tab on each video ? 

On a local setup, I have three browsers open, the number of peers is correct at 3. When I use the download link, it opens a torrent file in Transmission, it shows only one peer (the web server), I guess that the file can't be served from the browser peers. The number of peers in the browsers doesn't go up one number when the transmission "traditional" torrent is seeding. 

I guess these are different channels and the bandwidth can't be shared. If this is the case, do you know of any hack where one could have headless browsers on a headless server that open the videos URL to serve the content from multiple locations without a user in front of it ?

**Comment by Chocobozzz** [comment]
Yes, peers in web browser share data throught WebRTC, so it is not compatible with classic TCP/UDP peers (like Transmission).

If you want to seed from CLI, maybe you could try [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid). But it is pretty heavy (creates a hidden Electron process) so it's not ideal.

I've created an issue for your use case: https://github.com/Chocobozzz/PeerTube/issues/123

**Comment by arthurlutz** [comment]
Awesome, a heavy solution is better than no solution. Thanks for the links and the new issue.

**Comment by rigelk** [comment]
Just leaving a pointer to the WebTorrent issue tracking WebRTC support in popular/classic torrent clients: https://github.com/webtorrent/webtorrent/issues/369

**Comment by arxcode** [comment]
Yes, I think this great feature is under-documented, at least it was not obvious for me: You can use the "Download" option, select "Torrent" and then open the torrent file in WebTorrent Desktop (https://webtorrent.io/desktop; or presumably any other WebTorrent-compatible client from the link above).

This isn't exactly "headless", but it is much better than seeding via the browser. Most importantly, you don't have to re-download the video every time you close the client and open it again. And it works pretty well, I am using it right now to help seed Datagueule's new movie and I've already uploaded a couple of GBs...

**Comment by Openmedianetwork** [comment]
Am comeing back to the subjects of seedboxs after being off doing other stuff for a year.

Q. is the a working webRTC DIY seedbox sultion, read threw lots of threds and could not find anything concreat.

**Comment by Chocobozzz** [comment]
@Openmedianetwork See https://github.com/webtorrent/webtorrent/issues/369#issue-93586210

**Comment by k09i71** [comment]
I've decided to revive this issue since this one https://github.com/Chocobozzz/PeerTube/issues/2958#event-3564192394 got closed. 

The fact that we can now use regular clients to seed is a huge news https://feross.org/libtorrent-webtorrent and we should do something about it, no?

**Comment by Openmedianetwork** [comment]
will seedbox work now for peertube for holding the core video off the main server and in a distributed home seedboxs?

**Comment by Avamander** [comment]
Why has this been closed if it's not really possible?

**Comment by Avamander** [comment]
@Chocobozzz could you please reopen the issue as it hasn't been solved yet?

**Comment by Chocobozzz** [comment]
> could you please reopen the issue as it hasn't been solved yet?

No sorry:
 * Headless seeding can be done using peertube redundancy: https://docs.joinpeertube.org/admin-following-instances?id=instances-redundancy
 * We don't use webtorrent anymore for the HLS player https://docs.joinpeertube.org/admin-configuration?id=webtorrent-transcoding-or-hls-transcoding
 * We could create a CLI that uses an headless electron and https://github.com/novage/p2p-media-loader to seed videos, but it's out of the scope of PeerTube for now

**Comment by Avamander** [comment]
@Chocobozzz 

That list contains zero working solutions.

> This is a disadvantage that we accept, because we realized that BitTorrent client that helped to seed PeerTube files were not really used.

"We're the only use-case where WebTorrent would really shine but we're not waiting for any implementations" Really premature and tautological really.

**Comment by Chocobozzz** [comment]
> not waiting for any implementations

There are: https://webtorrent.io/desktop/ or https://wiki.vuze.com/w/WebTorrent or https://github.com/webtorrent/webtorrent-hybrid

**Comment by Avamander** [comment]
@Chocobozzz 

> There are: https://webtorrent.io/desktop/ or https://wiki.vuze.com/w/WebTorrent or https://github.com/webtorrent/webtorrent-hybrid

So there's only Vuze, which is approximately a quarter of the marketshare. It really takes more than that, especially if we look at seedboxes.

**Comment by polarathene** [comment]
> That list contains zero working solutions.

Wait a little bit longer. `libtorrent` 2.x as mentioned earlier in this issue merged WebTorrent support, it's still unreleased in 2.x presently, but looks like it may arrive sometime this year, or perhaps next year.

Meanwhile some popular open-source clients are working on updating to use `libtorrent` 2.x, qBittorrent probably will have it with 4.4 / 5.0 release, they're presently in a beta stage last I checked and working on fixing bugs as it's quite a big change to support (this is unrelated to WebTorrent support).

You might find other clients with `libtorrent` 2.x support already, and some users I think have built that lib with WebTorrent support enabled. So if you've got some dev skills in that area you might be able to get something setup sooner, otherwise soon enough wider support will become available.

Alternatively, there is a [Go based torrent lib implementation](https://github.com/anacrolix/torrent), it has WebTorrent support and there are some clients built on top of that. It doesn't seem as full featured as `libtorrent` C++ lib that is more broadly adopted, but it might be able to meet your needs of a lighter weight solution for headless seeding?

---

Personally I think once the bigger open-source clients are able to provide hybrid support, WebTorrent will be a much more attractive option.

That said, the linked FAQ explains very well the benefits of HLS for video content playback. I'm not too familiar with the related p2p media solution to compliment it, but I assume that helps about as much as, if not better than WebTorrent presently does.
