### ISSUE TITLE
Jobs list too large for screen

### ISSUE THREAD

**Issue by rhaamo** [Chocobozzz/PeerTube#1250]
**What happened?**

Jobs list is too large and the job queue selector is hidden on the right

**What do you expect to happen instead?**

Jobs list fit on screen or move the dropdown selector in a always-visible part

**Steps to reproduce:**

1. Go to jobs list

**Additional information**
* PeerTube version or URL: PeerTube v1.0.0...d9d1989b (current develop)
* Browser name/version: Firefox
* Screen: 12.5" 1366x768 (minus gnome dock on left)

![image](https://user-images.githubusercontent.com/8625/46853494-8c0f4b80-cdfe-11e8-8d48-43f1c0dce3ad.png)

**Comment by Chocobozzz** [comment]
You can remove the menu, maybe you'll have more space to display the table

I don't know how to handle the admin tables on small screen :thinking:

**Comment by rigelk** [comment]
@Chocobozzz maybe we can cheat a little and use primeng's selectable columns (a select a the top of the table that lets the user the possibility to toggle the display of some columns). This would allow us to hide a column or two on small displays, but still allow the sure to see them provided they toggle them.

**Comment by scanlime** [comment]
Re how any of this should look on a smaller screen:

1. A "mobile-first" design might choose to, instead of making this a wide tabular format, to have line-items for each item that can be expanded to reveal more details

2. A responsive design might have two modes, a tabular mode and a mode like in (1)

3. The simplest usable solution would be to set minimum width for the table to something that leaves enough room to interact, and accept that the table will need to scroll horizontally on mobile.

**Comment by alcalyn** [comment]
Hi, I made a PR about that (see link just above), you can view screenshots and give feedback
