### ISSUE TITLE
Ability to disable transcoding before upload.

### ISSUE THREAD

**Issue by commagray** [Chocobozzz/PeerTube#1315]
Currently there is only server-side option to disable it globally. It might be useful to have an option for disabling transcoding while you uploading a video as a common user.

**Comment by scanlime** [comment]
If there is, I'd hope that admins can disable this option. As an administrator, I don't want my site trying to stream videos that have been encoded using arbitrary parameters and formats.

**Comment by Chocobozzz** [comment]
I don't think it's a good idea to allow users to decide if their videos should be transcoded or not, in particular now we have the "Don't wait transcoding" upload option.

**Comment by ghost** [comment]
I would actually support this request too. I think that both options should be possible - A system-wide option, which sets the default values and optionally a user option to allow users to set up their resolutions (not more than what the system option allows, of course). The system could then have another option to override or disable the user settings. This way both sides would be pleased and the admin still has full control.

Personally, I am currently using my PeerTube instance alone and I wish I had this option, because I have different types of videos and some of them do not require all resolutions to be transcoded to. So even as the admin I still have to manually go to the settings and change the transcoding settings temporarily system-wide every single time. And after all jobs are completed, I set them back, which... is not an elegant solution.
