### ISSUE TITLE
Indicate to users how "trending" works

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1341]
The trending list sorts videos by number of views in the last 7 days (default value). But it is not indicated to users that this is the case, the ordering appears quite random. This can be especially confusing when a one year old video is listed next to one from a few days ago.

In order to clarify this, why don't we add a line like "123 views in 7 days" to each video on the trending page? That would make it immediately obvious to users why each video is listed there.

This would also be a great way to differentiate Peertube from Youtube, where the sort order is completely intransparent. And it would bring us closer to the philosophy of Mastodon, namely to avoid "magic" algorithms influence the content users see.

Related to #1207.

**Comment by BO41** [comment]
good thing you point this out.
But I guess it would be even clearer to add a simple text box, or popup or whatever and write 2-3 sentences. Then it is clear for sure

**Comment by auberanger** [comment]
I'm currently working on this issue and on the #1409 (which are related).
I'm actually nor satisfied by the idea of a popup or by the use of the help component here. At least, it would be better to make it appear on hover of the Trending title. Otherwise, a simple text box appearing from "Trending" when hovered or clicked could be a good solution. But in this case, is there a preexisting component I could use ?
