### ISSUE TITLE
Followed instances' videos and channels are kept in cache after unfollow

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1379]
For example, this instance _peertube.moe_ doesn't follow the video.blender.org instance but if I add _/accounts/blender@video.blender.org/videos_ to the peertube.moe's url: _https://peertube.moe/accounts/blender@video.blender.org/videos_ then I can see some old videos which are cached or something, because those videos aren't the ones of the actual instance: https://video.blender.org/

Aside from this "cache" bug, I think it's a cool feature/bug to be able to watch your favorite peertuber on another instance, even if that instance doesn't follow the instance where the peertuber publishes his videos.

**Comment by Nutomic** [comment]
Disagree, this sounds terrible because it could be used to display illegal content on my instance, and I couldn't do anything about it.

**Comment by rigelk** [comment]
@Nutomic I'm not sure to understand: it wouldn't display content on your instance. It's just the user watching remote content from his interface/subscription feed.

**Comment by ldidry** [comment]
@Nutomic's argument seems valuable to me.

Example:
- user A watches a far-right video from peertube X on peertube Y
- user A gives the URL of that far-right video on social networks
- user B, that saw the URL on a social network and don't know a thing about peertube would believe that peertube Y hosts far-right videos (instead of the true hoster, peertube X)

**Comment by rigelk** [comment]
In my scenario the user is not capable of sharing a link, just to watch the video from his interface once authenticated on the instance.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/8d4273463fb19d503b1aa0a32dc289f292ed614e

But if the administrator enabled the remote search, users will still be able to escape the federation: https://github.com/Chocobozzz/PeerTube/commit/8d4273463fb19d503b1aa0a32dc289f292ed614e#diff-8e71c54313a9b8a1d6c20ceae3927846R62
