### ISSUE TITLE
Add ability to rotate video

### ISSUE THREAD

**Issue by Yetangitu** [Chocobozzz/PeerTube#1399]
I use PeerTube to host a large number of raw video material produced by older cameras which did not include an orientation sensor or did not add such information to the video metadata. This leads to a number of videos showing up sideways or upside-down.

Adding an option (to the edit component) to rotate video files would solve this problem. On the backend this can be implemented using `ffmpeg -i input.mp4 -c copy -metadata:s:v:0 rotate rotation output.mp4`, e.g.:

```
/**
 * Rotate video on display by manipulating metadata
 */
async function rotate (command: ffmpeg.FfmpegCommand, rotation: VideoRotation): Promise<ffmpeg.FfmpegCommand> {
  let localCommand = command
    .videoCodec('copy')
    .audioCodec('copy')
    .outputOption('-metadata:s:v:0') // change metadata for first video stream
    .outputOption(`rotate ${ parseInt(rotation) % 360 }`) // sanitize rotation

  return localCommand
}
```

**Comment by BO41** [comment]
do you mean after uploading?

or while seeing it?
what could a use-case be for that?

**Comment by Yetangitu** [comment]
Like above, I pressed `enter` too soon and ended up with an empty template instead of an issue...

**Comment by Yetangitu** [comment]
The above command rotates video without transcoding it and such is fast and lossless.

**Comment by Yetangitu** [comment]
I'm experimenting with the above concept, have not added anything to the client yet. If this is implemented it'd add `rotate` options to the client, a `rotate` endpoint to the API and a related command to the CLI tools.

**Comment by Yetangitu** [comment]
The main question here is whether PeerTube should add more 'advanced' editing options or whether it should be a pure hosting platform without any such options. In the former case a PeerTube instance can be used as a limited content managing platform, in the latter case all source material should be prepared and edited before it is submitted to an instance. For my use case the former is preferred but this might be the exception rather than the rule.

**Comment by BO41** [comment]
>whether PeerTube should add more 'advanced' editing options or whether it should be a pure hosting platform

I think #1029 discusses this, and this could be part of a basic editor

**Comment by Yetangitu** [comment]
#1026 looks far too heavy for the simple features I'd like to add, mostly those which can be achieved by manipulating metadata. Adding full video editing to PeerTube is definitely not what I'm after. The features I'd like to see would necessitate adding something like the function I posted above to `server/helpers/ffmpeg-utils.ts` plus whatever code is needed to call that function on those videos which the user wants to rotate, either through the web UI or the CLI tools (or similar API-related means).

**Comment by Bugsbane** [comment]
I'd suggest that at least for the moment video editing shouldn't be touched, however basic metadata editing should. I would place this in the latter category as, although it requires transcoding, both the interface needed, the code and cpu required are modest. Needing to rotate the video is also likely to be a very common use case with video uploaded from phones.

**Comment by Goutte** [comment]
Here's [some proof](https://video.samedi.pm/videos/watch/b6a6e51d-6c76-4104-9e90-80f7a9fde433) (not my instance) that mobile users need basic video rotating features.

Educating mobile phone users about the _landscape vs portrait_ attitude could be eased by supporting rotations, especially metadata ones as they're cheap.

As a hotfix, rotating using the ffmpeg tidbit suggested by the OP does not work for me. After editing the file on the server, the client tries to download the file (by chunks) over and over again, without any apparent error in the js console. (until the RAM bails out) Confusing, but sort of funny.

If, for kicks, I rotate using the `transpose=N` filter of ffmpeg, (which is not cheap cpu-wise), a new file size is generated and the client fails with a 416 because (I suppose) the torrent file has to be regenerated as well, or a cache of the filesize somewhere has to be invalidated.

---

Beyond metadata rotation for users, allowing admins to readily invalidate the cache around a video file after monkey-patching it however they desire would be great ; (perhaps we already can, and I'm just not looking in the right places.)

**Comment by Chocobozzz** [comment]
Closing as it's out of the scope of peertube. You can write a wrapper to download the video, rotate it and reimport it using PeerTube CLI tools: https://docs.joinpeertube.org/maintain-tools
