### ISSUE TITLE
Redirect to login

### ISSUE THREAD

**Issue by pinage404** [Chocobozzz/PeerTube#1431]
**What happened?**

I usually open link to videos in new tab to have a watch list

When restart my computer, i want to watch videos in the tabs that i didn't close

Note: my browser keep the session when i restart it

But i'm redirected to the login page, when i log in, i'm redirected to "Recently added" vides

**What do you expect to happen instead?**

When i log in, i would like to come back to the video page

**Steps to reproduce:**

1. open a video page
2. close your browser
3. wait 24h (expired session token ?)
1. start your browser
1. the page will be the login page

**Additional information**
* PeerTube version or URL: [PeerTube v1.1.0-alpha.2](https://peertube.mastodon.host/about/peertube)
* Browser name/version: Google Chrome | 70.0.3538.67 (Build officiel) (64 bits) (NixOS (Linux distribution))
* NodeJS version: i'm a user, i don't know how the server is configured

It's maybe related to https://github.com/Chocobozzz/PeerTube/issues/294

**Comment by pinage404** [comment]
Sorry i mistyped on `CTRL+ENTER`

**Comment by McFlat** [comment]
I can validate that this is the behaviour I've seen in the past, what we have to do is grab the current page url and pass it as a `nextUrl` or `redirectTo` url so that after login the user ends up back at the page there were at before being redirected to the login page. We can use that later in other ways to redirect a user to a specific page they want access to after login, only thing to know is basically to not redirect to a `schema://domain` url rather to a page url `/page`, this way we can make sure the site doesn't redirect a user to their bank page if cracker or spammers want to abuse the functionality it will keep it all on the actual site.

**Comment by BO41** [comment]
> * open a video page
> 
> * close your browser
> 
> * wait 24h (expired session token ?)
> 
> * start your browser
> 
> * the page will be the login page

if you have a video page open, why should it redirect you to the login? is this a private video?
If you are not allowed to view a page while not being logged in, you get redirected back to the page (like #294 suggested).

**Comment by pinage404** [comment]
I don't know why

the videos are public and (most often) fédérated from other instances

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dae5ca24b173aebd16de2a202ccd4088568b8dfb

Thanks for the issue @pinage404
