### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by m4sk1n** [Chocobozzz/PeerTube#148]
PeerTube should be available in more than one language, that's why it should support localization, I would be ready to translate it to Polish. The project could use platform like Weblate to make translating it easier. I think it's essential if the project is going to grow.

---

## Update (as of 03/16/2018)

- [x] partial implementation with multiple clients compiled
- [ ] Localization in PeerTube will be implemented when Angular will add translation lazy loading: https://github.com/angular/angular/issues/16477#issuecomment-352125838 (should be any time soon now)

**Comment by Chocobozzz** [comment]
I agree. I just have other things more important to do first so it could take a few months.

Just for information, we will use the Angular Internationalization: https://angular.io/guide/i18n.

**Comment by goofy-bz** [comment]
Of course you have "more important things to do" atm :) But please consider this requirement very seriously. Imho the i18n structure should be ready for the first public beta release. A complete English version is necessary, whatever translation platform you choose, for at least two reasons
1. translated versions (Polish, Spanish, every lang…) really helps the project to gain traction 
2. The earliest it can be localized the better it is because the more you wait the longest your i18l will be, you will have to process more files looking for scattered strings

**Comment by D4rk4** [comment]
I can help with Russian translation

**Comment by Chocobozzz** [comment]
@goofy-bz 👍 

I'll implement localization in PeerTube when Angular team will add translation lazy loading: https://github.com/angular/angular/issues/16477#issuecomment-352125838

I'll post an update when it will be done. So if some people are interesting in translating PeerTube, please subscribe to this issue :)

**Comment by rigelk** [comment]
The latest blocking PR status can be seen at https://github.com/angular/angular/pull/22931

**Comment by Chocobozzz** [comment]
Hello, thanks for your patience. Localization in PeerTube is not quite ready but we extracted the strings so you can begin to translate them.

Please see the [translation guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md) and tell me if it misses something.

**Comment by Chocobozzz** [comment]
Done: https://github.com/Chocobozzz/PeerTube/commit/8afc19a6121569da054462c7cb351a3f13030a32
