### ISSUE TITLE
Allow adding and editing subtitles inside Peertube

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1481]
This would make it much easier for video uploaders to add subtitles, because they could just type them on the video upload or video update screen. Additionally, we could allow users to contribute subtitles to videos, which would result in more subtitles available. All of this would be very useful for accessibility and helping users who don't understand the language.

The same request was already made in an [earlier comment](https://github.com/Chocobozzz/PeerTube/issues/72#issuecomment-384809373), and upvoted by a bunch of people, but is now apparently forgotten.

I understand completely that this is very hard to do, so see it more as a wishlist item.

**Comment by ldidry** [comment]
For the record, here's a npm module to parse srt files: https://www.npmjs.com/package/subtitle

**Comment by albjeremias** [comment]
this is a killerapp feature for peertube... a very powerful tool for the objectives of this project!

**Comment by Niquarl** [comment]
YouTube will be removing their community subtitles feature on september 28th so adding this to PeerTube would really boost in my opinion the larger public and video creators towards PeerTube as a viable alternative. I hope for the next fundraiser we could have this feature in the roadmap.

**Comment by ketsapiwiq** [comment]
Maybe allowing subtitles upload (whole .srt files) from the community and validation from the admins is easier to add than a whole editing system? It would be a useful first step at implementing a fully-fledged subtitles editing UI, while still allowing volunteers to contribute.

**Comment by Niquarl** [comment]
Just got the email because of the new message and I'd like to mention that a couple of external websites do provide subtitle support, both to pay professionals or community focused. In my opinion, the best one for severall reasons is amara.org, unfortunetaly it doesn't support PeerTube videos. Perhaps we should contact them to add that support until PeerTube gets a subtitling feature. In that case the use of community uploaded srt files could be a solution, with the video uploader having to confirm it.
 I noticed also that Framasoft's 'What is PeerTube?' video is being subtitle throught webplate, but I don't think that's a good solution but wanted to mention it, you can check it out in the description of said video.

**Comment by koalp** [comment]
> In my opinion, the best one for severall reasons is amara.org

Is it open source and can it be self-hosted ? (and federated ?) I haven't found anything suggesting that it is.
I don't think that it should be integrated into peertube if it isn't the case. Maybe as a plugin then ?

**Comment by lulucasono** [comment]
How is amara better than using something like aegissub ?
Also considering that for me the standard was the now gone youtube editor. I don't want to create an account to test amara, that's why I am asking.

thank you

**Comment by Niquarl** [comment]
Amara.org is not opensource, unless I am mistaken.
I contacted them about adding the option to translate PeerTube videos on their website, just like for YouTube and Vimeo. It's not about adding any code to PeerTube, just to be clear. It would just use an embed of the PeerTube video essentially. If someone wanted to make a pluging, by all means of course. I don't think that is necessary however at all.

I do not know Aegissub very well, especially the newer versions but as far as I know it is not very user friendly for one. Amara's 'feature' is that it is on the web, just like YouTube's, so everybody can just transcribe/translate the video collectively, just by each doing a couple of lines and it being automatically sync.

Amara is pretty much the same as YouTube with a couple different feature in their editor, with IMHO better looking design. This is a personal opinion of course.

**Comment by NoMoreCRAPTion** [comment]
Amara used to be open source. Participatory Culture Foundation made the source private as reasoned here: https://blog.amara.org/2020/01/13/why-we-are-closing-amaras-source-code/.

Josef Andersson archived the source code on GitLab before it went private: https://gitlab.com/hanklank/amara-archive. Andersson included a disclaimer not to contact PCF for support after 2020.

Here is the archived copy from Wayback Machine: https://web.archive.org/web/20191118083609/https://github.com/pculture/unisubs

You can find forks of the Amara/Universal Subtitles project with various instructions on how to self-host over the last eleven years. The licencing is AGPL v3.0.

**Comment by NoMoreCRAPTion** [comment]
> How is amara better than using something like aegissub ? Also considering that for me the standard was the now gone youtube editor. I don't want to create an account to test amara, that's why I am asking.
> 
> thank you

Circumstances and mentality are different.

Amara is a byproduct of the "crowdsourcing" and "open web" culture of the Internet which emerged in late 2000s and early 2010s. It's similar to using Weblate or CrowdIn, except you get to see the video playback within the browser. Idea was anyone could contribute then others will come along and pick up what the previous person left behind.

Aegisub, Sabbu, Medusa, Subtitle Edit etc arose in late 1990s to early 2000s when collaborative process was done through sharing files and software through FTP, IRC, torrents, emails etc instead of through the web browser. At that time, it was better to have a small team of people you knew instead of relying on the public to prevent passion projects from becoming dead ends. At that time, it makes sense to keep everything on your hard-drive or other people's hard-drive instead of stored in someone's database, in a repository or in the cloud.

**Comment by NoMoreCRAPTion** [comment]
> Just got the email because of the new message and I'd like to mention that a couple of external websites do provide subtitle support, both to pay professionals or community focused. In my opinion, the best one for severall reasons is amara.org, unfortunetaly it doesn't support PeerTube videos. Perhaps we should contact them to add that support until PeerTube gets a subtitling feature. In that case the use of community uploaded srt files could be a solution, with the video uploader having to confirm it.

There is a Chrome extension which is hacky work-around for the .org website, not the self-hosting solution: https://github.com/yashagarwal1411/SubtitlesForYoutube, which doesn't rely on the uploader to maintain the subtitle files.

All it does is look for subtitles from Amara, OpenSubtitles etc to sync to YouTube videos. I don't know what percentage of PeerTube's videos have the same content ID as YouTube's.

**Comment by NoMoreCRAPTion** [comment]
Using Amara Embedder does work:

https://support.amara.org/support/solutions/articles/243227

But only if you use the direct download link for the MP4 file while adding the video file to the public repository, which is not ideal for server loads.
