### ISSUE TITLE
Cannot comment/subscribe from Mastodon (hostux.social) to Peertube

### ISSUE THREAD

**Issue by Folaht** [Chocobozzz/PeerTube#1528]
**What happened?**

I get the error: 
Unfortunately, there was an error looking up the remote account.

**What do you expect to happen instead?**

Simply to log in.

**Steps to reproduce:**

1. Open a hostux.social account.

2. Comment on https://peertube.heraut.eu/

3. Click on 'interaction distante'

**Additional information**
* PeerTube version or URL: 
https://peertube.heraut.eu/videos/watch/bb41ae7c-1668-4717-9c10-d74b825c7d8e

**Comment by blakeearth** [comment]
I'm also having this issue. Some additional information (almost made a new issue): when I try to subscribe to channels (using PeerTube's remote subscribe feature) instance running 1.2.1 on any PeerTube (among those I have tested) using my Mastodon account on fosstodon.org, I get the message "[u]nfortunately, there was an error looking up the remote account." I can subscribe to channels on Blender's instance, which runs 1.0.1 at the time of writing. I experience the same behavior when trying to comment via Mastodon.

1. Navigate to a PeerTube video on an instance running 1.2.1.

2. Attempt to subscribe to a PeerTube channel via the orange subscribe button. Alternatively, try to leave a comment.

3. Use a Mastodon account (I have tried accounts on fosstodon.org and mastodon.radio).

**Additional information**
* PeerTube version or URL: 1.2.1
* Browser name/version: Brave Version 0.63.11, Firefox Version 65.0.2
* NodeJS version: Unknown

I briefly discussed this issue with plhardy here (starting at 3; the other issue was due to a bad password): https://framacolibri.org/t/only-able-to-use-root-account-cannot-subscribe-via-mastodon/4669/3

**Comment by gbip** [comment]
I do also have this problem with the latest Peertube (1.2.1) and the latest Mastodon (2.8.2) :

> Malheureusement, il y a eu une erreur en cherchant les détails du compte distant 

It is also impossible to subscribe from the Peertube interface with a Mastodon account (with the same error).

**Comment by raphgilles** [comment]
Same error here. And of course, it's impossible to comment and subscribe from Mastodon.
With PeerTube 1.3

**Comment by ProgVal** [comment]
I noticed this with my Mastodon instance. Curiously, the issue occurs if the client uses Chrome, but not Firefox.
I don't see anything relevant in the mastodon logs or the browser's console.

**Comment by ProgVal** [comment]
Apparently, it does not work with all Firefox installs

**Comment by Chocobozzz** [comment]
Thanks @ProgVal, I came to the same conclusion. I applied [a fix](https://github.com/Chocobozzz/PeerTube/commit/3ddb1ec5553167b0b1cb852e906a691ea65522a4) last week deployed on peertube2.cpy.re.

Could you try to reproduce this issue by following https://peertube2.cpy.re/video-channels/test123_channel/videos?

**Comment by ProgVal** [comment]
It works :)

**Comment by agharbeia** [comment]
Was this fixed released? Starting which version?
I'm trying to demonstrate the cross-service following capabilities of the Fediverse, but so far I haven't been successful in finding properly working instances.

**Comment by rigelk** [comment]
@agharbeia this fix is part of version 1.3.1 and up.

**Comment by agharbeia** [comment]
Thanks, @rigelk.
I tried it using my account at [our Mastodon instance](https://zalluma.adef.xyz/@ahmad) from one [version 2.0 PeerTube instance](https://peertube.video/videos/watch/bad58735-a8a9-4636-b297-d209e44a146d) but I get a "server error" message at the Peertube site. I can subscribe by searching in Mastodon for the Peertube handle, however.
But I wanted to demo seamless interaction and subscription across instances and applications.
Any insights?

**Comment by rigelk** [comment]
@agharbeia you tried subscribing to a Mastodon account from a PeerTube account ?

**Comment by agharbeia** [comment]
I tried to subscribe to a Peertube channel using my Mastodon account. I couldn't authenticate.
I tried commenting on a PeerTube video using my Mastodon account, and got a "server error".
But, if I go to my Mastodon web interface and search for the handle of the peertube user I can subscribe to their channel. Also I can boost a video if I search using its peertube-URL in Mastodon.

**Comment by agharbeia** [comment]
Sorry, I created an issue by mistake.
