### ISSUE TITLE
Canonical link injected into HTML is invalid

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#1539]
It links to the current URL of the video whereas it should link to the URL of the video on the original instance.
https://github.com/Chocobozzz/PeerTube/blob/e76d578414d2f2f853bbb1d4bbe180da05aa4eab/server/lib/client-html.ts#L119
https://github.com/Chocobozzz/PeerTube/blob/e76d578414d2f2f853bbb1d4bbe180da05aa4eab/server/lib/client-html.ts#L191

While it should be something like
```ts
tagsString += `<link rel="canonical" href="${video.url}" />`
```

Should improve SEO a bit.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/c04eb647db4f543a31a8100c1ec9a86c700bca6a

Thanks @tcitworld 

> Should improve SEO a bit.

Unfortunately, Google bot uses a very old chrome engine so it cannot parse our javascript and it internally renders a blank page. And Angular CLI (developed by google) does not support Babel so...

![office-blased](https://user-images.githubusercontent.com/5180488/50977288-43952600-14f2-11e9-8ed4-ca4383c768b1.gif)

**Comment by Chocobozzz** [comment]
@tcitworld No, I'll try to find the dependency that ship ES2015 code and pin it to a previous version instead.
