### ISSUE TITLE
Docker - invalid_client: Invalid client: cannot retrieve client credentials

### ISSUE THREAD

**Issue by UnR34L** [Chocobozzz/PeerTube#154]
Using this docker image: https://hub.docker.com/r/chocobozzz/peertube/

I see 'invalid_client: Invalid client: cannot retrieve client credentials' above the login box.

I can't login, as root/admin/administrator.

[Stdout logs](https://pastebin.com/ikArgcJ1)

[Stderr logs](https://pastebin.com/x8eHwHF8)

**Comment by Chocobozzz** [comment]
I'm sorry but the docker image is not maintained anymore.

Your issue is that you need to configure the PeerTube inside the container to use the correct host/port for the webserver (https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L5).

The root password is displayed at the beginning of the logs.

**Comment by UnR34L** [comment]
> The root password is displayed at the beginning of the logs.
I read that in the docs and tried that.

I'll try a full install.

Cheers.
