### ISSUE TITLE
Alternate content Rating

### ISSUE THREAD

**Issue by sschueller** [Chocobozzz/PeerTube#1588]
I think a more complex content rating system would be much better than just NFSW or not. 

NSFW is too simple to work with larger markets. For example, while in the US excessive violence is something you see all day on TV you never see nudity. However in Europe it is more common to see nudity than excessive violence.

It should be up to the viewer to decide what content he/she wants to see and in order to do that I find a more complex rating system is needed. 

I also find age rating systems too vague. 

A system of adding content rating "tags" in my opinion would work best. For example something like this:

- V (Violence)
- N (Nudity)
- S (Sex)
- L (Language)
- X (Death)
- etc.

For more example see: https://en.wikipedia.org/wiki/Television_content_rating_system.

This way I could set what kind of content I want to see or at least I would know before watching something.

What do you guys think?

**Comment by Nutomic** [comment]
I agree with you, the NSFW system isnt good, because its not clear what it actually warns about. The system you suggest would definitely better, but I think it would be too rigid in some cases. Why not go with a content warning system like on Mastodon, where the uploader can specify the warning themselves?

**Comment by sschueller** [comment]
With the recent NSFL videos appearing I think something like this would really help letting people pick what they want to see and not have everything lumped into one tag.

**Comment by fenarinarsa** [comment]
Looks like those issues have been opened for many years with little to no progress.

As far as I'm concerned, I had to completely disable the blur filter since the very beginning. I'm not showing anything explicit in the thumbnails, and having blurred thumbnails + title in a list of dozens of videos completely defeats the purpose of showing the videos in the list in the first place.

It may work for a social network where you can chose what you want to see as a user in your own settings, but not for a video instance where you just go to watch videos without any need to create an account (and account creation is disabled anyway).

But of course, disabling blur also means there's no warning dialog when playing a sensitive video or a live because both behaviors are linked (which honestly I still don't understand why after all this time), and maybe the information is not conveyed through ActivityPub as well.

I quickly looked if I could disable the blur filter in CSS using the simple CSS setting in the instance's setup, it may be a dirty and fast solution, but I couldn't make anything since the use of inline CSS selectors with dynamically generated names seems to make it impossible to override anything (I'm not a web dev so maybe I missed something).

Anyway currently the blur feature is 100% useless in my use case. I just added a 🔞 at the beginning of each video's title hoping users will not make any bad click/tap.

**Comment by Chocobozzz** [comment]
You can remove blur using this custom CSS:

```css
#custom-css .video-thumbnail img.blur-filter {
  filter: none;
}
```

`#custom-css` allows you to override PeerTube styles

![screen_2023-03-10-08:40:20](https://user-images.githubusercontent.com/5180488/224253643-df3cdd9d-9af6-485b-88f3-2bb2f86ce100.png)

**Comment by fenarinarsa** [comment]
Thanks! I really didn't hope for a way to change Peertube styles like this.

This is a perfectly acceptable workaround. It should even be documented! 😺

Case closed, as far as I'm concerned.

The complete extra CSS code:

```
#custom-css .video-thumbnail img.blur-filter {
  filter: none;
}

#custom-css .video-miniature-name.blur-filter {
  filter: none;
}
```

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6144
