### ISSUE TITLE
orphan video

### ISSUE THREAD

**Issue by NeodarZ** [Chocobozzz/PeerTube#16]
Hello,

I have installed the last demo version of PeerTube and upload a video (Rien à cacher - Jérémie Zimmermann, La Parisienne) for test.
Then, I have drop the folder of PeerTube without delete the video uploaded.

But the video still listed in the list of videos and, of course, the video didn't work.

So I didn't think that is normal... ^^

But otherwise, it's a awesome idea ! ;)

**Comment by Chocobozzz** [comment]
Hi,

Thanks to have tested it! :) Yes this is normal, you should not deleted physical PeerTube folders. Please try to remove the video throught the web interface because you made friends with other pods (http://peertube2.cpy.re/videos/list) so the video is unreachable.

Do not hesitate if you have other feedbacks!
