### ISSUE TITLE
Android "PeerTube" app may be hurting PeerTube's reputation

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1624]
I'm not sure if there's anything we can do about it, but I wanted to make sure the devs are aware. I just heard about this from a user, via Twitter.

The user's first impression of "PeerTube" was from running across this Android app, which seems to hardcode a troll-themed peertube instance:

https://github.com/sschueller/peertube-android/blob/88b53324eab30a1e71347150463f2ffa35caad82/app/src/main/res/values/strings.xml#L40

They came across it via the F-droid store here:

https://f-droid.org/packages/net.schueller.peertube/

This initially gave this user the impression that PeerTube is (1) a single video collection, and (2) a quite undesirable one.

Are there ways we can prevent unrelated apps from using the PeerTube name, either by asking nicely or via legal protection?

Perhaps more actionable: Are there ways to spread the word about what PeerTube actually is and isn't, to reduce the impact of apps like this?

**Comment by rigelk** [comment]
Thanks for the alert - the impact of the app's choices and lack of communication to the user had gone mostly unnoticed.

A first thing could be to ask them to rename their application, as this by itself is misleading users into thinking the PeerTube ecosystem amounts to the instance they chose as default.

Another things could be to ask them to do a proper introduction/tour of what is PeerTube on first app use.

More thoughts once we get feedback.

**Comment by sschueller** [comment]
I have no problem with changing the default instance to something else or even changing the name of the app. There is no gain for me in this, I do this in my free time and unpaid as I believe in the project. 

The primary reason for using troll.tv as the default is because it is my instance and I can make sure it works. For example there is an issue with the Peertube configuration of nginx ciphers (https://github.com/sschueller/peertube-android/issues/36) which prevents users with an Android 7 device from accessing Peertube.

I try to only follow instances that are "clean" as in correctly mark their NSFW content but I haven't updated the follow list in a while. The instance itself has 5 videos and registration is closed. All other videos are from the instances that are being followed.

My goal ist to offer a intro where an instance can be picked that supports registration. I am in the process of implementing https://github.com/sschueller/peertube-android/issues/1 which pulls a list of servers from https://instances.joinpeertube.org .

Please also keep in mind the app is still beta and is listed as pre-release in the play store. I have placed the app on F-Droid because I was asked to not because the app is ready for prime time.

**Comment by lishoujun** [comment]
@scanlime the android peertube is not unrelated app, and it is open source too. you are welcome to join to commit your code.

**Comment by sschueller** [comment]
FYI, I will be renaming the app: https://github.com/sschueller/peertube-android/issues/132

**Comment by Chocobozzz** [comment]
Thanks @sschueller :+1:
