### ISSUE TITLE
Link to a specific comment

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#168]
The « x min ago » text should link to the comment.

**Comment by Aluriak** [comment]
I've always found that behavior weird and unexpected.

Why not a 🔗 icon appearing when hovering on the comment ?
Would be much more explicit and easier to understand.

I would expect clicking/hovering the «x min ago» giving me the exact date instead. Because the «x min ago» soon became «x days ago», then «x years ago». Not really helpful when trying to get a precise date of a conversation.
(unless the time is implemented using something like [hyperloglog](https://en.wikipedia.org/wiki/HyperLogLog) ?)

**Comment by Chocobozzz** [comment]
Implemented by @jonathanraes: https://github.com/Chocobozzz/PeerTube/commit/d5b53822ae7e1660cebe3a35be5ce76ea73dc1b9
