### ISSUE TITLE
Improve Peer-to-peer Privacy

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1724]
I'd like to open this issue for suggestions and ways to mitigate the downsides (from a privacy perspective) of p2p described [here](https://github.com/Chocobozzz/PeerTube/blob/74cd011b6c089cac88a4b8aa76ad3be2ca4f1c15/client/src/app/%2Babout/about-peertube/about-peertube.component.html).

**Comment by Jorropo** [comment]
First solution is to have an enormous amount of viewers per videos so the limit of 20 can works but that doesn't depend of us and can be still by passed with redundancy (as web seed you get all ips).

I think a good solution is to make a coroutine running in the background simulating viewing of random videos, so that will be impossible to guess is it real or not ?
No need to send on view endpoint because be spyed by your main instance (the one you use to view and comment and post) isn't a real problem (you can just switch instance).
So each 2 - (time of the fakely viewed video) minutes a corountine will switch the fakely viewed video.
We need to also broadcast view at a static time per day (because you can just watch view, if it grow its a real view, if not its a fake (that only true for small video because bigger will add random)) like each hour, and send the view of the pre past hour so if you watch a video at 6:58 your view will be broadcasted at 8h, for video longer than 1h we need to add more delay because the view mustn't be broadcasted while viewing the video.
And we can broadcast each 10 views because that create some confusion for a spyer.

The problem of this is, cost of bandwith and cpu.

**Comment by Chocobozzz** [comment]
> Lunch some js deamon running webtorrent on all video that you wan't to spy, and while peertube will still not very used all of the viewers will be presented to you.
That is maybe not very easy but can be done by almost any one who know js with time.

We log this kind of behaviour: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/tracker.ts#L108

> Query the tracker like a dumb guy to get all the nodes.

WebRTC peers are not exposed by the tracker

**Comment by Zig-03** [comment]
may be relevant to this issue - [Tribler](https://github.com/Tribler/tribler)

**Comment by Chocobozzz** [comment]
Closing this issue now you can disable P2P as a user and disable the tracket as an admin.
