### ISSUE TITLE
Account/instance mute badge disappears

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1748]
After muting an actor, refreshing the page undoes the red "mute" badge and possibly removes the mute itself. Checking the moderation tab shows that it's still muted, but not according to the profile pages.

**Additional information**
* PeerTube version or URL: https://dialup.express
* Browser name/version: Firefox 66.0.1
* NodeJS version: v8.15.1

**Comment by realityfabric** [comment]
This happens for me as well. Mute an account, red mute badge appears. Refresh or otherwise reload the page, badge is gone.

It is still listed as muted in the settings, and videos from the account disappear from the trending videos until the account is unmuted.

Using Open.Tube with Chrome 74.0, and with Chrome 75.0

**Comment by Chocobozzz** [comment]
Finally fixed in https://github.com/Chocobozzz/PeerTube/commit/80badf493afca026bc542260f353210e605a1715
