### ISSUE TITLE
Do not transcode uploaded video again if it is encoded correctly

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1780]
This has been mentioned before in various places, but there seems to be no issue for it yet. The idea is that many videos uploaded to Peertube are already encoded with the correct flags like faststart, so there is actually no reason to transcode them again. Especially videos that were imported from youtube, or that were made specifically for Peertube.

So we should add a check, which might save a lot of transcoding time. As far as I can see, these are the things we should check for:

- [ ] faststart flag is set
- [ ] video codec is h264
- [ ] audio codec is aac (?)
- [ ] container format is mp4
- [ ] video bitrate is below `getMaxBitrate()`
- [ ] audio bitrate is below some limit (not sure how the current code is limiting bitrate)
- [ ] fps are between 10 and 60
- [ ] some check for resolution/aspect ratio?
- anything else?

Even if these all match, we should probably still do a quick `ffmpeg -c:v  copy -c:a  copy` to get rid of any extra tracks or other unneeded stuff (this should be really fast).

I will try to implement this myself.

**Comment by rigelk** [comment]
@Nutomic I've already done something there: https://framagit.org/rigelk/kitchensink/tree/master/src/ffmpeg-isStreamable

**Comment by ealgase** [comment]
There's still no need to transcode even if the faststart flag isn't set.  We can just do `ffmpeg -i video.mp4 -c:v copy -c:a copy -movflags faststart streamable.mp4` and save the CPU cycles.

**Comment by Nutomic** [comment]
@ealgase Thanks, that is very useful because it means we dont have to check if the uploaded file was encoded with faststart. Looking at rigelk's code, that looks very complicated.

@rigelk Cool, thanks. I will probably copy some parts of that over. Is there any reason you didnt try to get this merged into Peertube?

**Comment by rigelk** [comment]
@Nutomic I can fully explain the part about faststart if need be. As simple as the command provided by @ealgase may be, my command is still useful to at least check if we can completely avoid any additional task spawning.

I didn't try to merge this into PeerTube because, depending on how and where you want to integrate it, you have to deal with the existing upload process which is quite a big refactoring if you ask me. At that time I wanted to allow user-provided resolutions and that was too big of a task… I should have thought smaller ^^'

The simplest case would be to use my function to check if the input file can be used in place of one of the target resolutions. That would require minimal refactoring (actually none if you just modify the task itself) to the upload process.

**Comment by Nutomic** [comment]
I was thinking to run the basic transcoding task anyway (with copying the codecs), because that also lets us get rid of additional tracks, subtitles, metadata and so on. And even for a long video, it should be a matter of seconds. So avoiding transcoding entirely would need a lot of checks, and seems like overkill to me.

I just want to change the transcodeOriginalVideofile() function, and that looks very straightforward. As far as I see, Peertube always keeps the same resolution that was uploaded, so I dont think there is a need to check the target resolutions (maybe in case of a weird aspect ratio).
