### ISSUE TITLE
Add a list of predefined report reasons

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1781]
I think we need to change the report form and make it look like [this](https://duckduckgo.com/?q=How+to+Report+YouTube+Videos+and+Comments&t=ffab&iar=images&iax=images&ia=images&iai=https%3A%2F%2Fwww.howtogeek.com%2Fwp-content%2Fuploads%2F2018%2F01%2F5reporting.png) with predefined report reasons, and maybe even add some text that says if the report is gonna be anonymous or not.

**Comment by XenonFiber** [comment]
It'd be better if the reasons were check boxes instead of a single selection.

**Comment by Zig-03** [comment]
> It'd be better if the reasons were check boxes instead of a single selection.

I like the idea but I'm afraid that feature will be abused - people will just sellect all boxes without even reading them.

**Comment by XenonFiber** [comment]
@Zig-03 It sends a single report out regardless of the reasons, and I'd have to watch the video/read the message anyway.

**Comment by Zig-03** [comment]
> @Zig-03 It sends a single report out regardless of the reasons, and I'd have to watch the video/read the message anyway.

Usually it is not mandatory to write a message if you've already checked the corresponding box, are you suggesting to make it mandatory for users to write "at least something" + checking the boxes?

**Comment by XenonFiber** [comment]
Nope.

**Comment by rigelk** [comment]
I tried to think of a list of reasons:

- **Violent or repulsive**: contains offensive, violent, or coarse language or iconography.
- **Hateful or abusive**: contains abusive, racist or sexist language or iconography.
- **Spam or misleading**: contains marketing, spam, fraud, or otherwise misleading thumbnail/text/tags.
- **Privacy**: contains personal information that could be used to track, identify, contact or impersonate someone (e.g. name, address, phone number, email, or credit card details).
- **Infringes my rights**: infringes my intellectual property or copyright, wrt. the regional rules with which the server must comply.
- **Breaks server rules**: anything not included in the above that breaks the terms of service, code of conduct, or general rules in place on the server.
- **Thumbnails**: the above can only be seen in thumbnails.
- **Captions**: the above can only be seen in captions (please describe which).

references:
- https://qph.fs.quoracdn.net/main-qimg-b0a7abf85401f946a50c590c7813ec51
- https://www.howtogeek.com/wp-content/uploads/2018/01/5reporting.png
- https://i.ytimg.com/vi/POhoGl5MS40/hqdefault.jpg (i like the timestamp and textarea that is related to the reason, hinting that we could also have a textarea per reason?)

It is just a draft, ofc. @XenonFiber do you have other/different report reasons in mind?

**Comment by XenonFiber** [comment]
This seems pretty encompassing.
