### ISSUE TITLE
Add complete username on account page

### ISSUE THREAD

**Issue by valvin1** [Chocobozzz/PeerTube#1843]
**What happened?**
When I want to add an account on my friendica instance I need to have a complete AP username `@username@server.tld` but I can't find it on account page. I can only see "username" whitout server.tld.

**What do you expect to happen instead?**
Having near the user (in small) a complete username `@username@server.tld` or `username@server.tld`

**Steps to reproduce:**
In my case I was watching a video on [Touhoppai instance](https://peertube.touhoppai.moe/videos/watch/8a9a054a-b1ac-4658-b363-e3212bc52054)
I click on user who posted the video and i'm redirected on its [account / video page](https://peertube.touhoppai.moe/accounts/touhoppai/videos)
I can only copy username : `touhoppai` but not its complete username `@touhoppai@peertube.touhoppai.moe`

**Additional information**
* PeerTube version or URL: v1.3.0-rc2
* Browser name/version:Firefox 67

**Comment by NassimBounouas** [comment]
Hello,

I guess that the complete username is not displayed when the account is displayed from its original instance. In this case, the name is truncated.

**What I found :**
- The account complete name is displayed [there](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/%2Baccounts/accounts.component.html#L10).
- This field is created [there](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/account/account.model.ts#L21) and the function called is [this one](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/actor/actor.model.ts#L31).

This is, I guess, the explanation for this difference between [Touhoppai profile on its instance](https://peertube.touhoppai.moe/accounts/touhoppai/videos) and [this profile on p2p legal instance](https://tube.p2p.legal/accounts/linux@peertube.mastodon.host/videos).

Is this behavior mandatory @rigelk  or can I do a PR with a modification ?

Thank you !

**Comment by Chocobozzz** [comment]
Hi,

This behaviour is intended to easily differentiate between a local account and a remote account. I think we should keep this behaviour, except on the account page. What do you think?

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz !

Thank you for your response, It seems that the static function I pointed [(this one)](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/actor/actor.model.ts#L31) is the one called for the account page rendering as I showed in my previous message and the same one is called for miniatures display [there](https://github.com/Chocobozzz/PeerTube/blob/3a0fb65c61f80b510bce979a45d59d17948745e8/client/src/app/shared/video/video.model.ts#L112) and [there](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/video/video-miniature.component.html#L26).

I think the best suggestion we can keep is yours. Maybe, can we add a parameter to this function in order to force the host to be added (in the account page) by adding this boolean parameter to skip the host verification (Line 31 on actor.model.ts) and let the previous behavior on other use case.

**Comment by valvin1** [comment]
I agree only the accout / user page is enought. On other pages it makes sense to have only the username.
It is what I imagined when writing this request 😃

**Comment by bolikahult** [comment]
Little suggestion : if this complete username is displayed _to be copied_, why not add a "copy button" right after ? (like this [example](https://www.flaticon.com/free-icon/copy-outlined-circular-button_52847))

**Comment by NassimBounouas** [comment]
Hi,
@bolikahult  indeed your suggestion is wise. A "copy button" could provide a better user experience than an old plain text field to copy the complete username.

**Comment by Chocobozzz** [comment]
Closing since the suggestion in https://github.com/Chocobozzz/PeerTube/issues/1843#issuecomment-497613863 was implemented by @NassimBounouas.

**Comment by valvin1** [comment]
Thank you (a bit late) @NassimBounouas @Chocobozzz for the implementation :)
