### ISSUE TITLE
When watching a playlist, videos should not resume, and autoplay should be forced

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1889]
**What happened?**
With this configuration:
- autoplay disabled
- history (and video resume) enabled

When I'm watching a playlist, each video resumes at the last timestamp in my history, and next video does not start automatically.

**What do you expect to happen instead?**
Video should start at 00:00, and autoplay should be activated.

**Additional information**
* PeerTube version or URL: 1.3.0
* Browser name/version: Firefox

**Comment by filmaidykai** [comment]
Yea same thing and for me

**Comment by ufm** [comment]
I think autoplay really should be enabled. But resume should be more complificated:
First played video (and position in video) in playlist should be last video (and position) which stopped at the last time. When we move from one video to another due to autoplay, we should really start from 00:00 regardless of whether we watched this video or not.

**Comment by Chocobozzz** [comment]
I don't understand the part with autoplay. But regarding auto resuming I propose:
 * On video click -> resume
 * On video next -> starts at 00:00
 * On playlist click -> starts the first video at 00:00

**Comment by JohnXLivingston** [comment]
I disabled autoplay on my account (because when I do my moderating job, I don't want videos to autoplay each time I open their page). When I launch a playlist, each time it goes to the next video, I have to click on play again.

**Comment by Chocobozzz** [comment]
@JohnXLivingston It's the correct behaviour since you disabled autoplay.

What we could do however is to add a switch like youtube does on top of the playlist to enable/disable autoplay. If you're interested in such thing please create an issue.

**Comment by JohnXLivingston** [comment]
In a playlist context, I think the first click on play should be consider as : «I want to watch entire playlist».

(anyway, the enable/disable button is a good idea)

**Comment by JigmeDatse** [comment]
I'm not sure what I think, I don't want to enable autoplay except in playlists.  On YouTube the, "autoplay" enable thing toggles it globally.  What I *think* I'd like to see is, "auto play videos" vs. "auto play playlists."  But I'm not sure.

**Comment by rigelk** [comment]
As of 12f18b90ba6395464606052bb1bdfedb6b83df13, playlists now ignore user history and start from 0, unless specified from the url parameters/the playlist itself.

I made sure `autoPlayNext` (one will go to the next video on the end of a video) can be toggled and is enabled by default for playlists, but didn't force `autoPlay` (making the player start the video automatically) yet.

**Comment by Chocobozzz** [comment]
> Video should start at 00:00

I depends. I want my videos to resume from my watch later playlist. And sometimes I want the videos to start at 00:00 (music playlist for example). Then, we have multiple possibilities:
 1. Add a setting per playlist to enable or not resume (if I create a "conferences" playlist, I would set resume to true and if I create a "musics" playlist  I would set resume to false for example)
 2. Add another button in the playlist window to enable/disable resume (so it would be a setting per user, and not per playlist as in 1.)
 3. Automatically resume videos when on user click, and starts it to 00:00 when the next video is automatically played (I think it's the Youtube behaviour)

I prefer the third solution, because 1. & 2. adds UX complexity

> and autoplay should be activated.

No, videos should starts according to users preferences. If you disabled auto play in your preferences then PeerTube respects that.

**Comment by rigelk** [comment]
@Chocobozzz I implemented option 3, as discussed.
