### ISSUE TITLE
Add ability for an administrator to remove any video

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#19]
For now, only the user that uploaded the video can remove it. The idea is the pod administrator should have the possibility to remove any video (remote or from another user).

- [ ] Add ability to remove a remote video (the video is remote, we do not notify friends)
- [ ] Add ability to remove a video of another user that is on the same pod (so the video is local and we need to notify the video removal to our friends)

**Comment by Green-Star** [comment]
Hey @Chocobozzz , I would like to work on this feature but I have some problems understanding the expected behaviour.

> Add ability to remove a remote video (just on the pod, do not notify friends)

If I understand well, admin will be able to "hide" a remote video, i.e., remove it on the local pod but the video will still be reachable on the friend pods (and on its friends).

> Add ability to remove a video of another pod user (on the pod and on pod friends, so notify them)

Completely remove a video, i.e. remove it on the pod and on our friends too.

Is that correct ?

**Comment by Chocobozzz** [comment]
Yes this is correct :)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/198b205c10dba362b9ae1ef6895b29d7e0dd685f
