### ISSUE TITLE
Additional peers can slow down video streaming

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2047]
**What happened?**

When viewing a relatively popular video on a fast server, performance can be much worse than when viewing a less popular video because additional peers can be much slower than the main server.

This results in frequent video pauses and stalls, much more so than on videos without these slow peers.

**What do you expect to happen instead?**

If some peers are significantly higher performance than others, I expect them to take priority. I expect slow peers to time out quickly, especially when there exist very fast peers.

**Steps to reproduce:**

1. Many of the videos on https://diode.zone/videos/trending reproduce this issue currently. Right now I'm seeing it on this video: https://diode.zone/videos/watch/030c97eb-2c6f-4379-8873-5708eb68e6b4

2. Affected videos (with >1 peer) will be slower, at least assuming the main server is quick from your network location. Videos with only 1 peer load quite fast assuming you have a low latency connection to the main server.

3. You can verify the peer network traffic and the stalls in the browser's network inspector. Some peers can take many seconds to respond when the main server has a latency of milliseconds.

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: Firefox 68.0.2
* NodeJS version: v8.16.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by realityfabric** [comment]
I also noticed this, I had 5 peers but the video buffered multiple times for https://diode.zone/videos/watch/fdab6162-c5e9-4920-8006-23bc605b8306 when I hadn't had any other problems with 1 peer.

**Comment by Chocobozzz** [comment]
On HLS and WebTorrent videos or only on HLS videos?

**Comment by scanlime** [comment]
Definitely on HLS, not sure if this also applies to torrents.

**Comment by scanlime** [comment]
I think part of this problem is specific to HLS and part of it is not.

• The server could be doing a lot more to validate redundancy before providing additional peer URLs to clients. One of the peers was completely unreachable for a long time and wasn't even a valid follower, and the server happily gives clients this URL which will never work.

• The HLS player specifically (not sure if it's worse than the torrent player) will get wedged when one peer is unreachable or very slow.

For now I'm manually avoiding this issue by deleting peers from the SQL database.

```peertube_prod=> delete from "videoRedundancy" where strategy is null;```

**Comment by Chocobozzz** [comment]
Should be better with https://github.com/Chocobozzz/PeerTube/commit/da3324177025b15ca23d84dd4249e3c7ba95053c

**Comment by scanlime** [comment]
It does look like da33241 helps, but I'm still seeing pauses in playback when it appears that some of the peers are occasionally much slower than the HLS player expects. I'm seeing occasional pauses in playback when the HLS player could have retried the download from a different peer before it had to stop.

I just saw this on the following video: https://diode.zone/videos/watch/f78c6792-d6be-4bcb-9886-ca589ca5f4f8

![Screen Shot 2019-08-30 at 7 19 30 PM](https://user-images.githubusercontent.com/923812/64058141-78c2b700-cb5b-11e9-8639-44f0fa68a228.png)

**Comment by scanlime** [comment]
Here's tube.linc.systems again being really slow, especially compared to diode.zone from the same network... I might have to clear the redundancy table again, just to prevent video performance from degrading until this works better.

![Screen Shot 2019-08-30 at 7 24 09 PM](https://user-images.githubusercontent.com/923812/64058161-d0f9b900-cb5b-11e9-94a8-65f646c03289.png)

**Comment by McFlat** [comment]
I have been having issues with the player playing without stop, any video, first time watching it gets stuck always and only way to get it to play the rest of the video is to refresh the page. All browsers I've tried it stops playing like 15 or 25% into the video and never continues, have to refresh for it to continue playing, from mobile and from laptop browsers. I have a 500Mbit up/down fiber connection, so it shouldn't be a network bandwidth issue, it's some kind of bug. How easy would it be to create a plugin that would use MediaElement.js as the video player instead? is it even possible to switch out the media player since it uses peer-to-peer web-torrents for the videos? Maybe I should report this as a new bug.

**Comment by Chocobozzz** [comment]
FYI you can now disable remote redundancy: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L137

**Comment by scanlime** [comment]
FYI this issue is still a big problem for my instance

**Comment by c0xc** [comment]
This does not appear to be considered a bug, so may I ask:
If the player isn't temporarily excluding overloaded instances, then what's the point of adding mirror instances, how should that help to scale up? Suppose someone is paying for 9 additional mirror instances so that all videos are available from 10 instances and each of the 9 out of those 10 instances is already serving as many viewers as possible with its given traffic and bandwidth limitations but the 10th instance would still be able to handle a few hundred viewers - now, any new viewer would have a 90% risk of choosing one of the overloaded mirrors, causing playback to stop and causing the user to leave the site thinking that it's broken.

However, what I would expect from having mirror instances is that they prevent playback issues as long as the combined bandwidth of all instances is enough to serve all simultaneous viewers. Also, this is one of the core features that make Peertube unique so I don't get how disabling it completely would be beneficial for the viewers experiencing playback issues.

Is the concept of mirror instances unfinished, is my understanding of it incorrect or what is it supposed to do for you?

**Comment by Chocobozzz** [comment]
The redundancy feature and its documentation is pretty clear:

> If your instance duplicates a video, web browser **will randomly download segments** of this video on the origin instance and on your instance, relieving origin instance bandwidth

So it's not a load balancing system, dispatching intelligently requests between servers. If it does not fit your use case or slows down video streaming, disable it.

I created [an issue](https://github.com/Novage/p2p-media-loader/issues/92) on the dependency we use. But until now, we did not have time to work on it.

**Comment by c0xc** [comment]
Thanks for your answer.

> If it does not fit your use case or slows down video streaming, disable it.
The use case would be: Allow more users to watch videos at the same time than can be served by a single instance on a single server.

Obviously, the goal is to prevent playback issues caused by an overloaded server, in other words: If a single server can handle 200 connections and a mirror with the same bandwidth is added, I'd expect 400 connections to be possible. Disabling it won't increase that number. If the first server can handle 200 connections and the second one can has enough bandwidth for 2000, then up to 2200 users should be able to watch videos and the same goes the other way around: If the first server can handle 2000 connections and you add one or more slow mirrors that each handle 200, those should not reduce but increase the number of users who can watch without the player getting stuck. Does anyone here in the bug report have a different use case?

Now, I get that having both slow and fast servers isn't taken into account when the sources are selected randomly, so when the slow server is at its limits, it will still be queried as often as the fast server, unless overloaded servers are temporarily removed or ignored. Such a mechanism might be even more useful with many followers as the admin doesn't have any control over their infrastructure.
(I have to admit that reading the documentation, it wasn't immediately clear to me that this means all mirrors should have the same bandwidth.)

Since there does not seem to be any progress in the bug issue of the player, how about an alternative approach? Sites that use a cdn usually don't have a player that knows how to load from different sources, it selects one depending on their availability and region and then it keeps using it. Do you think a similar approach might work in Peertube, to allow for more viewers while also reducing playback issues? For example, the server could keep track of active viewers and it could make the source selection for the player, user 1 gets mirror 1, user 2 mirror 2, user 3 mirror 3, user 4 mirror 1... But I think as an experimental feature, it should be an optional alternative to the selection in the player that we have now.

**Comment by scanlime** [comment]
For what it's worth, people on the terrible orange website are hitting this bug now and complaining that peertube "is slow" as a result. These people are annoying but the problem with performance in the presence of redundancies does pose a pretty frustrating initial experience for some folks.

**Comment by fflorent** [comment]
I disabled redundancy and had to delete in DB a host which didn't respond (any request hang).

My instance is in version 4.2.2.

**Comment by Chocobozzz** [comment]
@fflorent Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a77c5ff3622ab75d0c22241d0ef72053deaa7926
