### ISSUE TITLE
Potential bug in peertube-socket.ts

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2065]
I'm reading peertube's code to learn how it works. I came across this line:
https://github.com/Chocobozzz/PeerTube/blob/0ad45af705cb3870642f7b147334100112e19e46/server/lib/peertube-socket.ts#L36

Does it mean that a given user can only have one socket for notifications? If I open multiple tabs in my browser, only one will receive notifications?

**Comment by realityfabric** [comment]
That appears to be correct based on a test I just did. I performed the action which resulted in the notification, so I'm not sure what happens when other people subscribe/comment/etc, but I subscribed to one of my own channels and received a notification in only one tab.

**Steps to Reproduce:**
1. Log in
2. Open multiple tabs of PeerTube for your instance
3. Subscribe with your own account to one of your channels.
4. Check all of your open PeerTube tabs for the notification icon. There may be a delay.

* **Browser:** Chrome 76.0
* **Version:** v1.4.0-rc.1

**Comment by Chocobozzz** [comment]
Nice catch @JohnXLivingston! It's fixed by https://github.com/Chocobozzz/PeerTube/commit/015d9dec91ecb7a17e4e79407d187aac8a19206d

**Comment by JohnXLivingston** [comment]
In your fix:
https://github.com/Chocobozzz/PeerTube/blob/1b42d73f44811eec1b7ddd72dd0d640a57c3376c/server/lib/peertube-socket.ts#L43
You should do the "notification.toFormattedJSON()" outside the for loop.

**Comment by Chocobozzz** [comment]
@JohnXLivingston don't hesitate to make a PR

**Comment by JohnXLivingston** [comment]
Yes, but I'm not home for now. I'll make it this weekend if you don't.

**Comment by JohnXLivingston** [comment]
Done.
