### ISSUE TITLE
Tracker not working

### ISSUE THREAD

**Issue by saambd** [Chocobozzz/PeerTube#219]
Please check the image link http://prntscr.com/i2b28u
WSS I think not working or utorrent or any other torrent.

**Comment by Chocobozzz** [comment]
This should be fixed with new torrents: https://github.com/Chocobozzz/PeerTube/commit/0edf0581a92a2c0b5423d3947934d0f36bda1592

Just keep in mind that you need a torrent client that support the [WebSeed](http://www.bittorrent.org/beps/bep_0019.html) BEP (I don't remember if utorrent does, but I know transmission supports it).
