### ISSUE TITLE
Add ability to comment videos without accounts

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2228]
A user of my instance requested the ability to submit comments without account (of any sort). Indeed, users may just want to react to some videos just once (in my case, because they were interviewed and asked questions). 

However, that's maybe questionable. I am not sure how to balance this with moderation?

Feedback welcome on this use case :)

**Comment by JohnXLivingston** [comment]
They can use a mastodon account to comment. A non-connected user will be prompt for a mastodon or plemora account when he tries to comment.

Tips: on your mastodon account, you can follow an entire peertube instance by searching @peertube@yourinstance.com

**Comment by fflorent** [comment]
@JohnXLivingston Thanks for your answer. I know that pretty well, but that doesn't answer the use case. They don't want to create an account *of any sort*.

> Indeed, users may just want to react to some videos just once (in my case, because they were interviewed and asked questions).

**Comment by JohnXLivingston** [comment]
oh sorry, I read too fast

**Comment by fflorent** [comment]
No worry :)

**Comment by puppycodes** [comment]
+1

**Comment by DontUseGithub** [comment]
Could be part of the _umbrella of anonymous features_
https://github.com/Chocobozzz/PeerTube/issues/2279#issuecomment-558516241

**Comment by Chocobozzz** [comment]
I would be an interesting feature, but impossible to moderate. And we already have enough spam issues in PeerTube for now :/

**Comment by fflorent** [comment]
I totally understand, thanks for your feedback :)

**Comment by DontUseGithub** [comment]
> I would be an interesting feature, but impossible to moderate. And we already have enough spam issues in PeerTube for now :/

If it'll be disabled by default, only the admins that have the resources and desire to moderate will deliberately enable it.

**Comment by DontUseGithub** [comment]
> I would be an interesting feature, but impossible to moderate. And we already have enough spam issues in PeerTube for now :/

If it'll be disabled by default, only the admins that have the resources and desire to moderate will deliberately enable it. 

Additionally we can add an option of blocking certain IPs to help them moderate the comments and another option to limit the comment rate of anonymous comments. So for example, a server admin can set a limit of 1 comment per 6 hours for each video or for all videos collectively.

_I personally don't think it's a good idea to judge ideas/suggestions/issue based on the current situation. Because tomorrow the situation might change, more admins may start to better moderate their instances and the spam may go down a lot and then what should we do, re-open this issue? 
I think playing with default options is enough to control these kind of things, most admins use the default configuration anyways. But for those who have enough moderators/time, this feature may come in handy._

**Comment by rasos** [comment]
Great to see that there is now a live stream plug-in https://joinpeertube.org/news#live-plugin-app - very useful for events e.g. when streaming from a Jitsi servver via Jibri.
