### ISSUE TITLE
Trending page lacks interesting content. Let's slightly change the algorithm

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2270]
Because of the current algorithm, the Trending page contains old content that we've already seen the thumbnails of, and thus the Trending page becomes uninteresting.

I'd suggest changing the algorithm, to make it simple, just to show the videos that have the most views from the last 7 days (or 3 days?).

If you can think of a better algorithm, please suggest it here.

**Comment by WonderingDane** [comment]
Let the instance choose how many days, categories and language.

**Comment by DontUseGithub** [comment]
> Let the instance choose how many days, categories and language.

Sure, the PeerTube devs just have to pick a default value.

**Comment by DontUseGithub** [comment]
@rigelk can we please add the "good first issue" label to this issue? I feel like this is one of those issues that are easy to fix, that in return offer a great usability improvement.

**Comment by rigelk** [comment]
@DontUseGithub I wouldn't call adding an API parameter a "good first issue", as this needs at least some knowledge of how the project is structured to know where to add it, how to test it, how to query the db, how to modify an Angular component to change the filter, etc. I usually assign "good first issue" labels by judging if a 2nd year CS student could solve it, and this isn't one of those.

**Comment by 3risian** [comment]
I suspect that trending videos may be experiencing a small positive feedback loop: videos on the front page are probably more likely to get viewed, therefore they stay on the front page. This is just a hypothesis though.

I wonder if an algorithm such as `view count for the current period, divided by total view count` might help raise fresher content rather than 'always popular' content.

Motivating case: peertube.co.uk (follows around 400 instances) shows:
11/24 videos were made this week
10/24 videos made over 8 months ago and have been in the trending list for a long time

**Comment by Chocobozzz** [comment]
I guess we could have an admin setting to filter trending videos (for example only display videos published last month etc)

**Comment by DontUseGithub** [comment]
> I suspect that trending videos may be experiencing a small positive feedback loop: videos on the front page are probably more likely to get viewed, therefore they stay on the front page. This is just a hypothesis though.

You're totally right, the "What is PeerTube" video is trending on most servers since the video was uploaded on PeerTube.

Same with the Most Liked page, the top videos stay the same, so no one is interested in visiting it. https://github.com/Chocobozzz/PeerTube/issues/2369

@Chocobozzz but aren't we complicating it too much? What will happen when an admin will want to change that to 6 days? He'll have to change two things: 
`display videos published last 6 days` and `trendingDays === 6` (or less)

**Comment by HuGo-Y** [comment]
> You're totally right, the "What is PeerTube" video is trending on most servers since the video was uploaded on PeerTube.

The "What is PeerTube" video is still trending, everywhere. :laughing: 

Could we please give this issue some more importance? :) Thanks a lot and sorry for upping this issue.

**Comment by Chocobozzz** [comment]
Closing now we have additional trending algorithms (hot, best, trending)
