### ISSUE TITLE
Thumbnails show visible compression

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2280]
# What happened?
I was fed up with YouTube, looked at other alternatives and found PeerTube. After brosing some instances I noticed visible compression artifacts on (almost excusively) thumbnails with text. **This is especially visible on TN with white text and a black background.**
___
![pic-selected-191123-2204-49](https://user-images.githubusercontent.com/58121201/69485270-56c89000-0e3d-11ea-8c6f-a31ec5cf2b71.png)
*Zoom: 170%*
# What do you expect to happen instead?
I'd love to see sharp text on the thumbnails by default. 
___
![pic-selected-191123-2202-53](https://user-images.githubusercontent.com/58121201/69485241-0f420400-0e3d-11ea-9a40-33491798f4b5.png)
*This does not apply to the blender instance (guess they changed that).* 
*Zoom: 170%*

# Steps to reproduce:

1.  go to: [peertube.social](https://peertube.social/) or other instances
2. compare with: [video.blender.org](https://video.blender.org/)

**Comment by Chocobozzz** [comment]
Thumbnails have to be small because they are federated. The image you see on the blender instance is bugged and too large (https://video.blender.org/static/thumbnails/176ab5bc-e64f-440f-9da9-52d65a02bc33.jpg) because they use an old peertube version.

I'm not sure we can do anything here: jpeg is jpeg so texts will always be like that...

**Comment by martnnw** [comment]
**Wouldn't gif be better?**
After a simple conversion - to 183x122 just about the thumbnail size of the peertube.social instance - the gif image is about twice as large in size as the jpg but depending on the image it can be reduced a bit.

also:
- It works better with small images
- the artifacts look much more pleasing
- colors (pop/) look better

**Judge for yourself:**

**GIF** | **JPG**
:---: | :---:
![test](https://user-images.githubusercontent.com/58121201/69880046-46933380-12c9-11ea-868e-5c4b6f15061a.gif) | ![test](https://user-images.githubusercontent.com/58121201/69880124-73dfe180-12c9-11ea-89ca-8b97843d2cca.jpg)
18.0kB / 183 x 122 | 7.6kB / 183 x 122
![YT](https://user-images.githubusercontent.com/58121201/69882824-d046ff00-12d1-11ea-95d6-d3e5b529dac6.gif) | ![yt](https://user-images.githubusercontent.com/58121201/69882905-2156f300-12d2-11ea-99e6-a2517ed24a9a.jpg)
4.6kB / 217x122  | 3.7kB / 217x122

**Comment by aschaap** [comment]
I would argue against GIF due to being limited to 256 colours (per animation frame); even with dithering, it's still not great. Furthermore, the cases where GIF equivalents of PNGs are smaller are likely sufficiently rare that including this format is not going to be worth it. Formats such as WebP would likely reduce that likelihood further still.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1953
