### ISSUE TITLE
Notifications from muted instance still appearing

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#2345]
I'm running v2. Comments from muted instances are being hidden, but a notification is still sent out for the invisible comment.

**Comment by Fidgetcetera** [comment]
I'm the person receiving notifications. This is what it looks like on my end:
![screenshot of a user named catharsis commenting on a video](https://user-images.githubusercontent.com/15249812/71133971-86638180-21ca-11ea-9f49-a0e3e44221bb.png)
![screenshot of the video with no comments, because catharsis' server is muted.](https://user-images.githubusercontent.com/15249812/71133974-8794ae80-21ca-11ea-8f11-846308dacb02.png)

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/dddc8b1fe0c875f41c88f395b0d55cfea69add2c
