### ISSUE TITLE
[Suggestion] Streaming is decentralized, hosting is not. Proposed solution

### ISSUE THREAD

**Issue by gustavklopp** [Chocobozzz/PeerTube#2363]
There's still a single point of failure of failure if the server where the video is hosted is erased.
The level of centralization is increased by the need to create yourself a server and then host a PeerTube instance. A lot of people won't be able to do that which diminishes the number of possible servers.

Thanks to PeerTube, we can achieve decentralization in terms of streaming when you play the video. This decreases the load on each invididual PeerTube instance.
But still the centralization of hosting represents a problem.

I proposes a technical solution:
When streaming a video from a server, the client is actually downloading part of the video, saving it on his hard drive. So, each client must dedicate for example 10Gb of their HD space for downloaded video parts. The client downloads only a fraction of the video: the more viewer of the video, the less fraction of the video is kept on one client HD. 
For example, if the client is the only one to have viewed a video, 1/1 = 100% of the video is saved on his side. If there are 1 other client, so 2 viewers in total, 1/2 = 50% for each client.
This space is dynamically managed and the more viewers, the less fraction of the video is saved for each client. 
This space never exceeds the quota, for example 10Gb: so when it approaches this, an algorithm determines which video must be deleted (for example newest videos with a lot of viewers).

That's way we could achieve decentralization of video hosting: if a server goes down, we can hope that it was saved in parts in different clients. Thanks to saving in parts, the HD space is not bloated by downloaded videos that the clients could see. 

I still need the time to implement this but at first I'd like to have the opinion of the community on this.

**Comment by Findus23** [comment]
I think this is related to https://github.com/Chocobozzz/PeerTube/issues/2115 where I mentioned in https://github.com/Chocobozzz/PeerTube/issues/2115#issuecomment-533602828 why I think this might be hard to do.

The main issue is that browsers can't arbitrarily store multiple gigabytes of data and distribute them further just because a website (in this case peertube) tells them to do. That would be a huge security issue and would upset a ton of users (who are on metered internet connections). One could argue that instead of a browser these users could use special clients, but at that point one could argue that these special clients should be put on computers with fast upload speeds and one has recreated the existing peertube redundancy feature.

>  For example, if the client is the only one to have viewed a video, 1/1 = 100% of the video is saved on his side. If there are 1 other client, so 2 viewers in total, 1/2 = 50% for each client.

Splitting up like this increases the chance of failure instead of decreasing it, because now only one person going offline (or deleting their cache as they need the disk space) will result in the video not being complete any more. 

More decentralization is definitely a great goal, but I don't think depending on people's private internet connection (with low upload speeds) is the way to go.

**Comment by JohnXLivingston** [comment]
You forgot that there must be a torrent tracker. If the server hosting the video goes down, the tracker too. 

There are already redundancy policies in peertube which allows to share the load. 

And I'm not sure to understand your point. When you say «The level of centralization is increased by the need to create yourself a server and then host a PeerTube instance». Not at all. You don't have to create yourself a server.

**Comment by rigelk** [comment]
Since this is a duplicate of #2115, I invite you to contribute to the discussion there.
