### ISSUE TITLE
add dropdown button (icon) for the Trending page with more than one options

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2368]
This would allow the user to choose from different time-frames, such as:

- for the last month
- for the last 6 months
- for the last year
- custom value

Demo screenshots with the RSS icon on the right:
![111](https://user-images.githubusercontent.com/57924087/71583325-9eb29500-2b16-11ea-9681-fc302096a307.png)

And with RSS icon on the left:
![1112](https://user-images.githubusercontent.com/57924087/71583327-9fe3c200-2b16-11ea-8fdd-d9ed39da2fac.png)

Same images but with the black color:
![2221](https://user-images.githubusercontent.com/57924087/71583432-154f9280-2b17-11ea-9481-9cd6a9a76d65.png)
![222](https://user-images.githubusercontent.com/57924087/71583437-184a8300-2b17-11ea-9dd0-3d5701271f28.png)

IMO the 4th screenshot looks great.

**Comment by rigelk** [comment]
Why remove the word "Trending" from the text? I'd be more curious of a mockup of the dropdown, since choosing flexible time frames will be a challenge in a dropdown.

On a side note, there are a few implications with the addition of multiple time frames. The current main video pages are optimized and cached. Also, instance administrators can choose to default to one as their home page. All of this is fine for predefined time frames. Flexible time frames on the other hand will not be cached and likely yield a worse performance as a result, so they shouldn't be choosable as default home pages.

**Comment by DontUseGithub** [comment]
> Why remove the word "Trending" from the text?

It may also look good with the word "Trending" there, IDK I haven't tested. The mockup doesn't have it because I thought it's redundant because in the sidebar the word "Trending" is highlighted so it's easy for them to know on which page they are.

> I'd be more curious of a mockup of the dropdown

We could have it similar to how reddit has them
![1112](https://user-images.githubusercontent.com/57924087/71618406-155b9b00-2bc8-11ea-8b73-4e4d82c64e6e.png)

> On a side note, there are a few implications with the addition of multiple time frames. The current main video pages are optimized and cached. Also, instance administrators can choose to default to one as their home page. All of this is fine for predefined time frames. Flexible time frames on the other hand will not be cached and likely yield a worse performance as a result, so they shouldn't be choosable as default home pages.

I have two thoughts on this:

1. that's fine because there will be a default value which will be cached, in our case that's 7 days. So the page will load just like before, even if chosen as the default homepage. If the user will want to choose a different time-frame, then he'll just have to wait a little - no big deal I guess.
2. Offer fixed values beside "7 days" and cache them all. This would mean that we need to remove the last option "custom value". So if we decide to have 4 options in total:
7 days
a month
6 months
1 year
then we'd need to cache all of these only.

**Comment by Chocobozzz** [comment]
Closing now we have different trending algorithms.
