### ISSUE TITLE
Option to set default subtitle?

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#2379]
Hi,

it would be great to select an uploaded subtitle file as activated on default (similiar to the option that sets a subtitle for a share link).

Thx for PeerTube!

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3685

**Comment by Findus23** [comment]
I feel like either I am missing something or this feature got lost. I would like to change Peertube so that subtitles are enabled by default for visitors. 
This has been merged into #3685, but that has been closed as completed (but only supporting adding a `?subtitle` parameter to the shared/embedded URL).

**Comment by Chocobozzz** [comment]
Yes you're right. We implemented setting subtitle using the URL, but not forcing a subtitle in the video settings. I'll reopen the other issue.
