### ISSUE TITLE
Multiple semi-invalid predicates in `Video` object

### ISSUE THREAD

**Issue by puckipedia** [Chocobozzz/PeerTube#240]
The `shares`,`likes`, `dislikes`, and `comments` collection should have their own ID, as officially all objects should have dereferencable IDs. Also, maybe instead of `nsfw` you could use `sensitive`, for support with existing systems.

Also, the collections are missing inside the `object` of an `Announce`.

**Comment by Chocobozzz** [comment]
* Sensitive: https://github.com/Chocobozzz/PeerTube/commit/0a67e28beeaf603110d52df3eda400e60531b3a4
 * Ids: https://github.com/Chocobozzz/PeerTube/commit/46531a0abdd5c860a1a8cdb4b636b9c55bfb115b
 * Missing collections inside video objects should have been fixed with this issue: https://github.com/Chocobozzz/PeerTube/issues/239

Thanks @puckipedia.

**Comment by puckipedia** [comment]
Awesome, thanks! This should help federation with Kroeg and Mastodon a lot :)

**Comment by Chocobozzz** [comment]
I hope so! If you see other issues do not hesitate :)
