### ISSUE TITLE
"PeerTube Firefly" - p2p video hosting and streaming (optional feature)

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2410]
![cc0-photo png](https://user-images.githubusercontent.com/57924087/72361980-07933300-36fb-11ea-9571-adaeef324f84.png)

A firefly becomes visible only during twilight, just like people will be able to watch videos through this feature only when other users "will become visible" a.k.a seed. 

I think it's important to give this feature a name (it can be a different one) because some people due to lack of knowledge will probably misunderstand it and they'll want to blame "PeerTube", but if we give this feature a separate name, they'll know that this is just a small feature that doesn't represent the whole PeerTube software.

**If it sounds so bad, why should we implement it?** 
It may sound bad but there are ways to reduce its downsides (like displaying a warning) and well, it has its own big advantages (like no need for big server storage) and there are other big platforms which do only that (e.g. bitchute) and people really seem to need this.

**So what is this about?**
This feature is about giving people the possibility to upload torrent files (which are a few kilobytes in size) and thus create "Firefly videos" which people can watch as normal videos (if at least 1 person is seeding it).

Other methods to reduce its downsides:
- as I wrote above, display a warning that'll say that _this isn't a normal PeerTube video, but rather a Firefly video which works like this... and does this... and that..._. And guide them on how to hide all Firefly videos if they aren't interested in them.
- temporarily hide Firefly videos (from search results, recommended, Trending pages etc..) that have (zero) 0 seeds so that people don't even waste their time clicking on them

_Similar issue https://github.com/Chocobozzz/PeerTube/issues/1524, but it was a question and rather incomplete. So I've decided to create this one._

**Comment by rigelk** [comment]
There are some technical difficulties with that kind of functionality:
- videos need to be transcoded at some point to ensure they are compatible with all devices (ensure they have the right format, codec, etc.) and have varied bitrates to fit the tubes. That means storing them in the end, too.
- to provide thumbnails, previews, and other metadata like the length of the video, the file has to be downloaded by the server first for analysis.

There is a third point, but it can *non-trivially* be solved by forcing clients to use the instance WebTorrent tracker which would count peers :
- checking if at least one peer exists in the pool requires PeerTube to become a BitTorrent client. This is not the current approach PeerTube has, which is to be first and foremost a web service. Mind you, we already allow importing files from BitTorrent, but that is a *punctual* use that doesn't affect performance long term. Watching for peers for each of the Fireflies would affect performance at scale.

Sorry if that sounds negative, but I prefer to start with the technical overview so that we are on the same page.

---

*side note*: I had already checked BitChute. Their model has been put into question for some time now: https://www.dailydot.com/layer8/bitchute-decentralization-claims/

**Comment by tilllt** [comment]
I had to read the post several times to understand the proposal. but i am not sure i did. Is the idea is to have a "storageless" (or minimal storage) server?

**Comment by DontUseGithub** [comment]
@tilllt 
> Is the idea is to have a "storageless" server?

Yes, people will only upload torrent files (which are a few kilobytes in size) instead of entire videos (an average 1 min 4k video has around 400MB). And when playing such a video (Firefly video), the PeerTube server will only act as a bridge between the viewer and other seeds and peers, connecting them all together.

@rigelk 

> Sorry if that sounds negative, but I prefer to start with the technical overview so that we are on the same page.

That's fine, I totally understand this. Thanks for showing interest for this suggestion :)

> - videos need to be transcoded at some point to ensure they are compatible with all devices (ensure they have the right format, codec, etc.) and have varied bitrates to fit the tubes. That means storing them in the end, too. 
> - to provide thumbnails, previews, and other metadata like the length of the video, the file has to be downloaded by the server first for analysis.

What if we let the user first upload the original video, then the server will do all the transcoding, generate as many .torrent files as it needs (for each format, etc), analyze metadata, etc and then delete it?

Regarding the third point I have nothing to say (because I'm not that technically knowledgeable) except for: Let's accept the drawbacks and add this as a warning for the server admins that would like to enable PeerTube Firefly. At least until we find a better solution.

> https://www.dailydot.com/layer8/bitchute-decentralization-claims/

Yes, Bitchute isn't decentralized, but can PeerTube's Firefly videos be federated?

**Comment by tilllt** [comment]
Wouldnt it be more logical if the local user fired up a peertube instance (i.e. in a docker or VM), federates with the server it wants the video to show, and just hosts a temporary instance?

**Comment by DontUseGithub** [comment]
Firefly videos aren't "disposable", they get hidden only when all seeds are offline, the moment at least 1 seed is online, the video becomes visible.

**Comment by rigelk** [comment]
> The moment at least 1 seed is online, the video becomes visible (available) to everyone, hence the name - firefly.

Another problem, not inherent to you suggested feature but that impacts it, lies in the fact that most long-term seeding clients are legacy BitTorrent clients that don't support WebTorrent. That greatly reduces the capacity of a visitor to help seed the video without being very knowledgeable.

**Comment by DontUseGithub** [comment]
Good point. We can tho 'fix' this by recommending people to use a BitTorrent client that supports WebTorrents, such as:

- WebTorrent Desktop - Open source streaming torrent client. For Mac, Windows, and Linux.
- Vuze - Powerful, full-featured torrent client
- Playback - Open source JavaScript video player (super cool!)
- webtorrent-hybrid - Node.js package (command line and API)
- Instant.io - Simple WebTorrent client in a website
- βTorrent - Fully-featured browser WebTorrent client (source code)
- TorrentMedia - Desktop WebTorrent client

https://webtorrent.io/faq

And I suspect that in time this will be a non issue as popular bittorrent clients will start adding features, including support for WebTorrents.

**Comment by Chocobozzz** [comment]
Hello,

Closing this interesting discussion, that is out of the scope of PeerTube
