### ISSUE TITLE
Upload video from youtube is not working

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#2437]
**What happened?**

Upload video from youtube is not working. 

**What do you expect to happen instead?**

**Steps to reproduce:**

1. Try upload video from instance

**Additional information**
* PeerTube version or URL: v2.0.0
* Browser name/version: Firefox 65
* NodeJS version: 10.18.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):https://pastebin.com/raw/0hL8XpVB

**Comment by Findus23** [comment]
Youtube recently changed something which broke Newpipe and apperantly also youtube-dl.
(https://github.com/ytdl-org/youtube-dl/issues/23819)

It is already fixed in the latest version (2020.01.24) and I think peertube automatically updates youtube-dl regularily, so you just need to wait for the update and everything fixes itself.

**Comment by Chocobozzz** [comment]
Do it work now?
