### ISSUE TITLE
Upload image(s) to have them transformed into a GIF

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2463]
**Suggestion:**
Add the possibility of uploading images and for PeerTube to automatically transform them into a GIF.

**How will it work:**

- a user uploads one or multiple images
- he chooses for how long a frame (image) should be shown before showing the next one (e.g. 2 seconds each)
- done

**How will it work for the viewer:**

- UI/UX-wise it should look and feel like a regular video, except that somewhere it should say that this is a GIF (maybe add a [small icon](https://www.flaticon.com/free-icon/gif_2305974) somewhere)

**Comment by 3risian** [comment]
Is there a reason this should be part of PeerTube, as opposed to someone just using a dedicated GIF/video-maker program? I think you can even find websites that do this, so a mobile user could use them.

Also, was there a specific reason for using GIF? I guess that you mean that to say a small animation, rather than necessarily a GIF; GIF is an image format from before the 90s which is quickly being replaced by WebM video (far higher quality, smaller filesize). There is almost no motivation to use them on a video site, apart from possibly converting them to videos as an upload feature.

**Comment by Chocobozzz** [comment]
It's out of the scope of PeerTube. We are not a video maker software, and doing a video streaming platform is enough work ;)
