### ISSUE TITLE
How can a user opt-out of webtorrents on a browser-level (Firefox)?

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2468]
Setting this **media.peerconnection.enabled** to false in about:config didn't do the trick, the video player was showing me the number of peers it has connected me to. Thank you.

**Comment by 3risian** [comment]
This is an issue with Firefox, not PeerTube.

I found [this bug track](https://bugzilla.mozilla.org/show_bug.cgi?id=1314443) on Mozilla's site, it appears to be the most recent.

>To prevent media device enumeration, however, I had to set *both* "media.peerconnection.enabled" and "media.navigator.enabled" to false. Setting only "media.navigator.enabled" to false was *not* enough to prevent media device enumeration.

(I am not sure how complete of a solution that is, but it's worth testing.)

I am interested in this issue, so please post a reply if you find more information. However it may get marked as closed because you are discussing a browser problem, not a PeerTube problem.

**Comment by DontUseGithub** [comment]
> I am interested in this issue, so please post a reply if you find more information.

I've tested this, I've turned both of **media.peerconnection.enabled** and **media.navigator.enabled** off but PeerTube still shows the number of peers. Visiting one of those websites that checks if webrtc is enabled/disabled says that webrtc is indeed disabled.

**Comment by Chocobozzz** [comment]
The number of peers includes webseeds.

You can also blocks requests to the `/tracker/*` endpoints

**Comment by 3risian** [comment]
I disabled both **media.peerconnection.enabled** and **media.navigator.enabled**, restarted Firefox and opened a video on the peertube.cpy.re instance, and it still received a heap of .mp4 content from peertube.live (monitored through the Firefox Network Monitor, Ctrl+Shift+E in the browser).
