### ISSUE TITLE
Channel view

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#247]
So let me explain...
as of now there are two options right?
- Trending
- Recently added

well can we add one more for channel name and only videos uploaded in that channel to show up?
why? because sometimes for example people may have a podcast/show etc and on their fliers or links does not want to link to the front page with all the videos from all connected peertube nodes.. as of now is.

thanks! love this.

---

WIP: see [below](#issuecomment-360550746).

**Comment by DimitriGilbert** [comment]
Maybe it could also be a good thing to have a way to search channel and browse them ?
@Chocobozzz I can start working on that if you'd like (or at least specifying what i'd do so you can validate :) )

**Comment by Chocobozzz** [comment]
Sure!

**Comment by DimitriGilbert** [comment]
**For channel listing and view :**
- [ ] create a video-channel model
- [ ] create a video-channel service
- [ ] create an abstract-channel-list (just like for videos, it might come handy later on I think)
- [ ] create a video-channel-miniature component that :
  - displays the avatar of the channel
  - displays the number of videos on the channel (if so we'd have to add a videoCount on the video-channel model not to have to load all channels' videos' details in the channels list, I did not dig deep enough to know how to do that just yet ^^ )
- [ ] create a video-channel module
- [ ] create a route to access the module
- [ ] create a video-channel component that contains :
  - infos about the channel
  - the listing of the channel videos ( by creating a new video-list component which would be video-channel-[something])

If this seems acceptable, I have a few questions :
- should we list channels without videos
- what should the list be sorted on (I suggest by name, number of videos and maybe last activity)


**For channel search :**
I'm not fully sure how to do because questions.
- Should we have a single search both for videos and channel (that would break the current search)
- if no, shall it be placed on top of the channel list component ?
- if yes, hmmm, I am unsure how to do that...

That could obviously come at a later point

**Comment by Chocobozzz** [comment]
Don't do the search for now, we need to design it and I don't really know how.

You'll need 2 root components:
 * User page (Same design than "My account page") with two sub titles (with user information on the top):
   * Videos (classic videos list)
   * Channels (what you said in **channel listing and view**)
 * Channel page that contains:
   * Channel informations on the top
   * Videos (classic videos list)

For the lists just sort by `-createdAt` to begin :)

**Comment by Chocobozzz** [comment]
@DimitriGilbert do you work on this?

**Comment by DimitriGilbert** [comment]
I was unavailable the last 2 weeks but I'm back at it, expect PR  before end of next week.
If you want to have a look give a look at progress [https://github.com/DimitriGilbert/PeerTube/tree/issue-247](https://github.com/DimitriGilbert/PeerTube/tree/issue-247)

**Comment by DimitriGilbert** [comment]
I was unavailable the last 2 weeks but I'm back at it, expect PR  before end of next week.
If you want to have a look give a look at progress [https://github.com/DimitriGilbert/PeerTube/tree/issue-247](https://github.com/DimitriGilbert/PeerTube/tree/issue-247)

**Comment by rigelk** [comment]
@DimitriGilbert any update on this?

**Comment by BrainBlasted** [comment]
I too am curious, @DimitriGilbert

**Comment by Chocobozzz** [comment]
Taking this, with the account view.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/170726f523ff48f89da45473fc53ca54784f43dd

**Comment by rhaamo** [comment]
Is it planned to have the ability to create more channels per user ?

**Comment by Chocobozzz** [comment]
Of course, it's the next step :) https://github.com/Chocobozzz/PeerTube/issues/109
