### ISSUE TITLE
Ability to select timecode of a video to import

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#2471]
Improvement proposal: ability to select timecode of video to import.

When you import a video from another website, Peertube import all the stream. But it is possible that only a part of this video has an interest.
For example, https://video.lqdn.fr/videos/watch/b6544b93-1ff7-4bb8-a0a5-dceab779915a comes from the french Assemblée Nationale, and start only from minute 19. I would like to be able to say at importation to skip this 19 first minutes (and potentially the last xx minutes).

**Comment by klorydryk** [comment]
I'm sorry, but I don't understand how https://github.com/Chocobozzz/PeerTube/pull/2473 will answer this need 😬 (as I couldn't find any option in youtube-dl which offers to select start/end video time to download).

**Comment by drzraf** [comment]
Indeed. Actually the problem is that `youtube-dl` itself does not support this feature.

**Comment by klorydryk** [comment]
Ok. As it is a [7 years old requested feature](https://github.com/ytdl-org/youtube-dl/issues/622) in youtube-dl, shouldn't we provide an internal tool to do it as [proposed here](https://github.com/ytdl-org/youtube-dl/issues/622#issuecomment-162337869):

>  ffmpeg -ss 14350 -i $(youtube-dl -f 22 --get-url https://www.youtube.com/watch?v=mMZriSvaVP8) -t 11200 -c:v copy -c:a copy react-spot.mp4

**Comment by Chocobozzz** [comment]
Hi @klorydryk 

I'm sorry but this issue is out of the scope of peertube. Some solutions:
 * Wait for youtube-dl implementation and use our import script to inject appropriate options to the youtube-dl binary
 * Create a small wrapper to download a video using youtube-dl, cut it using ffmpeg and upload it on peertube
 * Use peertube import, download the video, cut it and replace existing file using https://docs.joinpeertube.org/maintain-tools?id=create-import-video-file-jobjs
