### ISSUE TITLE
Enable user registration

### ISSUE THREAD

**Issue by faddat** [Chocobozzz/PeerTube#25]
How can I enable new user registrations?  or is that not something that can happen just yet?  Is there a way to "drop" oauth into this?  

Thanks!

**Comment by Chocobozzz** [comment]
Public user registrations is not implemented yet. For now, only an administrator can create user accounts.

**Comment by faddat** [comment]
K.

Do you have preferences for how we implement this? I know that the
steemit.com community is dying to get logged in.   So you know,  I do go
but in general I do not touch Javascript.  Except today ;).

I think that the back end of peer tube would be more maintainable and
performant in go but I do need to figure a few things out before we can
make that happen.

**Comment by k0nsl** [comment]
Speaking of the administrator account, what is the default login and password? `root` and `test{1,2,3]` does not work. I am using the dockerized version of `PeerTube`.

**Comment by Chocobozzz** [comment]
@k0nsl The password is generated at first startup. You should see it in the PeerTube logs. There will be a script to change the administrator password from the CLI soon.

For the Docker image, it should not work because I did not update it since I switched the database from MongoDB to PostgreSQL. I planned to update the Dockerfile next week.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/2c2e90921646d223060e98d517fc8ac61c90eb9e
