### ISSUE TITLE
Use of a rating system instead of/in conjunction with the NFSW flag

### ISSUE THREAD

**Issue by DimitriGilbert** [Chocobozzz/PeerTube#254]
I think it would be interesting to use a rating system similar to the [MPAA film rating system](https://en.wikipedia.org/wiki/Motion_Picture_Association_of_America_film_rating_system#MPAA_film_ratings) in place of (or with) the NFSW flag to explicitly specify the intended audience of a video.
Obviously this should be the uploader's choice if he wants to rate the content and what rating it should have.

**Comment by Chocobozzz** [comment]
I think this system is too complex and people are generally not able to do the right classification for their content. We need to keep things as simple as possible.

(my two cents)

**Comment by DimitriGilbert** [comment]
for a bit of context, it cam out of a discussion with a friend where we talked about the "adpocalypse" and how it could have been mitigated.
My first reaction was the exact same, and to be clear, I still think it's not ideal. 
But the compelling argument I received back are :

1. that it's fairly simple to do :
    - one field in DB on the video table
    - one place to store the classification (in config for example)
    - one dropdown in the add/edit of a video
    - a simple sign in the front to show it to the user

2. it has to start somewhere and a simple flag is too manichean and can't represent real world


To be more precise, the MPAA classification is way too complicated, but it was for a reference, it could be something like "for all, explicit, adult, pr0n"

**Comment by ghedipunk** [comment]
If it were possible (and I know it's technically possible, just not within PeerTube as it exists now) to have custom thumbnails/preview images, content creators can put specific warnings in there, and "NSFW" could be simply changed to "Sensitive."

There are MANY reasons why you would want to warn a person before they watch a video, giving them an explicit choice to continue, that aren't included in an NSFW tag.

Also, NSFW is frequently interpreted as pornographic, which may make uploaders tend to under-warn for videos that should be warned of anyways, such as violence, gore, etc.

While it's our responsibilities as developers to keep our software from being confusing, it's also up to us to give the users the features that they need to do their job, whether that's as a content creator or as someone consuming content.  

So, my ideal way to address this is:

Change "NSFW" to "Sensitive."

Add a message that lets a content creator let the users know why the video is sensitive.  This could similar to the CW field in Mastodon.  It should be something visible to the viewer before they make the choice to start watching the video, such as where it currently warns about mature/explicit content.

Have customizable preview image.

If we decide to go with a pre-defined rating system, I'd support implementing it as a user- or admin-definable taxonomy system (such as found in Drupal, or similar to Wordpress's tags system).

I've asked for more input on social media, and will update here if/as I get feedback.

**Comment by ghedipunk** [comment]
Feedback I've received so far from someone I'm sys-adminning an installation of PeerTube for is:

She would prefer to have a default, standard site-wide preview image for sensitive content (i.e., if she has federated with my server and I post a sensitive video, her server's preview image would be the one shown).

She is most familiar with custom preview images on a per-video basis from working with YouTube, and would welcome that.

I can see a place for both: A server-based default preview image for sensitive videos that don't have a custom preview image, with the option to show an uploader's custom preview image if one exists.  (Otherwise, if a custom preview image doesn't exist on sensitive content, default back to the server's default preview image. (And yes, I realize many would consider this self evident; I'm just in the habit of writing requirements documents for QA managers to read, who will make a huge stink if I don't specify the non-default default cases explicitly.))

**Comment by benrob0329** [comment]
Perhaps a tagging system for uploaders, such as:
```
This video contains:
[ ] Nudity
[ ] Excessive Violence/Gore
[ ] Swearing
[ ] Provocative Actions
[X] Other: [l33t meemz]
```

Perhaps this could also be extended to a general tagging system to help users find videos they **do** want to see.

**Comment by henke37** [comment]
One could go into insane detail with tagging. There is X and there is _X_, as they say.

And then there is the issue of context. It's one thing to have people being tortured. It is another to watch an expert perform surgery.

**Comment by Nutomic** [comment]
I really like the content warning system in Mastodon. Basically, the author enters a short text that describes the nature of the context. For Peertube, the main question is where to display this description, because the video thumbnail + title doesn't have much space. Maybe only show it in the warning dialog?

**Comment by Chocobozzz** [comment]
Closing this inactive discussion.

See https://github.com/Chocobozzz/PeerTube/issues/1158 for the content warning system.
