### ISSUE TITLE
Add PaleMoon support

### ISSUE THREAD

**Issue by Flashwalker** [Chocobozzz/PeerTube#257]
Please add support for PaleMoon browser.

**Comment by rigelk** [comment]
Since PaleMoon refuses to implement WebRTC (see their [technical info](https://www.palemoon.org/technical.shtml)), it seems unlikely we'll be able to support it.

**Comment by Chocobozzz** [comment]
PeerTube is compatible with non WebRTC web browser (with the help of webseed) but it seems there is an issue after the build of the client with angular-cli (uglify issue?).

**Comment by LienRag** [comment]
I understand why Palemoon consider that WebRTC shouldn't be a core feature of a browser, but coulnd't the feature added by a plug-in (I'm not a dev, I don't know how WebRTC works)?

**Comment by rigelk** [comment]
@LienRag there is no WebRTC plugin for Palemoon, as far as I know.

Then there should be a fallback to direct streaming when WebRTC doesn't work. Maybe we could dig up what prevents this fallback from working in Palemoon instead?

**Comment by Flashwalker** [comment]
Meanwhile here that's what the PaleMoon developer replied to me:
> If they require WebRTC for video playback (why?!) then it will simply never work in Pale Moon. Period.

**Comment by Chocobozzz** [comment]
Lol.

Well, we don't require WebRTC since we have a HTTP fallback. But since PeerTube works on all recent web browser (even on Safari, iOS and Edge) I think it's a Palemoon issue. Feel free to open an issue on their side (if you're not too scared).

**Comment by rigelk** [comment]
At this pace I think we might recommend Palemoon users to access PeerTube over Guacamole to a Linux VM that has Firefox installed :smile:

**Comment by tcitworld** [comment]
Nah, it's good, @Chocobozzz will add [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)) support to Peertube anyway.

**Comment by Symbian9** [comment]
Next development branch of Pale Moon (Pale Moon 28.x) would be migrated to same codebase as Basilisk ~ Firefox 52+

- https://github.com/MoonchildProductions/UXP/releases/tag/PM28.0.0a4_Unstable

**Comment by wolfbeast** [comment]
I've done a little more research and the browser not OK message is thrown up on Pale Moon 27 not because of a WebRTC check, but because we trip up one of Angular's mines in the minefield it is. Of course that's fair -- we know our JS support in Pale Moon 27 is lacking, which is one of the major reasons (if not THE major one) why we've started the UXP effort last year.

WebRTC doesn't even seem to come into the picture at all, though, so I'm not sure what makes you say it's lack of WebRTC support at fault here. Care to enlighten?

**Comment by rigelk** [comment]
@wolfbeast please read [this comment](https://github.com/Chocobozzz/PeerTube/issues/257#issuecomment-384410112): we do have an HTTP fallback when WebRTC is unavailable, and yes, we know about it (hopefully!) :relaxed:

The issue is not about PaleMoon support of WebRTC, but PaleMoon support of… JS so that the HTTP fallback works, as you said. The fact that we talked about WebRTC at length in this issue is just because we wanted to understand why.

**Comment by wolfbeast** [comment]
Right, well, your first response here was:

> Since PaleMoon refuses to implement WebRTC (see their technical info), it seems unlikely we'll be able to support it.

So I assumed it was the only supported technology and peertube explicitly building on that. I skimmed over other comments as they got rather snarky real quick, so didn't see that comment about the fallback ;) Thanks for pointing it out.

In any case, if you keep the http fallback in place, it'll work in v28+ -- if not, then not, of course.

**Comment by rigelk** [comment]
Anyway, happy to know v28 will work with PeerTube. Thanks for the info!

**Comment by rezonant** [comment]
I think the Pale Moon devs misunderstand why PeerTube uses WebRTC (and perhaps the tech as a whole). As a side note, I was also quite saddened to see they do not support accessibility in their main builds since "most users" don't need it, which I'm sure has been the cry of many a shady construction project when their blueprints are audited for ADA compliance. Ah well. I'm off to add Gopher support.
