### ISSUE TITLE
Disable download button for all videos to prevent increased server load?

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2603]
Now, by default, downloading video from the server and directly and the torrent file is enabled **default for all videos**. I believe that this can lead to very large server loads. I turn off downloading for each video - it’s also inconvenient.
How can I completely disable direct video downloading, or downloading in general?

**Comment by rigelk** [comment]
Streaming videos and directly downloading it are both done using the same technique: HTTP download. As for torrents, actually the generated metainfo file has your server as a WebSeed, so torrenting will download from your server in the same way as a streamed/direct downloaded video. As such, I don't see how this can lead to "very large server loads".

Note that we provide a Nginx configuration that fully leverages the fact handling files is very efficiently done within reverse proxies. It serves the static file without hitting the Node runtime, leading to lesser loads.

**Comment by Alterak** [comment]
I still think that direct download of videos by default is very bad because many people just want to download the video instead of watching it. It’s best to disable this feature by default, but also add this feature in the control panel and also when adding video to your account.

**Comment by rigelk** [comment]
> direct download of videos by default is very bad because many people just want to download the video instead of watching it

Then your problem is not anymore with the performance? What makes it bad then?

**Comment by JohnXLivingston** [comment]
Moreover the recommanded nginx configuration includes a bandwidth limit. So I don't see any performance problem here.

**Comment by Alterak** [comment]
> Moreover the recommanded nginx configuration includes a bandwidth limit. So I don't see any performance problem here.
But what if I have a general limit on the entire server at 20Mb, but several people are downloading at the moment? It turns out that everyone else will have difficulty watching other videos?
I mean, when my instance is handed out alone, without helpers.

**Comment by JohnXLivingston** [comment]
But when you are viewing a video, the player transfer the same amount of video. The only difference is the time distribution. But on average, it changes absolutely nothing.

**Comment by Alterak** [comment]
> But when you are viewing a video, the player transfer the same amount of video. The only difference is the time distribution. But on average, it changes absolutely nothing.

But first of all, there should be accessibility to watch videos, not downloads.
I wrote that you need to download, but subject to my permission. Especially if I publish my personal video and do not want to download it. Therefore, I want to disable this download function by default.

**Comment by Alterak** [comment]
And why do you think that the download function also loads the Internet connection as the video viewing function? Downloading takes 2 minutes, and watching a video takes 2 hours

**Comment by JohnXLivingston** [comment]
>  Especially if I publish my personal video and do not want to download it. Therefore, I want to disable this download function by default.

Even without a download button, users can always download your videos. With tools like youtube-dl, or simply by searching the video url in the browser console. Removing the button will not prevent downloading.


> And why do you think that the download function also loads the Internet connection as the video viewing function? Downloading takes 2 minutes, and watching a video takes 2 hours

The total amount of data is exactly the same. When you are viewing the video, it is the same file that is downloaded. The difference is that it is done in one shot, and not by chunks. The bandwidth problem occurs when they are multiple users viewing/downloading videos at the same time. Users downloading are using the bandwith over a short period of time, users viewing are downloading chunks at the same speed, but divided in short period. On average, this is exactly the same. The average bandwidth will be the same, but only distributed otherwise.

**Comment by rigelk** [comment]
> But what if I have a general limit on the entire server at 20Mb, but several people are downloading at the moment? It turns out that everyone else will have difficulty watching other videos?

That's why there is a limit *per connection* at the reverse proxy. Lower it to your liking.

> I mean, when my instance is handed out alone, without helpers.

What do you mean by helpers? I assume you mean the reverse proxy configuration. If you are using PeerTube without an equivalent of the Nginx config we provide (and require for support), you should first solve that problem as it will be the main drive for your performance. By this point I think the performance point is covered @JohnXLivingston.

> you need to download, but subject to my permission

If simply hiding the download button is enough, and you do understand that it will not prevent usage of direct download by other means (like youtube-dl and NewPipe for instance), then hiding the button instance-wide is possible via a plugin or via custom CSS.

If you have hard requirements on whether a specific person can download the video, then you need a DRM system, which you will need a plugin for.

**Comment by Alterak** [comment]
It is unfortunate that you did not understand me and did the video hosting in file storage mode - (((

**Comment by DontUseGithub** [comment]
> Downloading takes 2 minutes, and watching a video takes 2 hours

Watching a video may take 2 hours, but it buffers in a few minutes, just as if you were to download it.

**Comment by fishfree** [comment]
@rigelk I support the idea of globally disabling downloading, but users can enable it when publishing. When people watch videos on site, they are more likely to comment and interact; when they download videos, almost no interaction.
