### ISSUE TITLE
Make video auto-blacklisting default

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2661]
Anyone who has recently browsed a few PT servers (even popular ones) saw that the number of _very bad videos_ (so to say) has increased. I can think of two possible solutions (maybe someone else has some better ones, **which don't reduce the admin's freedoms**, but still help PT become a better place):

- By default set `manualApproval` to `true`. Of course this is just a default change, any admin can change this back (if they think they can handle the in-real-time moderation).
- Keep the default as it is now, but add a modal window (during instance setup/upgrade) for admins that will encourage them to enable this option (with an explanation: what is this option and why would they benefit if they enable it).

**Comment by rigelk** [comment]
Are the videos local or remote ? If they are local, then improving the moderation tools is the way to go, and why not make auto-blacklisting default, yes.

Otherwise, if the videos are remote, the instance should just review their follows and remove the unmoderated ones. We are also reworking how autofollow is set in the configuration since there are clearly many instances which do not care about their content once they enable it.

**Comment by DontUseGithub** [comment]
They're remote. 

> if the videos are remote, the instance should just review their follows and remove the unmoderated ones

You're right. But by enabling `manualApproval` by default we're making sure that 'bad moderation practices' isn't happening by mistake or lack of technical knowledge (real life example https://github.com/Chocobozzz/PeerTube/issues/2653) or something else but because of a conscientious decision made by the admins.

**Comment by Chocobozzz** [comment]
I don't think we should enable auto blacklist by default because the majority of peertube instances are  not intended to be public with open signups. 

Moreover, we added modals, documentations and warnings to help admins to correctly setup their instance, and help them to moderate it.

**Comment by DontUseGithub** [comment]
We could turn on 'auto-blacklisting' by default only for those instances which are opened for public signups. And then use modals and other info to inform them on how they can revert these changes and customize their server. So instead of choosing "**weak**" defaults and then ask them to better moderate their instance, we can do it in reverse: set up "**strong**" moderation defaults and teach them on how they can change them, to remind them that they can do whatever they want with their instance, and moderate it however they want.

**Comment by JohnXLivingston** [comment]
Another idea: having multiple public index, all based on the instance list https://instances.joinpeertube.org , but that can be moderated differently. Peertube instance's owner can then choose which index they want to follow. And the moderation will not be centralized.
This will allow us to have different indexes, with different moderation policies.

It is also a way to have thematic group of peertubes instances. If a want to federate instance that are dedicated to music, all I have to do is provide a https//instances.peertube_music.tld index, based on https://instances.joinpeertube.org and filtred on the «music» criteria (I and can manually check for spam or malicious instances)

**Comment by rigelk** [comment]
@JohnXLivingston this is already possible, you just have to follow the documentation at https://framagit.org/framasoft/peertube/instances-peertube#peertube-auto-follow

**Comment by JohnXLivingston** [comment]
@rigelk yes, but we could develop and share the code for such indexes. And have a list of indexes on instances.joinpeertube.org, so that admin can find them.

**Comment by rigelk** [comment]
@JohnXLivingston yes, but that is a bit outside the scope of this issue. I suggest you open an issue with a link to a proof of concept on the instance list codebase, or questions along the way.

**Comment by DontUseGithub** [comment]
My apologies for bothering you with this question, I'm just worried about the current situation: Is there any chance for this fix to land in 2.2? Thanks.

**Comment by test2a** [comment]
we now have better site wide video reporting tools. I was wondering if we can have a setting for temporarily blacklisting a video if there are lets say "x" number of reports against it.
Imagine this. a bad actor uploads a video which is against an instances' terms. Now, either a moderator can go ahead and manually verify all uploads, which becomes difficult if many videos are being verified or expect the community to report bad videos and assume rest are okay. Now, if moderators are busy for whatever reason, i hope the system blocks that video, until someone reviews that automation.

**Comment by Chocobozzz** [comment]
@test2a I think a plugin could do such thing

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/16a173bbc98509705105eec8189fa5543d9673c7

**Comment by Niquarl** [comment]
I know this has been closed but because it's titled 'auto-blacklisting' I just wanted to mention that some, because of BLM, seem to think that 'blacklist' is racist and it would be better to use 'auto-blocklist' as a default to be more inclusive.

**Comment by rigelk** [comment]
@Niquarl this is already addressed and changed, isn't it? On which version are you reporting that?

**Comment by Niquarl** [comment]
Yes, you are right @rigelk. Sorry. It's the title of this issue that confused me. It does say 'block' on PeerTube.
