### ISSUE TITLE
[feature] livestream

### ISSUE THREAD

**Issue by jibe-b** [Chocobozzz/PeerTube#272]
The livestream option depends mostly on the availability of a camera app that uploads continuously on a peertube server.

Do you know which camera app/desktop-program does this?

The livestream feature will then be a free lunch option (only tutorial(s) needed), and I propose to write the tutorial(s) needed to make it concrete for users.

**Comment by rigelk** [comment]
It doesn't depend *mostly* on the availability of a camera app. It does depend however, on [different technologies that what we are currently relying on: WebTorrent](https://github.com/webtorrent/webtorrent/issues/243). It is made for static immutable files. See [the discussion](https://github.com/webtorrent/webtorrent/issues/448) about implementing it anyway by some WebTorrent folks.

Aside from that, please use the search feature: the problem is a duplicate of #151

**Comment by jibe-b** [comment]
sorry for the duplicate and thanks for the anwer
