### ISSUE TITLE
Replace the term “blacklist” by e.g. “blocklist” to avoid the “black == bad” connotation

### ISSUE THREAD

**Issue by blipp** [Chocobozzz/PeerTube#2790]
Thanks for your work on this project! The recently published roadmap for 2020 inspired me to donate to the fundraiser and to become a recurrent supporter of Framasoft.

I want to suggest that the term “blacklist” be changed to another one, to avoid using the connotation that “black == bad”.

Replacing blacklist by blocklist seems a common choice to solve this problem, see for example Travis CI ([Tweet by Amy Gebhardt](https://twitter.com/amlyhamm/status/1202684742069604353)), and Chromium ([Article by The Register](https://www.theregister.co.uk/2019/09/03/chromium_microsoft_offensive/), [entry in issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=981129)).

**Comment by mcgodwin** [comment]
Great suggestion, thanks @blipp !
I fully agree it's about time we move on to new terminology in software development.

**Comment by blipp** [comment]
Thanks @mcgodwin for the positive reply.

I am worried about the thumbs down and similar negative emoji reactions, and so I would like to add a couple of thoughts:

- This is *not* about accusing contributors of being racist (by e.g. deliberately choosing a term that can be perceived as racist). I do not want to accuse anyone here of being racist. I am sorry if I offended any contributor of this community, by being unclear in my first message, because I tried to keep it short.

- This is about moving forward. First, by raising awareness that a term that has been used for a long time in software, can be perceived as offensive to underrepresented groups. And second, by choosing more inclusive language.

- At the same time, this can be about choosing language that is actually more accurately describing the behavior of the software. “Blocking” a video might speak more directly to novice users than making a video “black”.

If the community decides *that* the term should be changed, and then decides *to what* it should be changed, of course the technical questions arise: While a change from blacklist to e.g. blocklist *is literally only one letter* for each occurrence, the question is how to do this change without breaking things in the ecosystem. I have no expertise in release or update management, so I am not able to estimate the cost; but I assume the earlier it happens within PeerTube's life cycle, the easier it would be. I am happy to help by creating pull requests, for example.

**Comment by k09i71** [comment]
> can be perceived as offensive to underrepresented groups

Can or is it for sure? I wanna see a few videos where some groups of black people are complaining about the word 'blacklist'.

> And second, by choosing more inclusive language

Show me a few comments where black people are complaining to a project that uses the term 'blacklist', and where they say the feel excluded because of that.

**Comment by mcgodwin** [comment]
> Can or is it for sure? I wanna see a few videos where some groups of black people are complaining about the word 'blacklist'.

I am sure you can do some research yourself! You will quickly find proof that these terms pose a problem.

> Show me a few comments where black people are complaining to a project that uses the term 'blacklist', and where they say the feel excluded because of that.

Same. We are not here to do the research for you ;)

**Comment by JohnXLivingston** [comment]
I am 100% for this proposal. There is no good argument for not doing it.

**Comment by DatBewar** [comment]
I don't care which solution will be choice, but don't a rude and do not told to people that there is no good argument to not doing it.

Removing words, which are IT words in a IT project, will not helped to educate people.
Everything need to be understood in their context.

I will be sad to see a French project at the beginning, getting hit by "American sensibilities".
I mean, this is a America cultural problem of always try to clean  everything  even when it's not a problem in a specific context which is the case here IMO.
It's a world project now, not a place to try to fix all the earth and humanity problems.

Here one example of project which took the choice to not change(Redis):
http://antirez.com/news/122

To conclude IMO, it should be a community decision not a sensibility decision.

**Comment by mcgodwin** [comment]
It is a political decision indeed. Do we want to finally look at our white privilege with integrity and courage and contribute to make the world a better place for everyone else? Well, I do. Doing nothing and encouraging the status quo (keeping the same terminology just because "we've always done it this way" without addressing the racist aspects of it) is in fact participating to oppression. It is up to us to educate ourselves and act accordingly.

**Comment by DatBewar** [comment]
Yeah, and I think it's not a good context for political decision.
It's not because "we have always done it this way", it's an IT terminology applied in an IT project.
Now I repeat myself, I think that should be a community choice so, we will see.

I already had some seminar about "privilege", the fact we don't know we don't know, etc...
I understand your position.

**Comment by mcgodwin** [comment]
I hope you agree that software and IT don't exist in a vacuum. They are used by real people and they contribute to show to everybody what is allowed / possible or not. So switching language has a huge impact on how we collectively see the world. Peertube holds a lot of great values. Switching to terminology that DOES NOT IMPACT usability and understandability of the software AND show that we acknowledge and respect systemic oppressions and want to do our little part about it is, I think, the bare minimum.

As a systemic designer, I try my best to not isolate things. Isolating things is an open door to gaslighting and arguments that don't apply to real life situations. I suggest this post by Mike Monteiro: https://deardesignstudent.com/how-to-fight-fascism-dabdfeab1830

**Comment by DatBewar** [comment]
I can take this argument, but this words are not here to show to everybody which are allowed or not. In my opinion, the employment context is very important. Here we are using a term which have never been used in IT for inappropriate thing.

I agree with your fight, I may think that it should be better to educate people instead of removing every thing which is bad in the world because it will always had bad thing in the world.

We debate about this terms today but in the future it will be others, deleting this terms will not suppress ignorance.

**Comment by mcgodwin** [comment]
"The UK government's cyber-security agency said this week it would stop using "whitelist" and "blacklist" due to stigma and racial stereotyping surrounding the two terms.

Instead, the UK National Cyber Security Centre said that going forward, it would use the terms "allow list" and "deny list" instead of the two.

"It's fairly common to say whitelisting and blacklisting to describe desirable and undesirable things in cyber security," said Emma W., Head of Advice and Guidance at the NCSC.

"However, there's an issue with the terminology. It only makes sense if you equate white with 'good, permitted, safe' and black with 'bad, dangerous, forbidden'. There are some obvious problems with this," she added.

"So in the name of helping to stamp out racism in cyber security, we will avoid this casually pejorative wording on our website in the future."

https://www.zdnet.com/article/uk-ncsc-to-stop-using-whitelist-and-blacklist-due-to-racial-stereotyping/

"No, it's not the biggest issue in the world - but to borrow a slogan from elsewhere: every little helps," the NCSC said.

**Comment by mcgodwin** [comment]
I can go on and look for other sources. These ones took me 3mn to find.

The Limerick Institute of Technology brought this topic on the table in 2018. So it is safe to say that these terms are not set in stone, especially when IT research directors point out their impact. They know what they are talking about, probably better than us even. And they advocate for a change in language in IT.

SO ?

I suggest we resolve this topic and actively choose to show a good example on Peertube by changing ONE letter in a word. It's just a word, it harms NO white person, and it contributes to show all people of colour that we give a shite and we are decent individuals ready to make bad things from the past disappear. Enough said for me. If you don't want to learn from the past's mistakes, I'd rather leave you behind cause I have a lot of work to do, like changing the way I use words to make oppressed people's life less of a hell.

Have a great weekend everybody!

**Comment by DatBewar** [comment]
What I read here is an argument from authority.
In IT we speak with a specific IT language.

You want to change it, well let the community choose.

**Comment by JohnXLivingston** [comment]
Furthermore, «block list» (or «deny list») will be better understood. Peertube moderators are not necessarily all from the IT world.

**Comment by DatBewar** [comment]
I have said all the stuff I needed to say.

"By banning those words, you’re giving them the meaning you don’t want them to have."
https://medium.com/@Zh0uzi/on-banning-racial-terms-in-programming-bdc5b6255d9f

**Comment by taziden** [comment]
> I am 100% for this proposal. There is no good argument for not doing it.

I manage a Peertube instance and I'm also 100% for this proposal.

**Comment by gagzzz** [comment]
> "By banning those words, you’re giving them the meaning you don’t want them to have."

Ah, the very last argument when one knows they're wrong but don't want to accept it. I've seen this exact argument being used to refuse the use of gender-neutral phrasing in other projects…

Anyway, I'm here to say that I'm also in favor of this change. Even more: I think it's important because language carries culture, and specifically mainstream culture. Mainstream culture is white, rich, male, cisgender etc. This mainstream culture takes care of making other cultures less visible, and even discredits them. People with privileges, people able to see themselves in such a mainstream culture, if they want to help less privileged people, need to take this seriously and review their language.

BRAVO for everything peertube and framasoft, I think that's something you (as a group at least) take seriously, and that's something great!

cheers

**Comment by DatBewar** [comment]
For sure I don't think I'm wrong, but contrary with you I'm open mind to listen what people think and let them talk without saying "you are wrong".

Cheers

**Comment by 3risian** [comment]
I agree with this proposal.
On a personal level I feel like that interpreting the connotation as racial is confirmation bias that ignores the longstanding meaning of the word, although that doesn't mean that the term shouldn't be replaced. It's not unreasonable for someone to interpret that connotation and feel unaccepted, and so far I have not been convinced by a counterargument that it should remain. Replacing a terminology isn't banning the old one, plus if I'm not mistaken an instance can easily change it back if they do interpret this as problematic social censorship. Like security, I feel that safest by default is appropriate in this situation.

Regardless, on a user-experience level, I believe that 'block' and 'allow' is a much clearer, self-explanatory terminology than the pre-existing 'black' and 'white'.

Note: I take issue to the civility of many comments on both sides of this argument, such as the accusatory nature of one of the comments which appears to blindly assert that other PeerTube contributors have white privilege, as well as the comment implying wanting to not offend is somehow an "American sensibility" that other nations don't have, as well as an assertion that "there is no good argument" for something they are currently unconvinced by. This rhetoric does not seem constructive on a software issue tracker. While I recognize there is most likely no offence intended, these kind of comments don't help maintain civil discussion.

**Comment by JohnXLivingston** [comment]
> as well as an assertion that "there is no good argument" for something they are currently unconvinced by.

I should have say «I can't see no good argument». My bad, you are right.
