### ISSUE TITLE
Unlisted video shouldn't be published through ActivityPub

### ISSUE THREAD

**Issue by taziden** [Chocobozzz/PeerTube#280]
* **PeerTube version or commit:** Peertube v0.0.20
* **Browser name/version:** N/A
* **NodeJS version:**  NodeJS v8.9.4

* **PostgreSQL version:** 9.6

* **What is the expected behaviour?**
When a video is uploaded as "Unlisted", it shouldn't appear on ActivityPub (eg. Mastodon)

* **What do you see instead?**
I've published a video as Unlisted and it appeared in my Mastodon timeline, as I follow my @user@peertube-instance (@taziden@media.zat.im)

**Comment by Chocobozzz** [comment]
On Mastodon, an unlisted toot is just hidden from the public feeds no?

**Comment by tcitworld** [comment]
I'm not sure the expected « unlisted » mode of Peertube matches the « unlisted » mode of Mastodon toots, since Mastodon toots that are not shown to users and only accessible through URLs are not useful.
Maybe add another mode to clarify things : 
* public : everyone, published everywhere
* restricted : just followers, published to followers
* unlisted : not published, accessible through URL
* private : only the creator accesses it

**Comment by Chocobozzz** [comment]
I'm don't like having too many possibilities because it would confuse users.

I think the best solution is to remove the followers audience when we send the video through ActivityPub, so it won't appear in timelines.

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/276d03ed1a469fd4e3579f92392b6f9a1567d1ca
