### ISSUE TITLE
add more info to instance stats

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2835]
Would be nice to add more information to the stats section of the about page

- \# Users Online Now
- \# Videos Views Today

**Comment by Poslovitch** [comment]
> # Users Online Now

To do that, we would probably need to keep track of how many "auths" occurred. As far as I know, the only way it could be done is by adding some sort of "user store" in https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/auth.ts.

I, however, have no idea how it could be implemented.

**Comment by test2a** [comment]
We probably need an entire stats page for that. If you say online today or now, then we should up this to say last week or month also because why not.

Then we could also show most viewed video, most commented video, most shared and downloaded.

Then most viewed channel, user.

Top commenter, top video creator by views, number of videos etc.

Most liked video in all forms above.

There are many possibilites

**Comment by Chocobozzz** [comment]
I added a hook in https://github.com/Chocobozzz/PeerTube/commit/650580504cf14a87bd4025eec9673eb5642dc71d so you can add stats you want using a plugin
