### ISSUE TITLE
Local PeerTube user is blocking LDAP login

### ISSUE THREAD

**Issue by mkoppmann** [Chocobozzz/PeerTube#2857]
**What happened?**

I enabled the LDAP plugin but the login wasn’t possible, because my old local PeerTube account exists.

**What do you expect to happen instead?**

Having some kind of option to takeover the old account. AFAIK it’s not possible to delete the local account and re-use the username.

**Steps to reproduce:**

1. Create a PeerTube user with username `foo`.

2. Create a LDAP user with username `foo`.

3. You can’t login with your LDAP credentials because the username is taken.

**Additional information**
* PeerTube version or URL: 2.2.0
* auth-ldap plugin version: 0.0.3

**Comment by Chocobozzz** [comment]
You can try to update manually the user:

```
update "user" set "pluginAuth" = 'peertube-plugin-auth-ldap' where username = '...';
```

**Comment by mkoppmann** [comment]
Thank you, that worked. You’re doing a great job :+1:

**Comment by cremos** [comment]
Hello,
Weird, I added in the "pluginAuth" field of the "user" table the value "peertube-plugin-auth-ldap" via the command: update "user" set "pluginAuth" = 'peertube-plugin-auth-ldap 'where username =' ... ';

But the app always tells me "Cannot create such user: an actor with that name already exists."

Thank you in advance for your feedback.
Cremos

**Comment by cremos** [comment]
Hello,
Yes the authentication works well now but I must first manually delete the record of the user "cmousli" from the table "actor" and in the manipulation this user loses all his media. Peertube creates a new LDAP user but does not update the old local account.

Yours

**Comment by cremos** [comment]
Hello,
Help, I'm still stuck, can you tell me if other people are having the same problem?
Yours truly

**Comment by gnouts** [comment]
I was in the same case as @cremos.

I could not login using my account, since it used to be local, and now with LDAP working, it conflicted. I change pluginAuth to "peertube-plugin-auth-ldap" but it was still not working. (same error "Cannot create such user: an actor with that name already exists.")

I tried to revert pluginAuth to login as a local user again ( `update "user" set "pluginAuth" = Null where "username" = 'nouts';`) and it did not work either. (same error)

Since pluginAuth was Null (not "peertube-plugin-auth-ldap"), I could reset the password of my user from an admin account.
This way I was able to connect to my account, using old local auth.
So I notice if I change back my password to the same I use in LDAP (username and password being the same on both ends), I can't login. But if local user have a different password than LDAP user , I can login as a local user.

Not sure I understand everything, maybe someone can make sense out of this ¯\_(ツ)_/¯ 
In the meantime, I regain access to my account (as a local user), but my password is not sync to and different than LDAP  :/

**Comment by Chocobozzz** [comment]
Updating the `pluginAuth` like you did should work.

I think the issue here is that you have the same LDAP username, but not the same email. PeerTube tries to load the user from the DB according to the email provided by the LDAP plugin. If it does not exist, it tries to create it. But it conflicts with the existing user that has the same username.

So try to change your email in the peertube interface to be the same than LDAP.

**Comment by cremos** [comment]
Hello,
I just verified a user account that has the same username manually created and that of LDAP. The e-mail address is the same. I checked with the ldapsearch command.

**Comment by Chocobozzz** [comment]
Enable debug logs and just check the [SQL request](https://github.com/Chocobozzz/PeerTube/blob/94d721efdc9a8c2cda612f49506a41adb6a06f1d/server/models/account/user.ts#L584) just before `Cannot create such user: an actor with that name already exists.` error (

**Comment by cremos** [comment]
Hello,
Thank you for your feedback, when logging in I get the error message "Incorrect username or password." I started Peertube in debug mode: journalctl -fu peertub:

`févr. 20 18:56:00 tube peertube[19380]: [tube.ac-amiens.fr:443 peertube-plugin-auth-ldap] 2021-02-20 18:56:00.550 warn: Cannot login lwantiez1 in LDAP plugin. {
févr. 20 18:56:00 tube peertube[19380]:   "err": "no such user: \"lwantiez1\""
."id" = "NotificationSetting"."userId" WHERE (lower("username") = lower('lwantiez1') OR "UserModel"."email" = 'lwantiez1') LIMIT 1;
févr. 20 18:56:00 tube peertube[19380]: [tube.ac-amiens.fr:443] 2021-02-20 18:56:00.562 warn: Login error. {
févr. 20 18:56:00 tube peertube[19380]:   "err": {
févr. 20 18:56:00 tube peertube[19380]:     "statusCode": 400,
févr. 20 18:56:00 tube peertube[19380]:     "status": 400,
févr. 20 18:56:00 tube peertube[19380]:     "code": 400,
févr. 20 18:56:00 tube peertube[19380]:     "message": "Invalid grant: user credentials are invalid",
févr. 20 18:56:00 tube peertube[19380]:     "name": "invalid_grant",
févr. 20 18:56:00 tube peertube[19380]:     "stack": "invalid_grant: Invalid grant: user credentials are invalid\n    at new InvalidGrantError`

**Comment by cremos** [comment]
Hello,
I redid the same steps as @gnouts and I see the same thing.

**Comment by cremos** [comment]
Signaling on the error:  Error: LDAP Invalid grant: user credentials are invalid [ HERE](https://github.com/Chocobozzz/PeerTube/issues/2773) 
The solution did not solve my LDAP authentication problem.

**Comment by cremos** [comment]
I just tried again.
1 / Creation of a local account, same username and email as the LDAP account, but the password is different.
2 / connection with the local account and upload of a medium.
3 / update of the "pluginAuth" field of the "user" table by the value "peertube-plugin-auth-ldap
4 / Authentication with the LDAP account without problem and the media and present.
