### ISSUE TITLE
protect clients connected with mobile data from using up their data

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#2887]
Feature request, regarding the webtorrent feature of peertube:

Clients connected with mobile data, are able to download only the smallest version of the streams, contained in the torrent of a video. If the video only contains 480p or bigger streams, then a warning message should appear.

Clients connected with LAN should download all streams contained in this torrent, if they have a good upload speed. So they can P2P-share all resolutions of the video file.

This question is referring to #2849, which i could not re-open.

**Comment by test2a** [comment]
there are many apps that use mobile data detection to check that and then ask user to restrict the resolution. for example, newpipe android has a setting, "limit resolution when using mobile data" which i have set to 360p, meaning i will default to 360p if the app detects i am using mobile internet.
my question, are you asking this feature about any app or the website because i don't a website can check which internet is being used. For that, i could suggest an option which would limit a users max video quality.

**Comment by rigelk** [comment]
PeerTube doesn't have access to a native API like a native app (i.e. NewPipe) does.

**Comment by Chocobozzz** [comment]
Hello,

The HLS player already do not seed data when the user is on a mobile connection. We can't do that with the webtorrent player, that is in "legacy mode".

The player is capped to the resolution of the screen, so we don't display a 1080p video on a 300p screen if there is an available 360p video file.
