### ISSUE TITLE
An alternative for the scary warning from the embeds

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2932]
currently the text from embeds says:
![12](https://user-images.githubusercontent.com/65374098/86512674-cf002680-be0c-11ea-8f36-f4b502d38c19.png)

I find it pretty 'scary', especially for those who have little IT knowledge. 

I think we should change the text, write something like "You may wanna click [here](https://peertube2.cpy.re/about/peertube#privacy) before watching this video". Where the link will be from the instance that is hosting that embed e.g. https://example.com/about/peertube#privacy
And remove the text completely when p2p is disabled by that instance.

**Comment by tdelmas** [comment]
> "You may wanna click here before watching this video"

That looks more like an ads that a link with information about privacy. Sharing your IP with strangers is not something common, so informing the user (and by that I mean, giving the information, not bury it in a page behind a link) is important in my opinion.

In some countries, and/or for some people, viewing some kind of video may be really sensitive and if known can lead to tragic real life consequences.

**Comment by MarkusSmith** [comment]
Wouldn't such people viewing sensitive videos already be using VPN or TOR? I don't think the small risk for a tiny minority is worth scaring off the majority of viewers with a scary message. Many people just won't watch the video because they've been scared off by the message and therefore won't use or watch peertube. So peertube will remain a niche platform.

**Comment by JohnLines** [comment]
I am concerned that too much emphasis on what should be exceptional cases leads to building a federated internet for the few, while 99% see the scary warnings and retreat to the safety of YouTube. I know it is important not to risk the security of people using PeerTube to distribute videos of content their government would want to keep hidden - the dramatic case, but I would also like to to be an option for your grandmother's knitting group to show how to knit Fair Isle patterns - and the less dramatic case should be much more common.

Would it be possible to have, for example, a set of 'trusted' sites in the PeerTube configuration which would not show a warning when embedded from those sites ? These could be, for example, the Wordpress sites of the knitting groups or whatever.

**Comment by kontrollanten** [comment]
I'm ambivalent to this.

In one side a appreciate the transparency provided by PeerTube regarding the IP sharing, like @tdelmas is describing.

On the other side I think that, just as @JohnLines and @MarkusSmith is telling, it's hard to an idealist when your opponent is foul playing. Even I, with technical knowledge, get a bit scared an confused when reading this warning.

I vote for removing the warning. Otherwise _#3420 Custom CSS not injected to embedded player_ can solve this by hiding the warning with CSS.

**Comment by test2a** [comment]
I have written this here earlier and more publicly, like it or not, many ISPs in the world today have switched to CGNAT or carrier grade Nat. This is because a real lack of ipv 4 addresses. Take for example the Jio in India. That ISP has millions of fiver customers and there simply arent that many ipv4 available so they do CGNAT where just one public IP is used for ALL the subscribers. This also has a sideeffect of not allowing inward access for even security cams and other home servers but still.

The privacy benefit OTOH is quite high. For example, when it comes to github my IP is the public address of Jio which is same for all subscribers.

The scary warning " your IP address can be monitored" goes nowhere without the help of ISP. That leaves almost all the offensive people unless they have ISP level access.

What I mean to say is, we should explain this CGNAT fact in the "privacy" of webtorrents.

That said, I don't see livestreaming working without the help of p2p. A couple of days ago I watched a live stream and my total download was around 1 GB. 600 MB from server, 400 from peers. 250 MB uploaded. I have seen stats where they downloaded 1 GB from server and 10 GB from peers. I am saying multiplying these raw GB scale figures times say even 100 concurrent users and that means a lot of bandwidth for the servers to handle. Too much even. P2p design is what makes it possible, no other way so we should try to explain the feature in a positive way.

Scaring people into disabling them for trivialities is not helping the p2p nature of peertube.

**Comment by Chocobozzz** [comment]
Closing now admins can easily alter the message using plugins or hide it using CSS.
