### ISSUE TITLE
Privacy concerns around P2P, WebRTC and the opt-out pattern

### ISSUE THREAD

**Issue by FedericoCeratto** [Chocobozzz/PeerTube#2934]
Hello and thank you for developing PeerTube. Various people have already expressed concerns around privacy in the issue tracker.

1. The webtorrent swarm used by PeerTube leaks the IP address of the peers (by design)
1. Some attackers can easily correlate IP address with the content being viewed and re-shared
1. Re-sharing is enabled by default (aka it's opt-out)
1. There is no clear warning about this behavior on the landing page and no process to require **informed** consent.
1. Most users don't know what "p2p" and "IP address" mean and cannot provide informed consent by looking at a warning and not opting out

The overlap of these 4 aspects makes the opt-out behavior worrisome. Can you please let me know if I'm missing something? Thanks.

**Comment by rigelk** [comment]
The about page informs your points 1 & 2.
As for the warning, it is present on the watch page and the embed.

**Comment by FedericoCeratto** [comment]
(FWIW, I'm aware of the about page but it's besides the point of informed content and opt-out)

**Comment by Githubuxer** [comment]
Agreed, just signed up and didn’t know anything about this until now. Hopefully I am protected with setting off now.

Does using a VPN prevent up leak in this situation?

**Comment by rigelk** [comment]
@Githubuxer there is no leak when using a VPN.

Leaking your public IP did indeed used to be an issue with WebRTC, but this was fixed a long time ago (back in 2011) in Firefox and Chrome. There's now a spec that defines exactly which IP addresses are exposed with WebRTC. You can read it here: https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-01

WebTorrent has a whole FAQ section explaining why that doesn't happen anymore: https://webtorrent.io/faq

**Comment by anon97945** [comment]
Can't you switch off the "Help share videos being played" option by default and only make it available if the user wants to support the server. After all, the server owner would then decide for himself. Or is this option already available for server operators?

**Comment by test2a** [comment]
My two cents. MANY isps around the world now use CGNAT or carrier grade Nat. This means for all intents and purposes, all their customers are given just one IP.

Now, while CGNAT is not funny when trying to set up a server at home but privacy wise its really good except your ISP ofcourse.

This means any website I log in or torrent sees that one ISP public IP. They can corelate and all but unless the ISP is helping, it would be much difficult.

The reason why I think sharing is enabled by default is because for the most part there isnt much sneaky stuff on public servers. Why do I care if some attacker can find me using cat videos. The benefit is more because the server load is reduced and that is really more important.

If, you want to protect the privacy of users, the server can disable sharing and use just HLS and this problem would go away but peertube needs sharing to grow.

**Comment by anon97945** [comment]
that is not entirely correct and not entirely thought out, I just want to prevent users from getting my ip, especially since peertube does not have so many calls and the swarm is so small that you can see all users.

Furthermore, I specifically mentioned whether there is a possibility of making the option "server-side" as an opt-in and not an opt-out, so every server operator can decide for himself.

**Comment by test2a** [comment]
Yes. If the server decides to disable webtorrent, this feature should be disabled for all.

**Comment by anon97945** [comment]
@test2a 
So it is not worth talking about whether you can switch off p2p globally on the server side, as this would result in a loss of functions

**Comment by test2a** [comment]
I don't think so. There are two ways of serving videos. One is webtorent where it works like that and the server is just another peer. Same when more people join, they should also share data and as such, server load is reduced.

Another is HLS where the server acts like YouTube. Each visitor is served files independently and as such, the server has to cater to all users on its own.

Its Upto the server administration to decide if they want either or both.

**Comment by anon97945** [comment]
But its true. 😄 

![Uploading 14f9838b14781d6d.png…]()

**Comment by Chocobozzz** [comment]
Hello,

In https://github.com/Chocobozzz/PeerTube/commit/a9bfa85d2cdf13670aaced740da5b493fbeddfce admins have now the choice to opt-in or opt-out P2P in PeerTube.
