### ISSUE TITLE
Missing system icon for iOS ‘add to home screen’ functionality

### ISSUE THREAD

**Issue by OddHouseGames** [Chocobozzz/PeerTube#2939]
![image](https://user-images.githubusercontent.com/62911518/86741739-9f683e80-c005-11ea-8285-230f6b0a27c3.jpeg)

**Comment by rigelk** [comment]
A2HS was already implemented following https://github.com/Chocobozzz/PeerTube/issues/269. Maybe you could point us to what iOS expects more from us?

**Comment by rigelk** [comment]
A good ressource to begin with would be https://www.netguru.com/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native - though a more recent source would be nice.

**Comment by kontrollanten** [comment]
@rigelk I think your resource is still accurate, anyway here's Apples documentation: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Wouldn't it be neat if all icons where created (and added to HTML file) during build time? Then the client-overrides solution would work in more environments (today it only works if you have a reverse proxy pointing to it), but from a user perspective it won't change (you still just put your files in the client-overrides folder).

Since angular CLI is using webpack under the hood it's possible to let Webpack plugins generate the files by using [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack).

This will also add hashes to the filenames so the cache is purged when a user changes files.

**Comment by Casuallynoted** [comment]
Would also really like to see this, since I'm not sure how soon we'll likely see a native iOS app.
