### ISSUE TITLE
Link Share Video From Host Instance, Not Viewing Instance

### ISSUE THREAD

**Issue by seniorm0ment** [Chocobozzz/PeerTube#2972]
Suggesting the ability to share videos directly from the video hosts instance, not the one you view the video from.

_For example, if I am on instance1 watching instance2's video, I can share the video by clicking share and copying a link to the video. It shares it using the link of instance1, I am suggesting a quick and easy way to get a direct link to instance2._

**Comment by k09i71** [comment]
Would be nice to have it, but IMO it should be a little hidden under 'Advanced options' or something similar. 

Direct links are a little dangerous because you never know what that instance is about and what kind of content is there, until you visit it. Instance2 may federate with instance1 but only show videos of some trusted channels while banning everything else, thus protecting its users.

**Comment by LPS-github** [comment]
Hi, I'm confused about this topic being labelled as an enhancement.  Currently, this seems to be a bug, where would I create a bug report?

I'm currently unable to share a link from a subscription (on my server) that a recipient without a login can receive successfully.

The currently behaviour, as indicated above, is that when sharing a subscription link from my own instance, the share link provided is not the source url but instead uses my home server subscription url.

The problem is that it is not viewable to anyone other than myself.  The link requires a login to my instance.  This clearly makes the sharing functionality in this case unusable.

**Comment by Chocobozzz** [comment]
We display the origin instance URL below the video. If you want to share the origin URL, use it.
