### ISSUE TITLE
Is there a demo online?

### ISSUE THREAD

**Issue by feross** [Chocobozzz/PeerTube#3]
This seems really cool! Is there a demo link online somewhere? There are a lot of dependencies to install -- a demo link would make things way easier for visitors to check it out!

**Comment by Chocobozzz** [comment]
Hi @feross, really glad you like the project!

Yes you're totally right, but PeerTube is unusable in "production" yet because of the [CPU leak issue in Electron](https://github.com/feross/webtorrent/issues/551) (PeerTube server seeds 24h/24h the uploaded videos with the help of an Electron process).

So I'm just waiting the new release of Electron (based on Chrome 50 or 51).

In the meantime, I'll add a small video in the README to allow people to see what it looks like.

**Comment by feross** [comment]
Awesome -- I think we all can't wait until the release that fixes the CPU leak!

**Comment by dadall** [comment]
Any news ? :p

**Comment by Chocobozzz** [comment]
Infortunately there is still the CPU leak in Electron 1.1.0 (and in Chromium 50 on GNU/Linux).

**Comment by dadall** [comment]
What about now ? Chrome 51 is available ;-)

**Comment by rom1504** [comment]
might be worth trying with electron 1.2.0 indeed https://github.com/electron/electron/releases/tag/v1.2.0

**Comment by Chocobozzz** [comment]
Thanks guys, I'll make another try.

**Comment by Chocobozzz** [comment]
Great, the issue is finally gone with Electron 1.2.0. I'll try to put a demo this week-end :)

**Comment by Chocobozzz** [comment]
The [demo](http://peertube.cpy.re) is finally here :)

**Comment by feross** [comment]
👍
