### ISSUE TITLE
Use original framerate for highest resolution

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#3036]
**What happened?**
When a video is uploaded with resolution <720p at 60fps, the served version is only 30fps.
**What do you expect to happen instead?**
It should be 60fps.
**Steps to reproduce:**

1. Upload a video that is 420p60fps. Make sure PeerTube needs to transcode it.

2. Playback the video.

3. Notice that it is only 30fps.

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: N/A
* NodeJS version: N/A

* Link to browser console log if useful: N/A
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): N/A

**Comment by test2a** [comment]
Does this mean the encoding server should check if the transcoding would result in a version lesser than original and in that case ask to serve original also?

**Comment by blobcat-mewmew** [comment]
@test2a What do you mean?

My explicit problem here is videos that are uploaded at 480p60fps, 360p60fps, etc. If they were upscaled and uploaded, a 720p60fps version would be available. But since they are not, the videos are decreased in framerate.

I think we generally *do* take this approach? If an instance only supports 1080p transcoding, but a video is uploaded in 2160p, the 2160p copy is still available. The same should be true here.

**Comment by test2a** [comment]
what if we have a flag on video upload to say "don't transcode".

**Comment by rigelk** [comment]
@test2a what if said video is not streamable, compatible with all browsers, etc.?

**Comment by test2a** [comment]
@rigelk agreed. it wont fly but a question. does peertube check the output of transcode job for that? the versions spit out work or is it assumed that they always will? if there is a check, then maybe check this "non transcoded" file also and if it fails, let the user know that the video might have a problem and that you should probably trancode it. ?

**Comment by blobcat-mewmew** [comment]
I want the video to be transcoded. I just always want the highest resolution version available to use the original framerate.

**Comment by blobcat-mewmew** [comment]
> 
> 
> @rigelk agreed. it wont fly but a question. does peertube check the output of transcode job for that? the versions spit out work or is it assumed that they always will? if there is a check, then maybe check this "non transcoded" file also and if it fails, let the user know that the video might have a problem and that you should probably trancode it. ?

PeerTube transcodes into a format that is widely compatible. And if you upload a video that is already that same format, PeerTube doesn't transcode it. But, I want the video to be transcoded - I just don't want it to reduce the FPS.

**Comment by Tachi107** [comment]
This little script should return 0 when the `moov` atom is located before every other one. I don't know how easily it could be integrated in PeerTube (if needed), but since FFmpeg is already in use I don't think it will be too hard. 

`ffprobe -v trace -hide_banner -i "UploadedVideo.mp4" 2>&1 | grep --fixed-strings --color=never --only-matching --regexp="type:'mdat'" --regexp="type:'moov'" | head --lines=1 | grep --fixed-strings --color=never --quiet "moov"`

`ffprobe -v trace` outputs pratically every info about the video file (it will take something like half a second); the first `grep` looks for the `moov` and `mdat` atoms; `head` only lets the first atom found pass through the pipe; the last `grep` checks if the atom that passed though the pipe is the `moov` atom, and if it is it means that the atom is at the front of the file, and the file is suitable for web streaming.

**Comment by rigelk** [comment]
@Tachi107 we already do that: https://github.com/Chocobozzz/PeerTube//blob/dca0fe12ec2e47be51884c4eb05ebe6f358cb9de/server/helpers/ffmpeg-utils.ts#L310

**Comment by Tachi107** [comment]
@rigelk checking the position of the atom, alongside with the bitrate, could avoid one useless encoding of the video at the original resolution, and would also not compromise the original quality of the video.
In my opinion this should happen without any user interaction. Sometimes the uploader itself does not know if the video is suitable for web streaming. 

Regarding the video framerate, I think that every transcoded version of the uploaded video should use the same framerate. Why shouldn't it?

**Comment by MadMan247** [comment]
Hello,

I wanted to nudge this issue and put in my two cents.

I almost entirely use peertube to store videos that are NTSC interlaced footage 720x480p 29.97 fps deinterlaced for a smooth viewing experience at 59.94 FPS. The only way that I found to preserve my desired 60fps is to disable transcoding altogether. This, however, has multiple negative side effects. It disables the use of p2p on that video, it causes my uploaded file to be larger than it needs to be for it to properly stream, and makes it so that a lower resolution can not be viewed in instances with poor network connectivity. 

I believe that it is illogical that the "transcode at native resolution" option does not preserve the framerate, especially since in the player the framerate is listed with the resolution dimensions, essentially setting itself as a part of the resolution (e.g. 720p60). If it did, I would get the best of both worlds, with the native resolution/framerate, p2p, and transcoding. 

I believe that 480p60 is common enough to support, especially if someone would use the instance to store old episodes of a television series, family home videos, or videos with the "retro aesthetic" involved in VHS/VCRs/Betamax/etc. The only reason I see not to is because this is how YouTube does it, and YouTube is familiar, but I use peertube because I want to get away from the limitations that come with YouTube. Worst case, I would like to see an option in the transcoding settings, alike and/or next to the options for the resolutions that are available for transcoding-- why have control over the resolution but none over the framerate?

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/commit/bbaf96d60d4bc1a40bbc88584524c94c1c2b0b9f the max resolution is transcoded to the original FPS, even if < 720p.
