### ISSUE TITLE
Non-CC licenses

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3048]
Hello,

When i post a video, i'm forced to license it with creative commons, i can't use any license that is more restrictive than CC.

**Comment by k09i71** [comment]
This is good because it encourages FREE as in freedom licenses. So I don't think we should add non-free ones, just add an option called "Custom" where you'll have to type it yourself.

**Comment by test2a** [comment]
there is one that says attribution, that could work for most circumstances where entirely free isnt an option although i am not sure how peertube the decentralisation which is the core of this project would handle copyrighted material.
suppose you post a video on a public instance and you set its license as "all rights reserved. copyrighted material". this license means only you have the "right" to distribute this video, charge for it, or propagate it or earn money out of it. lots of things.

Now, federation is a big part of peertube. one instance easily follows another instance, usually at the decision of instance owners. Suppose in our example you upload your copyrighted material on a public instance but that instance is followed by say 10 others and those provide redundancy also. 
Do you agree to have your material on servers that are not under your control? or how about this. you for example are going to charge money or ads on this video. you can do that no problem but because of federation, your video is available on 10 different instances where your monetization might not work due to plugins or whatever. how would you react at that?

**Comment by Chocobozzz** [comment]
You're free to create a peertube plugin that adds any new licence you want. See https://docs.joinpeertube.org/#/api-plugins?id=server-registerunregister-only-plugins for more information
