### ISSUE TITLE
HTTP Signatures are sometimes incorrect

### ISSUE THREAD

**Issue by ThibG** [Chocobozzz/PeerTube#3075]
When rewriting Mastodon's HTTP Signature parsing, I noticed that a PeerTube 2.1.1 instance fails to sign correctly their HTTP requests.

Indeed, the `Signature` header's value starts with `Signature ` instead of having the signature itself. This seems to be caused by using `http-signature` prior to version 1.3.0.

I am not sure whether the issue is fixed in PeerTube's latest version, but it seems to still depend on `http-signature` 1.3.4 and 1.2.0, so if the 1.2.0 codepath is used for signatures, this will result in the same error.

**Comment by Chocobozzz** [comment]
Hi @ThibG 

Thanks for your issue. I noticed this bug a few months ago and it should have been fixed in 2.2: https://github.com/Chocobozzz/PeerTube/commit/84ebcf345cb82b254853c03c142f7c304fb072dd

Could you try with peertube.cpy.re or peertube2.cpy.re to confirm? (I can create an account for you if you want).

**Comment by ThibG** [comment]
I'm not sure how to force those PeerTube instances to perform requests to my instance, but looking at my logs, the issue does seem to only occur with 2.1. Requests from 2.2.0 and 2.3.0 instances seem fine, and this is consistent with your commit, so I guess this is fixed, thanks!
