### ISSUE TITLE
Transcoding failed: some version has not the right duration

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#3121]
For 2 different videos imported, I got some transcoding failed:

in https://video.lqdn.fr/videos/watch/331bcb93-9651-4af4-b092-1de1c2ac2363
the original video is 32m long
the 480p version is 6m07 long

in https://video.lqdn.fr/videos/watch/fd56df97-d3a8-4f08-a931-a4c7af765842
the original video is 1h50 long
the 720p version is 8m22 long

the first one has been transcoded with v2.2.0
the second one with v2.3.0

**Comment by Chocobozzz** [comment]
Please search and paste your job error log (in admin)

**Comment by vincib** [comment]
It's 3 weeks old, we launch a transcoding job to see if it's still in error, and in that case we will paste the error log here

**Comment by klorydryk** [comment]
We found this error in the log: "ffmpeg exited with code 1: Unrecognized option 'hls_segment_type'"
Then updated ffmpeg from v3.2.14 to the last version, then relaunched transcoding.

Waiting for the result right now.

**Comment by Chocobozzz** [comment]
Any news? :)

**Comment by klorydryk** [comment]
For now, we updated ffmepg and restart transcoding... but there is a bug somewhere: we have only one version left of each video 😱 For example, this one is available only in 1080p now : https://video.lqdn.fr/videos/watch/331bcb93-9651-4af4-b092-1de1c2ac2363
We'll try to understand the reason this week.

**Comment by vincib** [comment]
ok, it's a bit better, but not much.
After we restart the transcoding of everything, most videos are as follow : 

- in storage/videos/ we have *all definitions* for all videos (only the one smaller than the original, of course)
- in storage/streaming-playlists/hls   I have 2 mp4 files per video : one in the original definition, one "audio only" (-0.mp4) and no others. 

And the result on chromium & firefox is that the "quality" menu only gives us the original definition, not the smaller ones. 

eg: https://video.lqdn.fr/videos/watch/331bcb93-9651-4af4-b092-1de1c2ac2363

is it normal that the "create-transcoding-job" is doing the HLS version only for 0 & max-resolution?

**Comment by vincib** [comment]
We just did  another test :  this one : https://video.lqdn.fr/videos/watch/c249320b-5263-4b2b-b1e8-14d07403079c  has (unexpected) the quality "720" and "240" available. That's what the HLS folder has

If we remove streaming-playlists/hls/c249320b-5263-4b2b-b1e8-14d07403079c   we know see all the definitions since peertube is now using mp4 direct files and not hls fragments

So I guess the discovery of this bug is : 

- the transcoding process is not always doing all the wanted definitions for HLS
- if peertube choose hls over mp4 files, it only shows the definitions available on HLS, not the one available as video files.

**Comment by vincib** [comment]
(I guess we will disable HLS on this instance until we found what's happening)

**Comment by Chocobozzz** [comment]
In `Administration` -> `System` -> `Jobs` -> `video-transcoding`, what jobs are completed or failed with `videoUUID: c249320b-5263-4b2b-b1e8-14d07403079c`?

Because for https://video.lqdn.fr/videos/watch/c249320b-5263-4b2b-b1e8-14d07403079c, HLS generation seems to have failed.

**Comment by vincib** [comment]
"level":"error","message":"Cannot execute job 3328 in queue video-transcoding."

"payload":{"type":"new-resolution","videoUUID":"c249320b-5263-4b2b-b1e8-14d07403079c","resolution":480},"err":{"stack":"SequelizeUniqueConstraintError: la valeur d'une clé dupliquée rompt la contrainte unique « video_file_video_id_resolution_fps »\n    at Query.formatError 
"sql":"INSERT INTO \"videoFile\" (\"id\",\"resolution\",\"size\",\"extname\",\"infoHash\",\"fps\",\"metadata\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *;"},"timestamp":"2020-08-29T14:15:59.455Z"

I didn't paste the entire log, but it seems that we have an inconsistency between the database and the files in the filesystem?

**Comment by Chocobozzz** [comment]
Thanks. So there is a bug when you re run webtorrent transcoding. I'll fix that.

You can try the `--generate-hls` option: `sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v` because we support re run HLS transcoding.

**Comment by vincib** [comment]
I just launched the re-transcoding of everything, and added --generate-hls. we'll see. Thanks Chocobozzz!

**Comment by vincib** [comment]
okayy, we still have the issue after a retranscode for some videos. But those have their original broken it seems : 

this one : https://video.lqdn.fr/videos/watch/ac4db656-3662-4072-8b75-a4866b7a3c81 have a 720p file whose duration seems to be 53" instead of 5'14".

so we reuploaded it on our peertube upgraded to 2.4.0, having a ffmpeg 4.3.1-static

it's here (unlisted) https://video.lqdn.fr/videos/watch/1b97f9ea-a616-4d99-8965-5ddea43d6ae1 and we have weird issues : 

The counter says 3"08 instead of 5"14, but the metadata below says 5"14... and we can't seek after 3"08. 

the 720p file in storage/video is 5"09 long, and the 480p is .. .3"08 

no idea where to start searching ...

**Comment by vincib** [comment]
okay, we re-re-uploaded the same original using an upload via URL, and not a FILE upload, and it ... worked pefectly :/ 

as of now I suspect that FILE upload + NFS storage is the issue. will test other stuff and tell you

**Comment by Chocobozzz** [comment]
It's weird that you don't gave ffmpeg errors in your jobs panel or logs :thinking:

**Comment by Chocobozzz** [comment]
Closing this issue. Feel free to comment, we can reopen.
