### ISSUE TITLE
Cert didn't renew automatically

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3161]
**What happened?**

Received an email from Let's Encrypt Expiry Bot.

> Let's Encrypt certificate expiration notice for domain "peertube.sunknudsen.com"

**What do you expect to happen instead?**

Somehow, I thought the cert would be updated automatically.

Just looked at the [docs](https://docs.joinpeertube.org/#/install-any-os?id=webserver) and see the following.

> Remember your certificate will expire in 90 days, and thus needs renewal.

Copy that! May I suggest making this a little more explicit and perhaps publishing the steps to renew the cert alongside the warning?

I initially ran `certbot renew` which resulted in the following error.

> Problem binding to port 80: Could not bind to IPv4 or IPv6

Then, I ran `systemctl stop nginx` and `certbot renew` and it worked.

I don't remember if I had to run `systemctl start nginx`.

**Steps to reproduce:**

1. Install PeerTube following steps on https://docs.joinpeertube.org/#/install-any-os.

2. Wait for cert to expire.

**Additional information**
* PeerTube version or URL: 2.4.0
* Browser name/version: Firefox 80.0.1
* NodeJS version: v12.18.2

**Comment by Chocobozzz** [comment]
Hello,

I'm not a certbot expert but I think there is a cron that automatically update your let's encrypt certificate :thinking: 
Anyway feel free to create a PR to improve the current documentation :)

**Comment by paulbernhard** [comment]
Hi,

this might be out of date but i just ran into the same issue, stating `Problem binding to port 80: Could not bind to IPv4 or IPv6.`. The [Certbot User Guide on Renewing certificates](https://certbot.eff.org/docs/using.html#renewing-certificates) mentions a solution using `pre-` and `post-hooks`. You can thus automatically stop and start your server, in this case nginx, using:

```bash
sudo certbot renew --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"
```

Furthermore, if running systemd, you can create a renewal service and a renewal timer to renew certificates periodically:

```
# in /etc/systemd/system/certbot-renewal.service

[Unit]
Description=Certbot renewal

[Service]
ExecStart=/usr/bin/certbot renew --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"
```


```
# in /etc/systemd/system/certbot-renewal.timer

[Unit]
Description=Timer for Certbot renewal service

[Timer]
OnBootSec=300
OnUnitActiveSec=1w

[Install]
WantedBy=multi-user.target
```

The `certbot-renewal.timer` will call the `certbot-renewal.service` once per week. In order to get the timer running, use:

```bash
$ sudo systemctl start certbot-renewal.timer # starts the timer
$ sudo systemctl enable certbot-renewal.timer # enables the timer on system boot
```

To check the logs of the `certbot-renewal.service`:

```bash
$ sudo journalctl -u certbot-renewal
```

**Comment by cartossin** [comment]
So sure, you can mod your cron job to stop nginx every time, or you can make a very minor modification to the certbot configuration and it will work just fine with peertube. I regard this as "the right way" to fix it.

The peertube docs tell you to set up a cert with authentication as "standalone" which means certbot will be its own webserver for the authentication to prove domain ownership. This fails if nginx is running on port 80.  The alternate authentication method is "webroot" which means there is a webroot in nginx that certbot can write files to without stopping nginx.  Peertube's template design allows for this.  So if you look at the "anyOS" guide, you will see where they tell you to edit:

`/etc/letsencrypt/renewal/your-domain.com.conf`

Edit this file as described in the peertube docs.  Change standalone to webroot and add the webroot path:

`webroot_path = /var/www/certbot`

next create that directory:

`sudo mkdir /var/www/certbot`

Next if you still have certs up for renewal, give it a shot:

`sudo certbot renew`

It should renew properly.  In my case, the cron job was already working, but it was only failing due to nginx running, so you probably do not have to look at cron.
