### ISSUE TITLE
Feature Request:  Data limits for private and unlisted

### ISSUE THREAD

**Issue by GORF-Official** [Chocobozzz/PeerTube#3226]
I don't want to set limits for daily or total data but I am experiencing problem where I have people uploading their entire youtube channel, 500 gb and making all videos private.  They just want a place to store all their videos so if they kicked off of youtube they can easily be up and running again.  Good for them, bad for us. We are just paying to store all their content without any content.  

Would be great if we have a place in settings where we could specifically set limits for private and unlisted data.  Thanks!

**Comment by test2a** [comment]
Wouldnt a user limit be sufficient ? Does keeping videos as private bypass storage or daily limits ?

**Comment by JigmeDatse** [comment]
I think the issue is not wanting to set limits, but having an issue with having private/unlisted videos which are using a big amount of the upload bandwidth/storage. I'm not really sure if there's a reasonable solution for this.  It feels like it could be a plugin thing?  It seems such an edge case.  

Though...  Only allowing public videos might be a solution, though I find that a little odd.  I could want an unlisted/private video because I want to upload something, but don't want to make it public "yet".

**Comment by Chocobozzz** [comment]
Hello,

We don't want to create another limit option in PeerTube. Please use the built-in user quota, or develop a plugin that remove unlisted and private privacies or that limit videos uploaded in these privacy settings.
