### ISSUE TITLE
Allow all ffmpeg video format if transcoding is enabled

### ISSUE THREAD

**Issue by dedesite** [Chocobozzz/PeerTube#326]
As PeerTube use ffmpeg to transcode videos, it should be possible to upload a video with any format supported by ffmpeg.

So, if transcoding is enable on the server, the file selector should not exclude file extensions like `.avi`.

**Comment by Anton-Latukha** [comment]
Yeah. Since FFMpeg abstracts really great the media containers.

==== Outro

<sub>I mostly use MKV, because it is the most flexible format for me.
MP4 has only a small set of allowed video, audio codecs (and even smaller supported set of codecs, applications expect standard MP4 codecs), has only it's own subtitle standard, and a smaller set of possibilities. And tooling. Comparing to open MKV and MKVToolNix.</sub>
<sub>
There are many cases when multimedia content can not be losslessly remuxed to MP4, due to container not supporting formats and requires do a lossy transcoding to pack them in MP4.</sub>
<sub>
That is why, for example, I use MKV.</sub>
<sub>
Also Matroska is a great streaming container itself. nginx has matroska streaming from the core for years now, browsers does not support it. But browsers support the WebM, which is the profile of Matroska.
</sub>

====

Since FFMpeg is a polyglot that can abstract containers and stream codecs, it is great to leverage it's possibilities, convert any type of incoming media into the target.

**Comment by PhieF** [comment]
I can confirm that .mov works perfectly here, after adding it to constant.ts 

some cameras (canon on my side) only make .mov

**Comment by Jorropo** [comment]
@rigelk @Chocobozzz I'm working on, you can add in progress and assign to me :wink:

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/14e2014acc1362cfbb770c051a7254b156cd8efb
