### ISSUE TITLE
More detailed space analisys and management

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3294]
With Peertube 2.4.0 administrators see only account used space, and this information rounded to "GB"
My feature requests about this:

- Use binary suffixes to have precise idea of space and make easier to do personal calculations (MiB, GiB, TiB)
- Scale unit as needed (few MiB, more GiB, many TiB) and use 1 decimal digit when number is below 10 (9,5 GiB 11GiB 56GiB 900GiB 1,1TiB) to fine grain.
- Report total Peertube instance space (used/available) at administrator's dashboard or system information. Also total number of videos (local/cache), minutes length, stored/encoded files.
- Administrators should be able to see spaces used by a single video: Whole video and per each video recodification/resolution. Calculate and show kbps of each file/recodification. Video owner to see this too.
- Administrators should be able to see what files/resolutions are stored for each single video, and each one's format (webm-vp9-ogg / MP4-mpeg4-aac / aac). Video owner too.
- Same summary as whole instance (space/files/minutes) should be shown at user accounts list.
- A channels list should be manageable with their owner and space summary. Users should have their own channels list with same features.
- A single video storage should be editable (by owner too), for example, removing one of its files/resolutions and leave others, and commanding it to be re-encoded to a lower resolution or different format.

**Comment by test2a** [comment]
this is a super nice request. we already have instances page where stats are collected. currently the stats page shows total storage of 93.28TB and videos count of 243,046. knowing what is the most space efficient, bandwidth efficient format, and also what format is generally seen by users because that way we can take active decisions in reducing transcoding resolutions. 
think of it in this way, if we find out over such a large demographic, say 720p60fps is not used as 720p30 fps, we could decide to skip that resolution and save considerable space and other benefits. 
this is a cool request and i second this fully

**Comment by rigelk** [comment]
> Use binary suffixes to have exact idea of space an ease personal calculations (MiB, GiB, TiB)

Why is that a more "exact idea of space" and why does it "ease personal calculations"?

**Comment by narcisgarcia** [comment]
> Why is that a more "exact idea of space" and why does it "ease personal calculations"?

Fixed phrases

**Comment by narcisgarcia** [comment]
Please, label this as Feature request.

**Comment by rigelk** [comment]
@narcisgarcia there are multiple requests in your demand ; please split them. I tagged this issue as discussion to triage them here first.

**Comment by narcisgarcia** [comment]
> @narcisgarcia there are multiple requests in your demand ; please split them. I tagged this issue as discussion to triage them here first.

Done.
