### ISSUE TITLE
Improve UX around playlists

### ISSUE THREAD

**Issue by Nodja** [Chocobozzz/PeerTube#3298]
Let me preface by explaining how I'm using peertube:
Due to the recent copyright troubles around twitch/youtube, I've been using a semi-private peertube instance to archive twitch streams. I've been using the playlists feature to group the streams together, so all streams of one game are neatly packed. It's been working well but there's some minor issues, in no specific order:

1. Stream playlist url's are not idempotent.
The url seems to be of the format /videos/watch/playlist/\<playlistid\>?playlistPosition=1 for the first item of the list, in this example the video that's on position 1 can change making old links confusing. Youtube seems to solve this by actually pointing to the video id instead of position.

2. Cannot re-order playlist position on channel page. 
Playlists are ordered by when they were created, but sometimes you want a different order, specially when you have dozens of playlists and want some to be more prominent. I've worked around this issue by connecting to the database directly and changing the createdAt fields to be in the far future. So certain playlists are always "pinned" to the top of the list.

3. Allow any relative url in the landing page configuration option.
In my case I wanted to change the landing page to be the url for the playlists on my channel. I've worked around this by editing the value using inspect element. But I think it would be useful for other instance admins.

4. There's no standalone playlist view page.
There is /my-account/video-playlists/\<playlistid\>, but that's only visible to the playlist author. The description field for example is not visible anywhere to anyone that doesn't own the playlist. I'd like to use this field to show notes about the videos on the playlists. The links on the channel page should link to this page.

Thank you for your time and for helping keep the internet open.
edit: markdown ate my \<\>

**Comment by test2a** [comment]
i have a private playlist on an instance with the url
https://devtube.dev-wiki.de/my-account/video-playlists/8971d89b-d828-4de6-aaae-1a9efd60a725

one of the videos inside is  listed here
https://devtube.dev-wiki.de/videos/watch/playlist/8971d89b-d828-4de6-aaae-1a9efd60a725?videoId=ffc3e8b5-d97d-408c-9285-9d7ba0ba59a0&resume=true
and on this instance the video is this link
https://devtube.dev-wiki.de/videos/watch/ffc3e8b5-d97d-408c-9285-9d7ba0ba59a0

why do you say peertube is not using videoid when it clearly is? what is the version on your instance?

2. you "CAN" reorder videos in a playlist. just drag the video number. i just tried and it worked for me.

3. you can have all public playlists in your account in this page. 
https://devtube.dev-wiki.de/video-channels/chrisweredigital@share.tube/video-playlists

**Comment by Nodja** [comment]
I'm using 2.4.0 docker.
I can't access that playlist with either link, if that method works, it's not the one that shows up when users view playlists, or press right-click copy url under 2.4.0.

2. It's not about ordering videos in a playlist. But ordering playlists in a channel.

3. I know that. Under Administration -> Configuration -> Basic Configuration, there's a `Landing page` option. It sets the default router location for the instance, I have mine set to my main channels playlists by manually changing the html.

**Comment by test2a** [comment]
@Nodja here
https://devtube.dev-wiki.de/video-channels/johnathana/video-playlists
this should work
https://devtube.dev-wiki.de/videos/watch/playlist/1c57304d-d95e-45f1-ba71-a0b3735d2f36 this is the first playlist and the playlist page also shows second playlist
https://devtube.dev-wiki.de/videos/watch/playlist/1c57304d-d95e-45f1-ba71-a0b3735d2f36?videoId=7bbe1d5b-2884-49a0-85f8-ff2166f2e32f
this is the video url in opening the first playlist. as you can see, it has videoid which points to the video 
https://devtube.dev-wiki.de/videos/watch/7bbe1d5b-2884-49a0-85f8-ff2166f2e32f
and as you can see, the videoid is same, meaning it takes the videoid from the video and NOT playlist position
>Stream playlist url's are not idempotent.
The url seems to be of the format /videos/watch/playlist/<playlistid>?playlistPosition=1 for the first item of the list, in this example the video that's on position 1 can change making old links confusing. Youtube seems to solve this by actually pointing to the video id instead of position.

you just said that here. videos in a playlist show playlist position and not videoid.

yes, in the page https://devtube.dev-wiki.de/video-channels/johnathana/video-playlists i can see two playlists but i dont know how to reorder them yet. so if i had 100 playlists and wanted to sort them in a particular way as you are asking in the second comment, that is probably not possible today but everything else is almost possible

**Comment by Nodja** [comment]
It seems 2.4.0 started using playlist position instead of video ids for playlists. 

From the release notes [here](https://github.com/Chocobozzz/PeerTube/releases/tag/v2.4.0)
> Use playlistPosition URL parameter for playlists instead of videoId to set the current playlist position

It's not a big deal, but some playlist links will be ruined if the order is changed/videos get added at the beginning. 

I tried manually using videoId instead of playlistPosition and it didn't work. I prefered the videoId method better, the only con being the huge urls.

**Comment by test2a** [comment]
yes. sorry my bad

**Comment by Chocobozzz** [comment]
Hello,

> Stream playlist url's are not idempotent.
The url seems to be of the format /videos/watch/playlist/<playlistid>?playlistPosition=1 for the first item of the list, in this example the video that's on position 1 can change making old links confusing. Youtube seems to solve this by actually pointing to the video id instead of position.

The reason is that we can now have the same video multiple times in a playlist. So we could not use the video uuid anymore.

> 2.

I created an issue: https://github.com/Chocobozzz/PeerTube/issues/3314

> 3.

I created an issue: https://github.com/Chocobozzz/PeerTube/issues/3315

> 4.

See https://github.com/Chocobozzz/PeerTube/issues/2672

Please in the future, create 1 issue per idea/feature request. It's easier to track and to maintain.
