### ISSUE TITLE
Ability to know how many MB are downloaded from the server or peers

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#3384]
**Describe the problem to be solved**

When watching a video, I would like to be able to know how many megabytes are downloaded from the server and/or from peers.
So we could estimate how efficient is the P2P mechanism.

**Describe the solution you would like:**

When hovering with the mouse the Download/Upload/Peers part of the player, I would love to have « Total Downloaded » separated in « Downloaded from the server » and « Downloaded from peers ».

**Comment by Poslovitch** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/videojs-components/p2p-info-button.ts

It splits between P2P & HTTP. But isn't the server considered a "Peer" when using P2P? If so, how could we distinguish the server from other peers? Would `PlayerNetworkInfo` need to be reworked?

**Comment by rigelk** [comment]
> https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/videojs-components/p2p-info-button.ts
> 
> It splits between P2P & HTTP. But isn't the server considered a "Peer" when using P2P?

@Poslovitch It is a peer, using webseed. Just checking the peer’s IP matches the resolved IP from the origin server domain name should be enough.

**Comment by Poslovitch** [comment]
Okay, I *might* work on that, but I'll have to dig deeper into PeerTube and learn a few things first.
Thanks for your answer @rigelk.

**Comment by Poslovitch** [comment]
@rigelk I found this NodeJS lib (https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback)
Is it something I would be allowed to add to the dependencies (package.json) ?

**Comment by rigelk** [comment]
@Poslovitch you are looking at the NodeJS standard library :upside_down_face: But please check the API exists in all ranges of NodeJS supported by PeerTube.

**Comment by Chocobozzz** [comment]
Webtorrent player does not have the info peer VS HTTP: https://github.com/Chocobozzz/PeerTube/blob/9eccae74c844f09e9e3483db623fea00e0562365/client/src/assets/player/webtorrent/webtorrent-plugin.ts#L489

But our HLS player has: https://github.com/Chocobozzz/PeerTube/blob/ec903c010ecc54ec2acad0bf2cf10e7fbf6a0fa2/client/src/assets/player/p2p-media-loader/p2p-media-loader-plugin.ts#L155

Our webtorrent player is in maintenance mode, so it's fine if we only implement this issue in the HLS player.

**Comment by Poslovitch** [comment]
> please check the API exists in all ranges of NodeJS supported by PeerTube
> I’m curious though: what are you planning to do server-side to adress what seems like a client-side computation?

@rigelk According to the docs, this lib exists nearly since the inception of NodeJS. I guess that means it's supported by PeerTube (which, afaik, is >= 10 and < 13, right?)

I hope I'm not wasting your time on that - I sort of use PeerTube as a learning/practicing project to learn TypeScript and Angular (I've only used "*vanilla*" JS so far) -.

Here's what I want to do, based on what you suggested me:
* Modify `PlayerNetworkInfo` to add `p2p.downloadedFromPeers` and `p2p.downloadedFromServer` (thus removing `p2p.downloaded`, as it could be easily recalculated by the client)
* Find where the P2P is handled (here? https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/p2p-media-loader/p2p-media-loader-plugin.ts)
  * **Get the hostname of the instance (how?)**
  * Resolve the hostname of the instance through `dns.js` to get the IP
  * **Check if the IP of the server is the same as one of the peers**: if that's the case, then increment `p2p.downloadedFromServer` instead of `p2p.downloadedFromPeers`
* Tweak the `p2p-info-button.ts` to make use of these new fields.

Sadly, the things that are in bold are those I currently don't know how to do.

However, I've noticed this line:

https://github.com/Chocobozzz/PeerTube/blob/a3f1595f791e3084398f983847c4bac43498a541/client/src/assets/player/p2p-media-loader/p2p-media-loader-plugin.ts#L120

Would `this.options.redundancyUrlManager` contain the list of the "peers" I'm looking for? Its name says otherwise ("redundancy"), but it contains a list of strings (urls? IP addresses?), so I might be on the right path.
Would I therefore have to add a method to https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/p2p-media-loader/redundancy-url-manager.ts in order to retrieve them?

**Comment by Chocobozzz** [comment]
The p2p-media-loader plugin already gives you appropriate stats: `p2p.downloaded` represents data downloader from other peers (and not from an HTTP endpoint). Then you don't need to do DNS requests.

So just update `PlayerNetworkInfo` to add a `source: 'webtorrent'  | 'p2p-media-loader'` field, and in `p2p-info-button.ts` adapt the output depending on the source field: if it is `webtorrent`, then keep the same output. If it is `p2p-media-loader`, you can me more precise.
