### ISSUE TITLE
Source maps in production

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3410]
**Describe the problem to be solved**
There's no source maps provided in the production build. This means that it's not easy to debug, let users check the log or monitoring errors with tools like Sentry and New relic.

**Describe the solution you would like:**
Full featured source maps in production! Lines and columns to original source.

**Describe alternatives you have considered**  
`ng build ... --sourceMap=true`

**Comment by Chocobozzz** [comment]
The thing is that some people complain about the release size, so adding debug files... And we don't want to create 2 different builds.

**Comment by kontrollanten** [comment]
I see. What's the arguments against big release size? I understand that the JS files sent to the users should be as small as possible, but huge source maps shouldn't harm anyone? Or is it the build time?

A possible solution would be to read arguments from the npm commands, so that `npm run build:client -- --sourceMap=true` will send the sourceMap param to `ng`. But it looks like that solution is conflicting with the way `analyze-bundle` param is handled.

I think it would be really valuable to build source maps as a default behavior, since it will make it easier for developers to debug and contribute to PeerTube.

**Comment by kontrollanten** [comment]
A more clear example about how this would be useful. We're using Sentry to monitor client errors, but since there's no source maps it's hard/impossible to determine where the errors come from. But yes, the release file will be thrice as big (316M currently). Can we create two release files with one build? One of the release files just filters out all *.map files. I'd happy to create a PR for that.

**Comment by Chocobozzz** [comment]
I agree that we should put in the release the source map, but it requires too much space (1.3GB instead of ~400MB).

I think I can add a `tar.xz` release containing source map but it requires for me to do 2 builds when I release PeerTube + adaptations of the `release.sh` script. I'll see if I have time to do it.

Anyway, I updated the script so you can use `npm run build -- --source-map` to build the client with source maps. And the nightly build will include them.

See https://github.com/Chocobozzz/PeerTube/commit/29f148a61381727a432c22a71c7a2b7cc23d9c9e

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/cdce5af7fcf28caa9bc95a6d7342163815dc8cfc
