### ISSUE TITLE
Resume video imports

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3456]
**Describe the problem to be solved**
I do not know in the case of many, but at least my internet for policies of my country, restrictions ..etc and ..etc, my speed is very, very limited.
What does this have to do with it?
That importing YouTube example videos is a fiasco, because as the internet is unstable (that is, it is due to lapses, or schedules) so to speak, 90% of imports give me failure

**Describe the solution you would like:**
I know that this may be something that only affects me
So, a possible solution, they might tell me how to change the import parameters, so that if the import of a video is at 50% and there is no internet, it remains stored until it finds the internet again. If not, you have to start the download process again.  :(

**Comment by AnonymousWebHacker** [comment]
If the videos fail to import this happens      https://github.com/Chocobozzz/PeerTube/issues/3834

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately it would be too complex to resume uploads and not cleanup failed imports. I suggest to open an issue on youtube-dl repository instead, to handle unstable internet connections so the import does not fail immediately

**Comment by drzraf** [comment]
Could we please reopen?

At least to either improve documentation, provide scripts or workarounds.


Failed imports are delicate. I have a lot of "Pending" imports which are stuck in **pending** state (I guess the job-runner is ignoring them for some reason), and some others which were simply canceled.

In both cases, I end up with an inconsistent situation (even if yt-dlp was fixed since then).

It'd be nice to:
1. be able to filter import jobs by state
2. (re)trigger the import job when state is "cancel" or "pending"
3. Understand why a job could be both "pending" and disregarded by the job-runner. (db/tables/state at stake)

If 2. is not possible from the UI, please explain why (from a database/state management perspective), because a SQL alternative (or a node script) would be handy as well.

**Comment by Chocobozzz** [comment]
> Understand why a job could be both "pending" and disregarded by the job-runner. (db/tables/state at stake)

Please create an issue with a specific import example and server logs to understand what happened. This case (pending import not attached to a job) **must** not happen.

> be able to filter import jobs by state

Implemented in https://github.com/Chocobozzz/PeerTube/commit/1bd9990013f0a09794d32460cbdc4d32e6924915

> (re)trigger the import job when state is "cancel" or "pending"

Implemented in https://github.com/Chocobozzz/PeerTube/commit/a1b60d7403e818fa71086fc259959814ddcba644 for cancelled jobs

**Comment by drzraf** [comment]
What SQL, for a given PENDING import (ID [how to get it]) would provide the necessary state information to be pasted here?
