### ISSUE TITLE
Docker image - missing ENV

### ISSUE THREAD

**Issue by Saddamus** [Chocobozzz/PeerTube#3482]
Hello
After changing docker image path from `chocobozzz/peertube:v2.1.0-buster `to `chocobozzz/peertube:v2.4.0-buster` im getting the following error:
`Error: Configuration property "database.ssl" is not defined `
Looking to your git repo, it looks like this key is missing on your env files, could it be that docker image has been build from newer sources than those that are present on git ?
Can you please provide me with the right ENV variable that sets this key ?
Is there anything else to update while changing image version ?

**Comment by Chocobozzz** [comment]
It's weird, because at startup peertube should copy the default configuration file: https://github.com/Chocobozzz/PeerTube/blob/release/2.4.0/support/docker/production/docker-entrypoint.sh#L10

Could you check this file was added at startup? And check this env variable is set in the peertube container: https://github.com/Chocobozzz/PeerTube/blob/release/2.4.0/support/docker/production/Dockerfile.buster#L36

**Comment by Saddamus** [comment]
I have added missing part (ssl) on  custom-environment-variables.yaml 
![image](https://user-images.githubusercontent.com/7191172/102803036-e7163300-43b7-11eb-821a-47c5ab022ddd.png)
now it works. Thank your for your attention.
