### ISSUE TITLE
Allow users who do not want to expose their IP address to watch videos

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#355]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

When prompted about using PeerTube will share my IP address with the world, I should be able to disagree and still be allowed to watch the videos. If PeerTube is used to broadcast videos that have been ban in a given country, users from such a country might not want to reveal their IP addresses, while people in other countries might be willing to provide their bandwidth.

This could be an extra setting for administrators.

* **What do you see instead?**

When prompted about allowing to share my IP address, I won't be able to watch the video if I click Cancel.

**Comment by Chocobozzz** [comment]
We don't have this prompt anymore :)

**Comment by Chocobozzz** [comment]
People that don't want to expose their public IP address to the world should use a VPN or Tor. Disabling P2P in PeerTube would just add a false feeling of privacy.

**Comment by rigelk** [comment]
@Chocobozzz it's more a problem of being exposed to the swarm. You may trust the server with your IP but not the swarm of users that watch the same video as you. Putting a user setting to fallback to HTTP should do the trick.

Again, fifty shades of privacy :)

**Comment by Chocobozzz** [comment]
> You may trust the server with your IP but not the swarm of users that watch the same video as you.

There are many other actors between you and the PeerTube instance. And when https://github.com/Chocobozzz/PeerTube/issues/123 will be implemented, it will be hard to trust every server on which you will request a chunk.

**Comment by Chocobozzz** [comment]
Anyway, see https://github.com/webtorrent/bittorrent-tracker/issues/271 to discuss about peers privacy in the tracker.

**Comment by hambibleibt** [comment]
> People that don't want to expose their public IP address to the world should use a VPN or Tor.

That would be better, yes. But not everyone is having access to that knowledge or the needed time to learn how to use it. And because they can't, those that can need to think how to protect them. 

> Disabling P2P in PeerTube would just add a false feeling of privacy.

No, it could help to educate about pricacy. Befor the video starts, people could be asked if they want to use p2p and with what implication it comes with. There could be also a pointer that not using tor/vpn gives information on ones ip doesn't matter if one uses p2p or not, with a link to further information.

This would helps to:
- raise awarness on that topic
- protect people from being identified through the p2p system

Example why p2p brings extra risk, comparing to just watching it from the server: 
- you protest against a company
- the company has hired militias
- you upload a video targeting the company on peertube
- your supporters watch it, but also the militias and by that they find out who your supporters are so they can target them

there's of course still the option that they could identify people watching the video even if p2p is off, but it requires way more effort and skills.

I do not see any downside of adding such, only benefits. 
Not implementing it, I do only see downsides, but no benefits.

**Comment by sj-on** [comment]
So, does this mean I should use a VPN while watching videos on  PeerTube instances?
