### ISSUE TITLE
Seperate "weighing" mechanism for Collaborative Filtering / Curating / Upvoting of Global Search

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#3553]
**Describe the problem to be solved**

I love the idea of a global Search over the Vidiverse as it is implemented now. While its great that you can run your own indexing server, that still leaves you with the burden of sifting through a big amount of instances to include or not include. I would like to see an additional mechanism on top of the search funtionality: Global indexing servers as they are now, that do no or little filtering, but have an "overview" of the existing instances (already exists, "Sepia Search") 

but on top of that small "curation" servers which basically just hold an individual upvoting / downvoting or collaborative filtering mechanism for videos and will weight and filter the global search results.

The problem with Peertube (from my personal perspective) is that there is a significant amount of
- low (content) quality videos
- politically problematic (right-wing, conspiracy etc)
- copyright violating
- nsfw

content. I really dont want to see most of that stuff and right now i think its is not sufficiently possible to use "Global Search"  and still get "high quality" results.

Example: Do a search for "ARD" (akronym for first German National TV) on Sepia Search - you will JUST get conspiracy content for the first dozen of results, a lot of it from politically rightwing sources (i.e. KenFM)

**Describe the solution you would like:**

A seperate mechanism that allows all videos on the Vidiverse to be up/downvoted, this should obviously be an individually configurable server, since someone who just wants to see nsfw or conspiracy videos might want to use it too - and they should - i just dont want to see the same videos they want to see.

**Comment by omac777** [comment]
I believe Sepia Search should be clearly indicated on JoinPeerTube's home page.
Sepia Search should be recommended as first-place wanna-be peertubers should go.

I do agree with @tilllt "Sepia Search" results being not necessarily relevant to what we are searching for.
More tags need to be used to return truly relevant results.
No results should be returned on a single tag word for the search of burdening the search engine.
A single tag word search currently brings up so much noise and irrelevant content as @tilllt observed with simply searching for the one tag word "ARD".  @tilllt is partly to blame for that since he could have provided a more tag words to narrow the search scope.  
More results should be based on previous search results done by other users for example MFU (most frequently used) and MRU (most recently used) tag words and their results.

Most appropriate to this discussion is the capacity to suggest other tag words most closely/frequently associated with currently requested tag word.  For example Microsoft/Google have a capability which follows what you type in the search text box on their search page.  This capability provides auto-completion suggestions for the word you are typing followed by other words frequently associated with that word.

IMHO the Sepia Search engine is key to increasing the popularity of  PeerTube.  If Sepia search does not rise to the challenge to provide what the peertube visitors expect to find which is relevant results, then peertube visitors will continue to go to Google/Bing/Yandex/DuckDuckGo to get truly relevant results.

I disagree about up/down-voting of content since moderators hold too much power and delete uploaders entries by doing so.
Reddit has been a negative experience for me when they moderate/downvote/delete participants' entries.  Everyone's opinion matters.  It's up to each of us to filter what we want to see and what we don't want to see.
All content holds value except for spam.  Determining what is the spam is a very important part of keeping the noise level down.
Determine those participants injecting spam and blocking their accounts is also a key capability.
Spam radar capability identifying spamming and making them known and de-listing them.

Thank you for listening.

**Comment by tilllt** [comment]
The thing is:

- there needs to be filtering
- the criteria for filtering are always subjective
- "tags" will not help in this context, i am sure if i would add the the tag "conspiracy theory" and "tinfoil hat content" to KenFM shows, i would start a very ugly flame war. But thats precisely how i see them and a lot of other content on peertube. 
- so the only solution is to create filter bubbles which can WEIGHT the search-result differently according to their views.
- i would call my "weighing" server "No Fanatics and Tinfoil Hats" and downvote all KenFM stuff and similar stuff with a group of likeminded people so i will never be bothered by that stuff again.
- if you on the other hand love KenFM, you could make your "KenFM is the best" weighting server and upvote KenFM and other conspiracy stuff. The advantage: you dont have to use my sever, i dont have to use yours, we could still both use Sepia Search.

I saw you are from Canada, so ARD is similar to what would be CBC for you. If searching for CBC returns 20 Pages conspiracy related content and then the first "neutral" result, thats a problem.

**Comment by Chocobozzz** [comment]
Hello,

There is already a upvote/downvote system for videos. If you want us to take them into account when making a search on sepia search, please create an issue on https://framagit.org/framasoft/peertube/search-index

We plan in 2021 to allow admins to create a custom homepage so they can do curation: https://github.com/Chocobozzz/PeerTube/issues/3582

**Comment by tilllt** [comment]
I dont think that a general up/downvote system will solve the problem of "battling" user group interests but i will take my issue to the sepia search repo
