### ISSUE TITLE
Configurable minimum sign-up age

### ISSUE THREAD

**Issue by JasXSL** [Chocobozzz/PeerTube#3612]
Currently when you sign up, you have to agree that you're at least 16 years old. In order to change this, you'll have to edit all the translation files in the deployment.

It would be nice if we could change this value in the settings, since we're working on a shard where you need to be 18+ to join.

I know you can alter it with the custom JS injections, but it feels like a hacky workaround.

**Comment by rigelk** [comment]
Please don't tag your issue title yourself, and use the issue template.

**Comment by Poslovitch** [comment]
I'm working on this.

**Comment by cdauth** [comment]
It's nice that the age can be configured now. However, the minimum age that can be configured now is 1, and I would like to disable any minimum age. This could probably be achieved by allowing setting the minimum age to 0 and editing the checkbox message so that it doesn't mention any minimum age if it is 0.
