### ISSUE TITLE
Custom fields via rest api

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#3667]
**Custom fields via rest api**

@Chocobozzz  Would it be possible to populate custom fields when uploading or importing a video via rest api (https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1imports/post)? 

For example a custom field created by a plugin, like in this example:
(https://docs.joinpeertube.org/contribute-plugins?id=add-custom-fields-to-video-form

**Describe the solution you would like:**

Add custom fields to rest api upload/import/update video

**Comment by geco** [comment]
As an alternative: do rest api plugins exist?

**Comment by Chocobozzz** [comment]
As stated in the documentation:

> PeerTube will send this field value in body.pluginData['my-field-name']

So just send your additional fields value in the `pluginData` field.

**Comment by geco** [comment]
I can't see pluginData into this Api documentation:
https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1imports/post
Can i use it alongside  POST /video/imports rest api call?

**Comment by Chocobozzz** [comment]
> I can't see pluginData into this Api documentation:

Because it's not in the peertube api. I mean peertube sends the request body to your plugin when you registered the `action:api.video.updated` hook. I means you can use the fields you want (`pluginData` field is used by the client, so it's better if you keep the same field). Then, you can use this hook to save things you want (it can be a previously imported or uploaded video).
