### ISSUE TITLE
Plural form markup

### ISSUE THREAD

**Issue by gunchleoc** [Chocobozzz/PeerTube#3791]
I have added some source string discussions on https://weblate.framasoft.org/projects/peertube/angular/gd/ to flag up strings that need plural forms.

I have also asked a few questions for clarification there.

**Comment by Chocobozzz** [comment]
Hello,

I fixed some of these strings in https://github.com/Chocobozzz/PeerTube/commit/2640db3ff1a7ebb2e2bfbae7437c093c14ccfa5c (not yet available on weblate). But unfortunately most of your comments cannot be fixed because the Angular `$localize` tool (used to translate strings in `.ts` components) cannot interpret ICU expressions.

**Comment by gunchleoc** [comment]
Thanks for fixing what is possible :)
