### ISSUE TITLE
Sporadic sequelize timeout error

### ISSUE THREAD

**Issue by manalejandro** [Chocobozzz/PeerTube#3793]
**Sporadic sequelize timeout error**
```
peertube    |   "err": {
peertube    |     "stack": "SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)",
peertube    |     "message": "Operation timeout",
peertube    |     "name": "SequelizeConnectionAcquireTimeoutError",
peertube    |     "parent": {
peertube    |       "stack": "Error: Operation timeout\n    at Timeout._timeout.setTimeout (/app/node_modules/sequelize-pool/lib/Deferred.js:17:25)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)",
peertube    |       "message": "Operation timeout"
peertube    |     }
peertube    |   }
```
**Steps to reproduce:**

1. Use chocobozzz/peertube:production-buster docker image with postgres:11 docker image
2. Wait the timeout

**Additional information**
Peertube container tune:
```
database:
  pool:
    max: 100
```
Postgres container tune:
```
shm_size: '1gb'
    command: >
      -c 'max_connections=100'
      -c 'shared_buffers=512MB'
      -c 'effective_cache_size=1536MB'
      -c 'maintenance_work_mem=128MB'
      -c 'checkpoint_completion_target=0.7'
      -c 'wal_buffers=16MB'
      -c 'default_statistics_target=100'
      -c 'random_page_cost=1.1'
      -c 'effective_io_concurrency=200'
      -c 'work_mem=1747kB'
      -c 'min_wal_size=1GB'
      -c 'max_wal_size=2GB'
      -c 'max_worker_processes=4'
      -c 'max_parallel_workers_per_gather=2'
      -c 'max_parallel_workers=4'
      -c 'autovacuum_max_workers=1'
      -c 'autovacuum_work_mem=128MB'
      -h '*'
```
* PeerTube instance:
  * URL: https://fediverse.tv
  * version: latest chocobozzz/peertube:production-buster docker image
  * NodeJS version: latest chocobozzz/peertube:production-buster docker image
  * Ffmpeg version: latest chocobozzz/peertube:production-buster docker image

* Browser name, version and platforms on which you could reproduce the bug: none
* Link to browser console log if relevant: none
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): default peertube log

**Comment by error10** [comment]
I think my problem is very slightly different but closely related. It likely _is_ the same issue, just presented differently, or at least the same root cause. Thus it probably ought to be posted here in the same issue.

**Describe the current behavior**
Peertube freezes and becomes unresponsive. It no longer serves videos, lives or user or administration data and must be killed and restarted. Only static assets load.

**Steps to reproduce:**

1. Install peertube using "Any OS" directions
2. Upload and watch some videos and lives
3. Wait for it to eventually happen

**Describe the expected behavior**
Peertube shall not freeze but service requests indefinitely

**Additional information**

* PeerTube instance:
  * URL: https://peertube.freetalklive.com/
  * version: v3.0.1
  * NodeJS version: v12.21.0
  * Ffmpeg version: 4.2.4
  * PostgreSQL version 10.15

* Browser name, version and platforms on which you could reproduce the bug: Firefox 86.0
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

Normal service until, for unknown reasons, this shows up in journalctl. Nothing matching is in storage/logs/peertube.log, just access logs. Peertube is frozen at this point and has to be restarted. PostgreSQL continues to operate normally and has no log entries within 12 hours of the event.
```
Mar 01 00:58:56 peertube.freetalklive.com peertube[875]: (node:1016) UnhandledPromiseRejectionWarning: SequelizeConnectionAcquireTimeoutError: Operation timeout
Mar 01 00:58:56 peertube.freetalklive.com peertube[875]:     at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)
Mar 01 00:58:56 peertube.freetalklive.com peertube[875]: (node:1016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Mar 01 00:58:56 peertube.freetalklive.com peertube[875]: (node:1016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Chocobozzz** [comment]
Hello,

If our ORM cannot acquire a connection in the pool, it means that some queries are too long to proceed. Please use the `log_min_duration_statement` PostgreSQL option to find out which queries are problematic

**Comment by manalejandro** [comment]
This happens also without the postgres container options, can it be some constanst.ts timeout? :thinking:

**Comment by frankstrater** [comment]
I'm having the same issue as described by @error10. Instance freezes after around 12 hours with connection timeouts, but everything seems to be running fine.

**Comment by manalejandro** [comment]
Dialect options setting for postgres could be completed with timeout: https://github.com/sequelize/sequelize/blob/main/lib/dialects/postgres/connection-manager.js#L117 in https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/database.ts#L60
```
    dialectOptions: {
      options: {
         statement_timeout: 30000
      }
    }
```
humm :thinking:

**Comment by Chocobozzz** [comment]
We should not have statements that take this amount of time. Have you find these queries?

**Comment by manalejandro** [comment]
> We should not have statements that take this amount of time. Have you find these queries?

Nope but if there are open connections in the pool, you cannot get any more, currently i have 100 connections in the pool in postgres and 80 in peertube, for now it works without problem.

**Comment by manalejandro** [comment]
@Chocobozzz hello, you are invited this afternoon at 19h UTC + 1 in [fediverse.tv](https://fediverse.tv) to see how the sequelize configuration works with acquire: 60000ms and not 30000ms by default :wink:

**Comment by rigelk** [comment]
@manalejandro it would be better writing an article or submitting a PR IMHO
