### ISSUE TITLE
Default use HLS with P2P when disabled transcoding.

### ISSUE THREAD

**Issue by meredith2u** [Chocobozzz/PeerTube#3833]
**Describe the problem to be solved**
Can not use HLS with P2P mode when disabled transcoding option.
I know that the preset will only use webtorrent mode.

**Describe the solution you would like:**
Add feature that Disabled Transcoding default use HLS with P2P option, then peertube will not perform transcoding but will convert to HLS playable format.

**Comment by Chocobozzz** [comment]
Unfortunately this is not possible. We had to disable the quick transcoding feature with HLS only because some players could not play the video (see https://github.com/Chocobozzz/PeerTube/issues/3502 and https://github.com/Chocobozzz/PeerTube/commit/236841a1d73a1b67541537f0017856848ad43b79).

I'm not sure if it's a ffmpeg bug or a safari bug, but until this is fixed we cannot re-enable this option.
