### ISSUE TITLE
Build issue on mac 20.2.0

### ISSUE THREAD

**Issue by Rozen10** [Chocobozzz/PeerTube#3859]
`/Users/youssou/PeerTube/scripts/build/client.sh: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
scripty ERR! script failed: '/Users/youssou/PeerTube/scripts/build/client.sh'
scripty ERR! exit status: 2
npm ERR! code 2
npm ERR! path /Users/youssou/PeerTube
npm ERR! command failed
npm ERR! command sh -c scripty "--light"`

I have this error when I run `npm run build -- --light` on mac.

I can reproduce this error when I run `declare -A toto`. The error is `declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]`.

My bash version is 3.2.57

**Comment by Chocobozzz** [comment]
Hello,

Please upgrade bash to 4.0 (using `brew install bash` and https://stackoverflow.com/a/42042459)

**Comment by darnuria** [comment]
@Chocobozzz suggested to my student to edit here https://github.com/Chocobozzz/PeerTube/blame/develop/support/doc/dependencies.md#L285 to add bash. They will make a pr about it. :)

**Comment by darnuria** [comment]
Maybe changing scripts using: `#!/usr/bin/env bash`:  here https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/build/client.sh#L1 can help users because the shell for scripts sometime is not the shell for interactive commands like said in https://stackoverflow.com/questions/6047648/associative-arrays-error-declare-a-invalid-option/43948526#43948526
