### ISSUE TITLE
Disable video download global or for categories

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3872]
**Describe the problem to be solved**
As everyone knows, it is not the same traffic generated on the network, by downloading a video, as the stream (little by little) that makes peertube.
Most users leave the download option enabled, this generates traffic on the network, annoying other users.

**Describe the solution you would like:**
I think there should be an option in the admission of the instance to disable the downloads of the videos globally. In other words, the option to [Allow the download or not] does not appear.

**Describe alternatives you have considered**  
It can be optional to choose by the administrators of each instance, leaving some categories the option of downloads, example [Music Video]

**Comment by Alterak** [comment]
I have already asked this question. And I got tired of constantly disabling this function for each video, because many users do not watch videos on my copy, but simply download my videos to their computer ... This creates a heavy load on the Internet connection.

The developers suggested adding this feature to the profiles, it would be very convenient! If I understand correctly, the "profiles" function is still in development. I would like to hear the answer from the developers.

**Comment by AnonymousWebHacker** [comment]
That is the problem, that direct downloads generate a very large traffic.

I hope they can give us an answer

**Comment by Chocobozzz** [comment]
I think we can create a hook in the download route so you can develop a plugin a use the criteria you want to disable/enable it.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/118e1942e6e968ffb596ded67e79eebe33eeb6e1

**Comment by AnonymousWebHacker** [comment]
tanks men
