### ISSUE TITLE
Find videos that currently have peers (thereby lessening instance load)

### ISSUE THREAD

**Issue by darkenvy** [Chocobozzz/PeerTube#3903]
**Describe the problem to be solved**

Unable to see videos that have more than 0 peers. Encouraging people to watch videos that have peers would lessen stress from instances hosting the video-file. 

**Describe the solution you would like:**

A sort-by option that sorts by highest peer-count
OR
A tab showing videos that have more than 0 peers.

**Comment by test2a** [comment]
I have another idea. Instead of having a separate new view of "actively watching videos", what if we add more to the existing "hot", "views" and "likes" tabs.

What I mean is these videos show results based on their algorithms. My idea is to give "more" preference to videos with more than 1 peer if webtorrent is enabled with p2p and to live streams in their respective algorithms.

So, if a video was top of hot earlier but people have started to watch it again, maybe peers would give it a more higher score making it possible to go to top of results. Same for lives. This would aid in discoverability

**Comment by rigelk** [comment]
> what if we add more to the existing "hot", "views" and "likes" tabs.

Query complexity increases too. This information (how many peers there are per video) is only stored in the tracker, not in PeerTube's database - it is transient data after all.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/3796 could be used

**Comment by darkenvy** [comment]
Is there a way to query a tracker to see what videos have the most views?

**Comment by Bugsbane** [comment]
I have a concern that this could lead to recreating YouTube's issue of videos becoming more popular, just because they're already popular, so that the most popular 5% of creators end up getting 99.9% of all views, mindshare and opportunities on the network.

Surely the better question would be how can we encourage more peers for low peer videos, rather than how can we keep everyone watching the same small handful of videos that are already the most popular on the network?

Personally I'd love to see a separate app which is just a fork of an existing bittorrent app with just a Peertube login and settings for the interface, that basically downloads and shares any videos with certain crieria, eg. videos the logged in user watches that have less than X peers.

**Comment by darkenvy** [comment]
You know, I have thought about this a bit a and I agree with you 100%. However, I would still enjoy a feature, filter or API call that informed me if a video has zero peers or not. (a peercount not needed). I feel like the original spirit underlining my original request is that I would prefer to watch videos that are already being shared by 1+ peers (instead of streaming it from the server directly).

I want to encourage and promote the peer sharing. Definitely not create the problem youtube has. I actually found https://github.com/webtorrent/webtorrent-hybrid from https://github.com/Chocobozzz/PeerTube/issues/122 and see that it is pretty reasonable to create a simple chrome-extension/userscript that sends unseeded videos to a self-hosted headless seedbox. If getting a peercount from a API was reasonable. I guess if it is a userscript, one could always scrape the current page they are on XD.

**Comment by Chocobozzz** [comment]
Thanks for the issue, but it's out of the scope of PeerTube. I think a plugin can be developed to implement your use case though.
