### ISSUE TITLE
Serve video/thumbnails directly from s3 instead of proxying through nginx

### ISSUE THREAD

**Issue by LasersAreGreat** [Chocobozzz/PeerTube#3928]
I see how in the /etc/nginx/sites-enabled/peeretube file it is possible to have nginx fetch video and thumbnails from S3 and serve them to the user. But I would like to have the data go directly from S3 to the user, without nginx in the middle.

For example, when a user loads the front page of my peertube instance, there is a thumbnail:

https://peertube.newsocial.tech/static/thumbnails/3c1a36e9-5214-43ac-8a10-d3a588998ebb.jpg

I would much rather see that rewritten as:

https://MyS3Bucket.peertube.newsocial.tech/static/thumbnails/3c1a36e9-5214-43ac-8a10-d3a588998ebb.jpg

Is that possible?

**Comment by rigelk** [comment]
Yes, you just have to take [the current nginx block for video CDN](https://github.com/Chocobozzz/PeerTube/blob/b70025bfdc5f3d7aa3e827f6cadfa1e21483a038/support/nginx/peertube#L247-L254) and adapt it for thumbnails. It's just rewriting the URL so that the ressource is fetched by the browser at this new location.
