### ISSUE TITLE
Web Interface goal/guidelines - Youtube-like PWA?

### ISSUE THREAD

**Issue by aschaap** [Chocobozzz/PeerTube#3937]
**Parts of the documentation concerned:**

I looked through the contribution section (https://docs.joinpeertube.org/contribute-architecture) and couldn't find anything about goals for the UI, particularly on mobile. Looking through bugs and pull requests, @rigelk appears to have the vision for the web interface to be a PWA https://github.com/Chocobozzz/PeerTube/issues/250#issuecomment-368534840. Is this still the case? And is the goal to mimic YouTube primarily, or are there other considerations/guidelines/inspirations to follow?

**Describe the desired information/correction**

I'd be happy to create a section or update the Architecture page on https://docs.joinpeertube.org/ once the current direction becomes clear.

**Comment by rigelk** [comment]
hi @aschaap,

I don't hold the vision ^^' And since 2018 (the date of the comment you mentioned), things have changed a bit, but not our ressources. That means maintaining and improving upon our PWA is still our approach towards mobile support.

The goal is not to mimic YouTube, but we're happily taking inspiration from their interface ; their design choices are not openly discussed or explained though, so there is a limit to what we can follow. Usually, the differences come down to features we don't have, features we have they don't (like channels/account concepts).
