### ISSUE TITLE
Use "eu" instead of "eu-ES" for Basque locale

### ISSUE THREAD

**Issue by Porrumentzio** [Chocobozzz/PeerTube#3956]
Currently Peertube uses "eu-ES" as locale for Basque language, but Euskara (Basque) is a language and culture present both on Spain and France, legally.
When people set the system language on OSs, they tend to use "eu" local, independently of the country (ES or FR), so it is better to use only "eu"; even more, I would say that it's not change between -ES and -FR, further than maybe date.

So I believe that it's important to set the locale neutral, using only "eu", without country variation.

Source: https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/ef77a37249d4d2961191b7381ca803678767770e#commitcomment-49417489

**Comment by Chocobozzz** [comment]
Hello,

`eu` is an alias to `eu-ES`. Then, the web browser should detect `eu` and correctly displays Basque to the user. We prefer to use the complete locale because most of the time we don't know if there are differences in a specific locale between countries. But it's not important for the user, since we always create an alias for the short locale (see https://github.com/Chocobozzz/PeerTube/blob/develop/shared/core-utils/i18n/i18n.ts#L37)

**Comment by Porrumentzio** [comment]
Also, most of Fediverse software use "eu" locale by default:
Mastodon: https://crowdin.com/project/mastodon/eu#
Lemmy: https://weblate.yerbamate.ml/projects/lemmy/lemmy/eu/
Funkwhale: https://translate.funkwhale.audio/languages/eu/funkwhale/
WordPress: https://translate.wordpress.org/locale/eu/

Other grand projects:
Document Foundation: https://translations.documentfoundation.org/languages/eu/
Common Voice:https://commonvoice.mozilla.org/eu

And also most common GNU/Linux distros use "eu":
Debian: https://www.debian.org/international/l10n/po/eu
Ubuntu: https://translations.launchpad.net/ubuntu/hirsute/+lang/eu
Linux Mint: https://translations.launchpad.net/linuxmint/latest/+lang/eu
Elementary: https://l10n.elementary.io/languages/eu/
Fedora: https://translate.fedoraproject.org/languages/eu/

**Comment by Chocobozzz** [comment]
We use both `eu` and `eu-ES`. I'm not sure where our technical i18n stack can confuse people. Basque is correctly displayed on weblate and our i18n modal, it should also be correctly detected depending on web browser configuration (`eu` or `eu-ES` set) etc.

**Comment by Porrumentzio** [comment]
Okay! If it's that way, also `eu-FR` should be used :)

**Comment by Txopi** [comment]
Hi, I collaborate in the translation to Basque of other fediverse's softwares and other known free softwares. I still haven't decided to start collaborating in the translation of PeerTube.

They are about [1 million](https://en.wikipedia.org/wiki/Basque_language) Basque speakers (source Wikipedia). It has no sense to maintain both `eu-ES` and `eu-FR`. I don't know a sole software doing that.

I think it's usual for small languages spoken in two countries to use a short locale that joins people and makes the most of the translators community. The free softwares listed above shows that's a very common strategy, at least in the case of Basque.

What's the point of imposing the inclusion of one of the countries in the Basque locale if that's not common and it's clear that translators don't want it?

I'm sure that if developers show sensitivity in this issue, translators will answer positively making a good work on Basque translation and keeping it updated over time (if translators feel they have not been kept in mind, some of them probably will loose interest on this translation, I have seen it many times).

**Comment by Chocobozzz** [comment]
> It has no sense to maintain both eu-ES and eu-FR. I don't know a sole software doing that.

We never did or will maintain 2 locales for `eu`. We just maintain one, that's behind `eu-ES` or `eu` **in our code**. I agree that we should only have `eu`, but for historical reason we also have `eu-ES`.

I don't know why you link other software projects (from the fediverse or not): they don't have our history, nor use the same tools as we do. And we have the same URL for Basque than projects that also use weblate: https://weblate.framasoft.org/projects/peertube/angular/eu/ so I'm a little confused.

> What's the point of imposing the inclusion of one of the countries in the Basque locale if that's not common and it's clear that translators don't want it?

Where did we do that? There seems to be a misunderstanding here because I still don't understand what is the issue: OP said PeerTube uses `eu-ES` for Basque which is wrong, since we also use `eu`. Then, the issue raised by the OP (OS configured with `eu` and not detected by PeerTube) does not exist (or this is a bug). We display `Basque` on weblate and on PeerTube, without country suffix, and don't maintain 2 different locales.

Maybe the underlying issue is that we force plugins the use of locales with a country suffix in the API? If yes, I think we can change this behaviour that is not very convenient for developers.

**Comment by Txopi** [comment]
I was talking about locale codes in general. As you know, they have been created and defined to use with many languages, libraries, tools, frameworks, APIs and technologies. PeerTube itself uses `eu`? I didn't know! If that's the case, it really was a misunderstand. I still don't have this clear because I don't understand who or what is OP, sorry.

Let's see what's happens with plugins. You say _"we force plugins the use of locales with a country suffix"_. My questions:

1. Why [this plugin](https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/package.json) use `eo` locale (without suffix) and `eu-ES` locale?
2. So `eo` is OK?
3. It could use `eu` instead of `es-ES` and the plugin would run OK?

I'm sorry for making this obvious questions for you, but right now I'm just a PeerTube user (normal and a bit as administrator) and really don't know the meat!

**Comment by Chocobozzz** [comment]
> It could use eu instead of es-ES and the plugin would run OK?

For now no, but it's the thing I want to fix :)
