### ISSUE TITLE
Not possible to change already uploaded video (Edit of video impossible)

### ISSUE THREAD

**Issue by cb2-dd** [Chocobozzz/PeerTube#4179]
I cannot find a hint in the official user documentation on how to change an already uploaded video... so, imagine the situation: a video link is already spreaded among lots of people but now you realise an error in the cutting of the video, you correct it and want to upload it for the same metadata / the same link... but it does not seem to be possible...

I cannot believe, people should delete the old video and upload the new one by putting the metadata again and loosing the counts of users that have already watched a video... so, there must be a hidden way to replace an old video with a new one...

**Comment by rigelk** [comment]
hi @cb2-dd,

You currently cannot replace the video, only edit its metadata. This is done on purpose: to avoid any possiblity of interactions made for a content being suddenly under a video that is radically different. While your use case is certainly legitimate, there is a possibility for abuse that needs more moderation tools before we introduce such a feature.

See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs for replacing a video as an adminstrator.

Your issue is not new, and has already been discussed at https://github.com/Chocobozzz/PeerTube/issues/1845. You can further detail your use case there, and upvote the issue to help us triage it 🙂
