### ISSUE TITLE
Customize default search sort

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4219]
**Describe the problem to be solved**
When users are searching on our PeerTube site they feel that the search results are presented in a "confusing/unlogical" order.

**Describe the solution you would like:**
The proposed solution from our users is that an order based on views count would be more easy to understand. This can be done manually each time a user is searching, but most of the users don't go that far, they just quit using the search functionality if they feel uncomfortable using it. Therefore it would be great to set a default sort order.

**Describe alternatives you have considered**  
A) Add a setting in the configuration file; `search.sort: 'views'`.
B) Add a hook so that the sort can be changed by a plugin.

**Comment by kontrollanten** [comment]
The current default order, relevance, is based on PostgreSQL's [similarity](https://www.postgresql.org/docs/9.1/pgtrgm.html) function. It seems that when searching for a string that occurs in multiple video names, they're sorted by the videos where the string first occurs, and if multiple videos has the string in the same position the videos are sorted by shortest video name. I can't see how that makes sense from a user perspective, but maybe there's a use case which I haven't thought about?

**Comment by Chocobozzz** [comment]
>  I can't see how that makes sense from a user perspective

The similarity is greater if the target string has a lower length. If we use the search `hello`, it is more similar to `hello world` than to `hello world, how are you?`. Then, it seems to be more logical to display `hello world` first, because more relevant.

I'm opened to improve the current behaviour (maybe using `word_similarity` instead?), but I don't think that changing the default is the appropriate solution.

You're free to change the default sort using plugins (if you need hooks create an issue, I'll implement them).
