### ISSUE TITLE
OpenBSD + Firefox: no video

### ISSUE THREAD

**Issue by sachaz** [Chocobozzz/PeerTube#423]
* **PeerTube version or URL:**
tube.aquilenet.fr
* **Client OS name/version:**
OpenBSD 6.2
* **Browser name/version:**
Firefox 56.0 (64-bit)
* **NodeJS version:**

* **What is the expected behaviour?**
Launch a video
* **What do you see instead?**
Nothing

* **Browser console log if useful (Gist/Pastebin...):**
https://pastebin.aquilenet.fr/?398e921c50ce277d#s02l6kRu+pAPPProNZwUQwovvBvxyVOO2Z/Q4pQZMM4=

**Comment by 22decembre** [comment]
I have an OpenBSD -current (6.3) with Firefox 57.0 64 bits.

When browsing the peertube home page (random instance), I can click on whatever video, it won't redirect me to the video page. If I click, copy link, launch a new tab and paste the URL, it will then produce the home page, blank.

If I launch a web console, it would indeed produce the log above. I have also this:

```
Successfully compiled asm.js code (total compilation time 7ms; not stored in cache (too small to benefit))  
TypeError: asm.js link error: Unable to prepare ArrayBuffer for asm.js use
```

I could get the thing to work. But only when I reload the home page with the web console. Then I can launch a video. But no sound either.

Notice that Chromium on OpenBSD worked great, opposite. No tricks. Just working flawlessly.

**Comment by sachaz** [comment]
merci 22decembre to have well explained and reproduced the bug !

**Comment by bnjbvr** [comment]
Hi! Working on Firefox and asm.js here. First of all, @sachaz please make sure to upgrade your Firefox installation to the latest stable version, otherwise you might be subject to security bugs that have been opened to everyone in the meanwhile. Updates are important.

Second of all, this error might be due to a 64 bits optimization we do on asm.js/webassembly: Firefox requests ~6GB of addressing space (via an mmap, so note they're not actually used, just requested) and then mprotect this addressing space to avoid slow explicit bounds checks.

Either one of the system calls fails, or you have low limits on the memory one single process can request (e.g. using `ulimit` or something like that). I suspect OpenBSD sets such a limit by default, and it might need to be deactivated for asm.js/wasm to work efficiently on Firefox.

A workaround is to go on `about:config`, then set `javascript.options.asmjs` to `false`. I strongly recommend to *not* do it, because it might alter performance on other web apps too, but that would be a workaround to make sure this won't break.

**Comment by sachaz** [comment]
Hi
I confirm that your workaround works, thanks bnjbvr
This issue is still considered as a bug ?

**Comment by Chocobozzz** [comment]
Not on the PeerTube side but maybe you could fill a bug on the OpenBSD bugtracker.

Thanks @sachaz and @bnjbvr
