### ISSUE TITLE
Error: no peer with that to_peer_id

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#4239]
Hello @Chocobozzz , i'm getting the peertube logs full (about 100/minute) of these error messages, i've searched into issues but i can't find something similar. Do you have any idea of what's causing it? I've tried disabling HLS but errors continue.

"stack": "Error: no peer with that `to_peer_id`\n    at /app/node_modules/bittorrent-tracker/server.js:554:41\n    at /app/node_modules/bittorrent-tracker/server.js:364:7\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
"message": "no peer with that `to_peer_id`

* PeerTube instance:
  * version: 3.2.1
  * NodeJS version: 14.17.1
  * Ffmpeg version: 4.1.6-1~deb10u1

Thank you in advance

**Comment by Agorise** [comment]
Lots of "500 internal server error" messages. 
Lots of red toast error messages pop up on the site too (bottom right corner of the instance recently-added page) with this text inside of the error that is displayed: 
 
<html> <head><title>500 Internal Server Error</title></head> <body> <center><h1>500 Internal Server Error</h1></center> <hr><center>nginx/1.21.0</center> </body> </html>      <!-- a padding to disable MSIE and Chrome friendly error page →

**Comment by geco** [comment]
> Hello @Chocobozzz , i'm getting the peertube logs full (about 100/minute) of these error messages, i've searched into issues but i can't find something similar. Do you have any idea of what's causing it? I've tried disabling HLS but errors continue.
> 
> "stack": "Error: no peer with that `to_peer_id`\n at /app/node_modules/bittorrent-tracker/server.js:554:41\n at /app/node_modules/bittorrent-tracker/server.js:364:7\n at processTicksAndRejections (internal/process/task_queues.js:77:11)",
> "message": "no peer with that `to_peer_id`
> 
> * PeerTube instance:
>   
>   * version: 3.2.1
>   * NodeJS version: 14.17.1
>   * Ffmpeg version: 4.1.6-1~deb10u1
> 
> Thank you in advance

I add an information: we've upgraded peertube from version 3.1 to 3.2.1, enabled hls and disabled webtorrent (about 1800 videos existing)

**Comment by Agorise** [comment]
Exactly, but just so that @Chocobozzz knows, we switched the server back to webtorrent from HLS since we thought that might have been the problem. 
 
The 1800 videos that we host on our server caused a ton of "500 internal server error" messages. I can only assume it is because the server was trying to reformat the db or something due to the streaming method switch. 
 
Every time the peertube website/instance threw up an error 500, those toast messages would also pop up on the site too (bottom right corner of the instance recently-added page) with this text inside of the error that is displayed: 
 
`<html> <head><title>500 Internal Server Error</title></head> <body> <center><h1>500 Internal Server Error</h1></center> <hr><center>nginx/1.21.0</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page →`

**Comment by Chocobozzz** [comment]
Hello,

Please paste server logs regarding this 500 error.

**Comment by marcialvieira** [comment]
There are 287223 occurrences of the log below.

2021/07/17 22:50:16 [warn] 810#810: 1024 worker_connections are not enough, reusing connections

**Comment by Chocobozzz** [comment]
Then try to increase the worker_connections config
