### ISSUE TITLE
PeerTube 3.3.0 „Incompatible browser” error on Palemoon

### ISSUE THREAD

**Issue by kujaw** [Chocobozzz/PeerTube#4311]
**Describe the current behavior**
When trying access Peertube 3.3.0 instance (for the time of writing it is e.g. https://peertube.stream/), I'm getting error page saying:
```
PeerTube
Incompatible browser
We are sorry but it seems that PeerTube is not compatible with your web browser.
Please try with the latest version of Mozilla Firefox.
If you think this is a mistake, please report it.
```
**Steps to reproduce:**

1. Visit Peertube 3.3.0 instance using Palemoon 29.30

**Describe the expected behavior**
Should work :P

**Additional information**

* PeerTube instance:
  * URL: peertube.stream
  * version: 3.30
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Palemoon 29.3.0
* Link to browser console log if relevant: :(
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): :(

**Comment by ROBERT-MCDOWELL** [comment]
could you provide the full user agent of palemoon?

**Comment by ROBERT-MCDOWELL** [comment]
could you see the website https://conf.tube/ ???
because I can with mypal browser (a fork from paelemoon), which is peertube version 3.0.1
the version I installed to my server has the same problem of you, browser not compatible and it should be indeed.

**Comment by kujaw** [comment]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Goanna/4.8 Firefox/68.0 PaleMoon/29.3.0
I can see conf.tube.

**Comment by EchedeyLR** [comment]
@kujaw which useragent has you configured in your browser?

I mean, Pale Moon and third party builds (New Moon) allow you to set 3 kind of useragents:
- Native
- Gecko Compatibility
- Firefox Compatibility

By default, it is set to Firefox Compatibility and the Firefox reference on it, it is set to last Firefox ESR version iirc but, as version 29.3.0 the Gecko and Firefox Compatibility useragent is set to the old Firefox ESR version (68.0) instead of the last (78.0).

I am using Native whose useragent is:
```
Mozilla/5.0 (X11; Linux x86_64; rv:4.8) Goanna/20210720 PaleMoon/29.3.0
```

For Gecko Compatibility is:
```
Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Goanna/4.8 PaleMoon/29.3.0
```

And, for Firefox Compatibility is:
```
Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Goanna/4.8 Firefox/68.0 PaleMoon/29.3.0
```

**Comment by Chocobozzz** [comment]
Hello,

We don't detect user agents to display this message. We display it when there is a fatal JS error. In this specific case, it's related to the lack of support of dynamic import in palemoon which most web browsers support for some time: https://caniuse.com/es6-module-dynamic-import

I suggest to subscribe to https://repo.palemoon.org/MoonchildProductions/UXP/issues/1691

**Comment by ROBERT-MCDOWELL** [comment]
I confirm that import is the problem
Timestamp: 8/18/2021 4:25:22 AM
Error: SyntaxError: expected expression, got keyword 'import'
Source File: https://secure.direct-live.net/client/en-US/main.edd299a39fa834d242c4.js
Line: 3, Column: 1137015
Source Code:
onst a=(h.N.apiUrl||window.location.origin)+n.script;return import(a).then(t=>t.register({registerHook:i,registerVideoFi
BUT, I visited many site with import instruction without problem with mypal and palemoon.

**Comment by ROBERT-MCDOWELL** [comment]
btw, is there a ECMASCRIPT version change since peertube version 3.0.0?
what ecmascript version is used for typescript?
here a useful table of compatibility.
https://kangax.github.io/compat-table/es6/
I think peertube will lose a lot of users if at least it's less browser compatible than youtube or odysee.

**Comment by sirrooster** [comment]
Hello,
I am only a simple user, and I understand nothing what is written here.
Can you tell me if there is a solution to use PeerTube with MyPal?

btw: On this peertube site I still can playback videos:
https://tube.querdenken-711.de/videos/watch/cc32afcd-3df8-4092-bde0-da8387263512
but I can not read the text / font.

On this peertube site it shows error:
https://vdp.veezee.tube/videos/recently-added

What to do now?
Is there any other working browser for XP?
And why is (e.g.) YouTube so much better???
