### ISSUE TITLE
Enable Kubernetes / Helm support

### ISSUE THREAD

**Issue by panzouh** [Chocobozzz/PeerTube#4614]
Hello, 

I would like to know if you would like to move towards Cloud Native hosting modes, such as Kubernetes, if so I would be happy to take a look :)

**Comment by kontrollanten** [comment]
I think that would be really interesting. We're currently running PeerTube behind a CDN where we have a OpenStack where we've separated database, redis and PeerTube server. Each update we're doing to the PeerTube server means creating a new server and then shutting down the old server. The only issues we've had is a transcoding queue bottleneck and transcoding jobs that fails due to server shutdown. We hope the latter will be solved in 4.0.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately we don't have Kubernetes skills so we can't maintain such guide. However we have a [unofficial guide for Kubernetes](https://docs.joinpeertube.org/install-unofficial?id=kubernetes). Contributions are welcomed: https://framagit.org/framasoft/peertube/documentation/-/edit/master/install-unofficial.md :)

**Comment by ThomasSamson** [comment]
Hello, We just have created a Helm Chart for deploying peertube you can ginf it [here](https://github.com/coopTilleuls/helm-charts/tree/main/charts/peertube)
