### ISSUE TITLE
Video not starting to play

### ISSUE THREAD

**Issue by sachaz** [Chocobozzz/PeerTube#4628]
Dear Peertube community,

On our peertube since last upgrade in 3.4.1 (maybe before) some old videos are not starting anymore.
Some exemples:
https://tube.aquilenet.fr/w/mhqrZLAXYd4dhwSGkUWEwc
https://tube.aquilenet.fr/w/meKJU4ngW1Aupau4kzEqkt

* PeerTube instance: Aquilenet
  * URL: https://tube.aquilenet.fr/
  * version: 3.4.1 
  * NodeJS version: 12.22.5 dfsg-2 11u1
  * Ffmpeg version: 7:4.3.3-0+deb11u1

**Comment by sachaz** [comment]
Tryed to réencode with no succes:
~~~
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run 
create-transcoding-job -- --generate-hls -v a441bd81-dcde-4d41-a745-35068e084dbf
Error: ffprobe exited with code 1
(...)
/var/www/peertube/storage/streaming-playlists/hls/a441bd81-dcde-4d41-a745-35068e084dbf/a441bd81-dcde-4d41-a745-35068e084dbf-240-fragmented.mp4: No such file or directory
~~~
In my config/production.yaml I got:
~~~
storage:
(...)
  streaming_playlists: '/var/www/peertube/storage/streaming-playlists/
~~~
And in my system I got
~~~
root@argos:/var/www/peertube# ls -al /var/www/peertube/storage/streaming-playlists/
total 21
drwxr-xr-x   3 peertube peertube   3 18 nov.   2020 .
drwxr-xr-x  13 peertube peertube  14 11 déc.  18:53 ..
drwxr-xr-x 218 peertube peertube 218 11 déc.  19:21 hls
~~~

**Comment by andrew712-1** [comment]
the same is happening on bittube.video

**Comment by sachaz** [comment]
In the Firefox console I got:
HLS.js error: networkError - fatal: true - manifestLoadError

**Comment by avdb13** [comment]
Same issue ... I reinstalled the entire thing and still end up with the same problem. Thumbnails aren't loading and video player is unresponsive. 
Here is a screenshot of my Firefox console: https://midi.moe/f/ceryr.png

**Comment by Chocobozzz** [comment]
https://tube.aquilenet.fr/w/mhqrZLAXYd4dhwSGkUWEwc seems to work correctly on my side 

HLS version of https://tube.aquilenet.fr/w/meKJU4ngW1Aupau4kzEqkt does not exist on your disk, which is weird.

@andrew712-1  @avdb13 please create dedicated issues and fill the bug template

**Comment by andrew712-1** [comment]
not a single local video on bittube.video seems to work, example https://bittube.video/w/1Z5kjSM69SRnaxHWfukiEr

my apologies

**Comment by avdb13** [comment]
@Chocobozzz maybe you could have linked it? I literally followed the installation documentation 1:1 (other than the changes below) and then ran an update, strangely enough I noticed that this time it's installing 4.0.0 instead of 4.3.1.

What I did was replace `hostname` in `/var/www/peertube/config/production.yaml` with my own domain name and change 
 `echo "cd $APP_DIR && NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $APP_DIR/$NODE_APP $KWARGS 1>$LOG_FILE 2>&1 & echo \$! > $PID_FILE" | sudo -u -i $USER` to `echo "cd $APP_DIR && NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $APP_DIR/$NODE_APP $KWARGS 1>$LOG_FILE 2>&1 & echo \$! > $PID_FILE" | su $USER` in `/etc/init.d/peertube` since I don't want sudo installed on my system. I think it's bad practice to make this a "dependency" when `su` can serve the same functionality here.

These are the errors I'm getting on 4.0.0 in the console: https://dpaste.com/AUQ3KSFT4

**Comment by Chocobozzz** [comment]
> maybe you could have linked it? I

When you create an issue github will give you the choice to fill the bug template :) What is your ffmpeg version?
