### ISSUE TITLE
Incorrect request parameters: videoChannels.maxPerUser, transcoding.resolutions.144p

### ISSUE THREAD

**Issue by kodxana** [Chocobozzz/PeerTube#4649]
**Describe the current behavior**

**Steps to reproduce:**

1. Update PeerTube Docker to 4.0
2. Try edit settings at /admin/config/edit-custom#transcoding
3. I get error "Incorrect request parameters: videoChannels.maxPerUser, transcoding.resolutions.144p, live.transcoding.resolutions.144p" when saving settings.

**Describe the expected behavior**
No error should show and transcoding should work normal.

**Additional information**

* PeerTube instance:
  * URL: https://peer.madiator.com/
  * version: 4.0.0
  * NodeJS version: v12.22.7
  * Ffmpeg version: 4.3.3-0+deb11u1

*Full Error from console:
```
[peer.madiator.com:443] 2021-12-17 14:02:14.810 info: 173.19.0.1 - - [17/Dec/2021:14:02:14 +0000] "GET /api/v1/config/about HTTP/1.1" 304 - "https://peer.madiator.com/admin/config/edit-custom" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[peer.madiator.com:443] 2021-12-17 14:02:22.669 warn: Incorrect request parameters {
  "path": "/api/v1/config/custom",
  "err": {
    "videoChannels.maxPerUser": {
      "msg": "Should have a valid maximum amount of video channels per user",
      "param": "videoChannels.maxPerUser",
      "location": "body"
    },
    "transcoding.resolutions.144p": {
      "msg": "Should have a valid transcoding 144p resolution enabled boolean",
      "param": "transcoding.resolutions.144p",
      "location": "body"
    },
    "live.transcoding.resolutions.144p": {
      "msg": "Should have a valid transcoding 144p resolution enabled boolean",
      "param": "live.transcoding.resolutions.144p",
      "location": "body"
    }
  }
}
```

**Comment by Chocobozzz** [comment]
Hello,

Did you follow https://docs.joinpeertube.org/install-docker?id=upgrade?

In particular `docker-compose down -v` (`-v` is important)

**Comment by kodxana** [comment]
Looks like the image that was pushed 10h ago fixed the issue.

**Comment by gohlool** [comment]
Hello,

Today I did an upgrade to version 4.3 (chocobozzz/peertube:v4.3.0-bullseye).

The first time, I didn't execute `docker-compose down -v` because my volumes were all declared inside the compose file (not external). Everything went well, until I noticed that I can do any changed in the configuration. I came across of this post, so I created all the volumes per `docker volume create` and migrated everything from the backup to the new volumes.

I also updated my docker-compose file to mark the new volumes as external. Later, I called the following commands:
 
```
  docker-compose down -v 
  docker-compose pull and finally 
  docker-compose up -d
```

Everything is up and running, but I am still not able to update the configuration. Just by clicking the button “update configuration” without any changes done, I get the following error:

Incorrect request parameters: videoChannels.maxPerUser, transcoding.resolutions.144p, transcoding.alwaysTranscodeOriginalResolution, videoStudio.enabled, import.videoChannelSynchronization.enabled, live.transcoding.resolutions.144p, live.transcoding.alwaysTranscodeOriginalResolution

docker logs:

```
 Incorrect request parameters {
peertube           |   "path": "/api/v1/config/custom",
peertube           |   "err": {
peertube           |     "videoChannels.maxPerUser": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "videoChannels.maxPerUser",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "transcoding.resolutions.144p": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "transcoding.resolutions.144p",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "transcoding.alwaysTranscodeOriginalResolution": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "transcoding.alwaysTranscodeOriginalResolution",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "videoStudio.enabled": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "videoStudio.enabled",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "import.videoChannelSynchronization.enabled": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "import.videoChannelSynchronization.enabled",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "live.transcoding.resolutions.144p": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "live.transcoding.resolutions.144p",
peertube           |       "location": "body"
peertube           |     },
peertube           |     "live.transcoding.alwaysTranscodeOriginalResolution": {
peertube           |       "msg": "Invalid value",
peertube           |       "param": "live.transcoding.alwaysTranscodeOriginalResolution",
peertube           |       "location": "body"
peertube           |     }
peertube           |   }
peertube           | }
```
Anybody else gets this error? Is there anything that I can do to resolve this problem?

Thank you advance.

**Comment by Chocobozzz** [comment]
Hello,

`-v` option when using docker compose down is mandatory in the official peertube docker compose stack to "refresh"  client (HTML, JS CSS) files.

**Comment by gohlool** [comment]
Hi,
Thank you so much for information. The problem was that my volumes were all created by docker-compose call (so the volumes were not external) so by calling -v I would have lost everything. Anyway. As I've already mentioned, I did a docker-compose down -v, but after I already updated to v4.3. Afterwards, I realized what I did wrong, so I backed up all the volumes  from the v4.3 instance and created all the volumes by calling docker volume create copied all the files from the backup in to the new volumes. Then I performed the docker-compose down -v and recreated the containers. It seems that everything works perfectly. All videos, configs and users etc. are all up and running.  Do you see any chance for me to resolve this issue (caused by my stupidity) beside of spinning a completely new instance and redo all configs and uploads? 

Thank you so much!
