### ISSUE TITLE
Add screenshot for embed

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#47]
Hello,
Can you add screenshot for embed so  people can know the video content for first eye?

**Comment by Chocobozzz** [comment]
Unfortunately this is not a trivial task.

The video previews is not sent to friends (too big) and we can't put a link to the preview of the origin server because it could overload it with popular videos.

An idea might be to copy the preview from the origin server only when a user want to share the video. A sort of *on demand* preview.

**Comment by imtube** [comment]
@Chocobozzz This might will be ok.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/43f61d2635113001c3d19e3299d8700a00d47e48
