### ISSUE TITLE
Add user subscriptions

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#470]
Add ability for a user to subscribe to an instance, channel or a user.

He would have a personal videos view (like a Mastodon feed for example).

---

### As a user
 - subscription-related:
   - [x] I expect a subscription page to exist 
   - [x] I expect to be able to subscribe to a ~user~/channel while watching their video
   - [x] I expect to be able to unsubscribe to a ~user~/channel while watching their video

 - viewing-related:
   - [ ] I expect to be able to see videos from all my subscriptions (user/channel/instance) at once
   - [ ] ~I expect to be able to see videos just from my user subscriptions~
   - [ ] I expect to be able to see videos just from my channel subscriptions
 
### As an admin
 - [ ] I expect to be able to unsubscribe to an instance while watching their video (the same mechanism doesn't exist for subscription as the discovery of instances is a manual process)

**Comment by voronoipotato** [comment]
Right now not only is there no way to subscribe to a user, there's no way to view videos by a user/channel/instance without search. I'm already feeling the pain from this one. I guess for this we would need a subscriptions page, a subscribe to user, subscribe to channel, and subscribe to instance button when viewing a video. I would also like to see a channel page, a user page, and possibly an instance page which would basically be shortcuts to the search functionality.

When I click view subscriptions it could then do a search for videos by that username. I noticed that the existing search already can look for a username. I can also search for an instance. When I have an @ sign in the search though the search breaks. I think for a first implementation even just having it track usernames would be nice. I'll need to read some of the existing code to see how users/instances/channels are being tracked now.

**Comment by voronoipotato** [comment]
I'm going to work on this, but don't be afraid to work over me because I'm less experienced with angular. Just let me know if / when you're starting this so I can stop. Here are my user stories in order that I intend to do them. When we get user pages I'll also add a subscribe button there. 

## Minimum Requirements
### As a user
 - [ ] I expect a subscription page to exist 
 - [ ] I expect to be able to see videos from all my subscriptions (user/channel/instance) at once
 - [ ] I expect to be able to subscribe to a user while watching their video
 - [ ] I expect to be able to unsubscribe to a user while watching their video
 - [ ] I expect to be able to see videos just from my user subscriptions
 - [ ] I expect to be able to subscribe to a channel while watching their video
 - [ ] I expect to be able to unsubscribe to a channel while watching their video
 - [ ] I expect to be able to see videos just from my channel subscriptions
 - [ ] I expect to be able to subscribe to an instance while watching their video
 - [ ] I expect to be able to unsubscribe to an instance while watching their video
 - [ ] I expect to be able to see videos just from my instance subscriptions

**Comment by Chocobozzz** [comment]
This is clearly not a good first issue! :) Thanks for the stories, I planned to implement this at the beginning of summer but if you want to try go for it!

**Comment by andzdroid** [comment]
I would suggest the 'follow instance' button to be present on every page, not just on videos.

**Comment by voronoipotato** [comment]
I'm going to do the absolute minimum viable implementation to use this feature and then we can talk about other things we need. Its likely once it's done that a lot of necessary things to be added will become obvious. Thanks for the suggestion though and I'll keep it in mind once I'm completed with this.

**Comment by voronoipotato** [comment]
As a small update, I've not been able to put in much time yet because I've had family obligations, I worked on adding the views. I'll be working on this tonight and I might need some guidance on setting up my machine to actually host and run peertube so that I can test.  I was able to get dependencies installed last night and now it's a matter of getting everything set up.

**Comment by voronoipotato** [comment]
Okay I am finally in a place where I can build. I'm using hyper-v for development and I needed to use the fix at.  
https://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc I think because of the dynamic ram allocation. 

Either way, I'm back on track now it runs (Fedora) and everything works great.

**Comment by voronoipotato** [comment]
Alright, I've been focusing on the obvious things so far, so that means adding my Model and my View. It's been somewhat self-explanatory but I'll likely hop on tonight to ask some questions.

**Comment by voronoipotato** [comment]
I don't have the time available that I thought I would have. Someone else should take this on.

**Comment by OlivierNicole** [comment]
I see several people on Mastodon thinking that this feature is crucial, considering that many users will expect a Youtube-like experience. So I was just wondering what is its priority in the todo-list.

**Comment by Chocobozzz** [comment]
It's one of the goal of our kickstarter campaign: https://www.kisskissbankbank.com/en/projects/peertube-a-free-and-federated-video-platform

**Comment by tcitworld** [comment]
@benrob0329 See first post.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/f6eebcb336c067e160a62020a5140d8d992ba384 & https://github.com/Chocobozzz/PeerTube/commit/f37dc0dd14d9ce0b59c454c2c1b935fcbe9727e9 & https://github.com/Chocobozzz/PeerTube/commit/f5b0af50c85e2f8b6b2b054ac1f47123cacbe08d & https://github.com/Chocobozzz/PeerTube/commit/06a05d5f4784a7cbb27aa1188385b5679845dad8 & https://github.com/Chocobozzz/PeerTube/commit/99492dbc0d87ef54d0dab7d8d44f8d0de5722bdd & https://github.com/Chocobozzz/PeerTube/commit/22a16e36f6526887ed8f5e5d3c9f9e5da0b4a8cd
