### ISSUE TITLE
I would like to show "Videos redundancies" on my instance

### ISSUE THREAD

**Issue by Axeltherabbit** [Chocobozzz/PeerTube#4702]
**Describe the problem to be solved**
Video i mirror on my instance are not shown.

When I choose to make a video redundant on my instance it is because I think it is an interesting video, I don't want to fill the network with duplicate videos, and I also want to support the other instances.

For instance I search for [BBS: the Documentary](https://search.joinpeertube.org/search?search=BBS+-+The+Documentary&sort=-match&host=&page=1) it's a 4 hours documentary and I have 13 results that are all almost the same and most of them are just too slow and is not watchable. I'd rather have 1 result with 13 peers serving the same video.

Right now if I also want to provide the same video on my instance I have to just upload another video unless the instance accepts my follow request.

**Describe the solution you would like:**

I'd like to have a section "Local Video Mirrored" or similar

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we prefer to not add another page for mirrored videos since most users would not understand what it means.
However, you could create [a custom API route](https://docs.joinpeertube.org/contribute-plugins?id=add-custom-routes), add [a menu entry][https://docs.joinpeertube.org/contribute-plugins?id=addremove-left-menu-links) and [create a dedicated client page](https://docs.joinpeertube.org/contribute-plugins?id=create-client-page) using the PeerTube plugin API.

**Comment by Axeltherabbit** [comment]
What if rather than having a custom menu entry, they are shown with local video (with maybe a small icon to distinguish them from other regular video).

**Comment by Chocobozzz** [comment]
I think the icon could be a good idea. You could add it using [the plugin api](https://docs.joinpeertube.org/contribute-plugins) (using `filter:api.videos.list.result` param for example).
