### ISSUE TITLE
Add video format/codec informations

### ISSUE THREAD

**Issue by Sp3r4z** [Chocobozzz/PeerTube#479]
Hello devs.

I've thought about a feature, which can be really useful, for when someone wanted to download a video: giving to viewer the ability to know technical information about video.
I give you an example:
> Video informations:
1920x1080px 1fps yuv420p vp9
opus 96kbits/s stereo
WebM - 4.4Mo

I've done that, manually, for [this video](https://peertube.xyz/videos/watch/b80c711a-c455-4535-b1f0-2d0cf1290e62).

I find that really interesting for downloaders, knowing size, codecs and technical stuff.

PS: maybe it's not a good idea, because download are into mp4 format (transcoding is done on server somewhere). Let me know about my idea :) (I think it's still a good idea :))

Thanks for all the Peertube work :+1:

**Comment by rigelk** [comment]
@Sp3r4z there is [mediainfo](https://mediaarea.net/en/MediaInfo) for that purpose ;)

But we could indeed add some info.

**Comment by Sp3r4z** [comment]
@rigelk it's not about finding that on my computer (ffmpeg is good at that). It's more about having than on the video description. In fact, with transcoding after upload is pretty the same for all videos (except for file size).

I just find that interesting having some download information below video. It's not "super important, THE IDEA of the decade, but well it's just nice to have that). :)

**Comment by rigelk** [comment]
@Sp3r4z you misunderstood me. I'm suggesting to use the mediainfo standard of information display *in your suggested feature*. Of course it's more convenient to have PeerTube show you info about the media and the versions available for it :)

**Comment by Sp3r4z** [comment]
@rigelk Sorry for that :cry: 

So for Peertube, it can be a really good idea getting that with `mediainfo`, it returns very nice informations. See here: [mediainfo.txt](https://github.com/Chocobozzz/PeerTube/files/1887467/mediainfo.txt) (same video as above: download video after transcoding and original file).
I think it can be easily parse/extract and added under the description or something (maybe into the popup for download).

**Comment by rigelk** [comment]
There's actually a pure js port of mediainfo: https://github.com/buzz/mediainfo.js
But it seems to have bugs of its own, so I'd stick with a wrapper to the original mediainfo command that will be better maintained (i.e.: [mediainfo-wrapper](https://github.com/vankasteelj/mediainfo-wrapper)).

**Comment by Sp3r4z** [comment]
Servers can run `mediainfo` in CLI, so maybe we can just support that solution?
Sure a `node package` version can be really cool and easier, because it's inside NodeJS (which is required for Peertube), but if it's outdated or not really functional, we can just ask for "mediainfo" as a required dependency.

Let see what's the simplest solution can be find :)

**Comment by JeromeMartinez** [comment]
> There's actually a pure js port of mediainfo: https://github.com/buzz/mediainfo.js
But it seems to have bugs of its own,

@rigelk we have now [our own version of JS port of MediaInfo](https://mediaarea.net/en/MediaInfo/Download/JavaScript), running on [MediaInfoOnline](https://mediaarea.net/MediaInfoOnline), without known bugs (about the JS part, the JS port still contain bugs from the MediaInfo library, not related to the JS port itself).

**Comment by JeromeMartinez** [comment]
> Servers can run mediainfo in CLI, so maybe we can just support that solution?

@Sp3r4z JS port is for analysis of local (visitor computer) files. Quickly looking at your project, looks like you need to analyze server files, in that case you just need to run mediainfo command on the file you want to check, and store the MediaInfo result in order to display it on the page you serve to visitors.
Note that we are working on hosting MediaInfo data on [MediaBin](https://mediaarea.net/MediaBin) with the possibility for MediaInfo to upload MediaInfo result on our (or your) server, so you would just have to store the MediaBin unique identifier and display a link on the page your serve to visitors, it slightly reduce the database size and the byte size of the web page, would you be interested to be a beta tester of such feature?

**Comment by rigelk** [comment]
@JeromeMartinez thanks for all this info (and sorry for the belated answer)! We have not decided of anything yet, but since we already rely on `ffmpeg` anyway for the transcoding server-side, we figured using its sibling `ffprobe` would provide some (albeit not similar) functionality without adding dependencies. 

For instance, it gives some info with a convenient json output like this: `ffprobe -v quiet -print_format json -show_format -show_chapters -show_streams <file-name>`

**Comment by Sp3r4z** [comment]
@rigelk ffprobe seems to be a really good idea and it gives quite nice informations (I've tested it on MP4 and WebM). And, as you said, it doesn't require other dependencies.

Maybe we can start with that (extract from the command line you give):

> - format
> 	- size
> 	- format_name
> 	- duration
> - streams
> 	- [video] (key not in JSON output)
> 		- codec_type
> 		- codec_name
> 		- width
> 		- height
> 		- display_aspect_ratio
> 		- pix_fmt
> 		- avg_frame_rate (better than r_frame_rate)
> 	- [audio] (key not in JSON output)
> 		- codec_type
> 		- codec_name
> 		- channels (or channel_layout, maybe more humanly comprehensible)
> 		- sample_rate
