### ISSUE TITLE
instances.joinpeertube.org: wrong location after register a peertube server 

### ISSUE THREAD

**Issue by CodeFreezr** [Chocobozzz/PeerTube#4792]
Hello Together,

thanks for this great stuff!

After adding our Instance [video.r3s.nrw](http://video.r3s.nrw/) We are shown as located in France. Soo many french speaking peertube follows us. But thats wrong, because we are located in germany. How to fix this?

**Comment by Booteille** [comment]
Hi.

I guess this is an issue bound to instances.joinpeertube.org (since the API and so it's probably more appropriate to post this issue on [instances.joinpeertube.org repository](https://framagit.org/framasoft/peertube/instances-peertube/-/issues).

But after investigating a bit, you should know instances.joinpeertube.org determines the [location based on a GeoIP db](https://framagit.org/framasoft/peertube/instances-peertube/-/blob/develop/server/helpers/instance-requests.ts#L56). If you look for your domain on any geolocation service you can find they all show that [you are located in Grand Est, a french region](https://www.geolocation.com/?ip=https%3A%2F%2Fvideo.r3s.nrw%2F#ipresult).

So, either these services are wrong, either you're not located in Germany but really close to, in France. In both case, this is not a bug dues to PeerTube or instances.joinpeertube.org.

**Comment by Chocobozzz** [comment]
Thanks for the explanations @Booteille 

As a side note, `instance.joinpeertube.org` bug/feature tracker is available on https://framagit.org/framasoft/peertube/instances-peertube/-/issues
