### ISSUE TITLE
mozilla firefox 97 is incompatible browser 

### ISSUE THREAD

**Issue by JeffNys** [Chocobozzz/PeerTube#4794]
Hello
I have mozilla firefox 97, we are the 13th of february 2022,
it's my first experience of peertube, 

well
after a check on mozilla website ... version 97 is the last up to date version

my config: 
Linux Mint 20 Cinnamon
Mozilla Firefox for Linux Mint 97

hope that help

**Comment by Booteille** [comment]
Hi.

In case you are not informed, PeerTube works through a network of federated instances. To learn more about how PeerTube works, please, visit [https://joinpeertube.org/](https://joinpeertube.org/).

PeerTube works perfectly fine on Firefox 97 (at least for me, on Linux & Windows)
Your issue is probably related to the instance of PeerTube you've chosen which is probably not working anymore.
What is the url you were trying to visit?

Also, please, consider [filling the template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/10-installation-issue.md) for issues (You can edit your first comment for this one). It's really a time saver for everyone.

Thanks.

**Comment by JeffNys** [comment]
ok, now it's working fine.

it was peertube.fr
version 3.3.0

sorry
thank for answer
