### ISSUE TITLE
Encourage comments to be about the video.

### ISSUE THREAD

**Issue by therahedwig** [Chocobozzz/PeerTube#480]
Okay, so this is as far as I can tell a relatively unusual idea, and will probably require a lot of discussion to get the kinks out of it.

I've been thinking about comments and harassment and things that are annoying in youtube comments for a while. We have different kinds of annoying comments, most of which have been traditionally dealt with through moderation and upvote/downvote mechanisms.

A particular type of comment is very peculiar to video comments. Namely, video comments are supossed to be _comments on the video_. But there's usually nothing stopping people from commenting when they have not finished, or, even started watching the video at all. This is a bit odd to me.

At its most benign, I sometimes see people use video comments as a free-for-all help forum, which is frustrating when there's places on the internet they could get help much quicker.

At its worst, this can be a harassment tactic, with commenters posting horrible comments about the video creator without even starting the video.

**Might it thus be an idea to prevent people from commenting if they have not yet watched a minimal percentage of the video's total?**

Given that some people have already worried about encouraging users to seed, maybe instead use share ratio as an enabler for commenting. These values could be decided by the instance admin.

_The biggest problem with this is, as far as I understand, PeerTube is not the one responsible for commenting_. It seems Mastodon and other activitypub based systems are the responsible ones. I have no idea how to resolve this.

Other big problems:
* I have witnessed some people who write comments doing a sort of live-blog of the video in question. Implementing something like this can accidentally handicap this kind of behaviour.
* How does one go about the situation where someone watches a video, then closes the tab, does some grocery shopping, and realises they have something profound to say and returns to the video. Do they then have to sit through most of the video again? How do we create something that doesn't involve invasive tracking?

These are all pretty large problems. But I figured that the idea in itself might be worth thinking about, so hence why I am creating this issue.

**Comment by Aluriak** [comment]
Yes, let's cure the youtube comment cancer.

To me, only the post-processing is really viable, UX guiding is a good help, and prevention sometimes a good feature.

### prevention
It's your main proposition: avoid bad comments by making them impossible to be published.

My though is : you can't have a rule system that prevent comments without false positive (or in such case it will have a tiny true positive rate). After all, you're dealing with humans (i.e. highly creative agents willing to bypass your system, or just using it in an innovative way) using a natural language (so we can't just parse it to get the real meaning).

Other than the problematic "*can't comment before seing the video*" or "*can't comment before <video's length> minutes after publication*", here is some funny rules:
- a comment must not contain words used in another comment. You have then a very limited subset of possible comment set, and you avoid the repetition of opinions. Make the comments editable by community, and you get a living pad where viewers can't repeat themselves.
- the comments are not shown, but a patchwork of them is. Works in natural language processing allows for basic semantic extraction (see bag of word and word to vec) that would allow to get the most prominent subjects in comments, and build a representative comment with that. Or maybe just a markov model with a button *generate a new representative comment* ?

If you start preventing comments (which is not *bad* by design, but may become if too obscure, complex or injust), you may want to do it fully : multiple rules, that ensure a complex but sane comment section. Let the uploader decide. That goes along an early idea of mine (see #51) that allow the comment section to take multiple shapes, including ones oriented toward thinking collectively instead of commenting the video itself.

Another way to go is the post-processing of comments, i.e. *healing*, which seems to me much more reasonable.

### healing
We consider all-file/API access (again see #51), that could be used by uploaders to filter out comments matching some expression (you get the comments, detect the unwanted one, remove them, and re-upload the updated comments).

More generally, external tools could call complex methods to detect unwanted comments, and in the end, the only thing you need for that is the API to retrieve them and mark them as such.

I think that post-processing is beyond the scope of that project. That's the reason we should allow others to work on it through a generalist API.

### guiding
The other way comes from UX (and i am far from an expert in that domain), and consists into changing semantics and shapes to guide the user behavior. When it comes to humans behaviour, semantics matters a lot.

### My two cents
Few years ago, there was a movement of few bloggers to delete comments from their websites, replacing them by an encouragement to contact them by mail. This deletes the social incentives behind comments.

So, what about curing the comment cancer problem by allowing uploader to avoid all comments, and instead provides a "mail me" button ? Users can then gives their mail address, send a message. And uploaders to have a (per-video) mail box, also accessible through the API (to enable the external tools to work on it).

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.
