### ISSUE TITLE
Add a theme system

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#484]

**Comment by fredsif** [comment]
Awesome! It would be great to style our own instance with a CMS. Like Wordpress.

**Comment by Serkan-devel** [comment]
where did the comment go?

**Comment by fredsif** [comment]
I've deleted it. 
I agree with your idea. Also offering documentation about customizing the theme would be of great help.

**Comment by Zig-03** [comment]
Not everyone understands the decentralization aspect of PT and that every admin can customize everything on their PT instance and some think of PT as of a centralized video platfom, because it looks mostly the same across all instances. One way to fix that would be to let PT instance owners pick from 3 different, pre-built themes, during their initial instance setup. I believe the results of this will help non-tech-savvy people understand decentralization and that almost everything about PT can be modified.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1959
