### ISSUE TITLE
Create a user notification system

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#493]
To notify users about a new comment, video abuses etc with the possibility to send mails too.

**Comment by rigelk** [comment]
There are definitely multiple ways to implement this wrong. We should probably think thoroughly about the uses cases so that we can make the user process of subscribing/reading notifications as simple to understand as possible (maybe we should reach out to designers for that):

- subscribing to updates made to a video
- subscribing to comments made to a video
- support batched notifications (common in mail notification systems, but could also see its use as shown in Github for instance)
- support dozing notifications on a video for some time (global and per-video setting)
- as said above, notifications should probably include video abuse/moderation notifications
- have a global setting to enable/disable mail/platform notifications, with some granularity.

**Comment by Phenitei** [comment]
At least

* subscribing to updates made to a video
* subscribing to comments made to a video
* subscribing to a channel/user

could be done using simple, well-known RSS/Atom feeds.

#### Pros

 * Allowing subscription without any accounting done by the instance (less clutter, and no sign-up).
* Adding another feed with 'batched' updates would be the simple matter of having a feed that posts groups of new items of the 'full' feed, possibly in summarized form. 
 * This would also have the advantage of clearing up the timer question: users just refresh the feed when they want to, and all configuration is left to the user on their feed reader, which they will do anyway.
 * User can subscribe to video/comment/user/instance feeds as they wish, making granularity easier.

#### Cons

 * Not everyone uses or knows what RSS/Atom is. From a proselytist point of view, this is bad because it will lower adoption rate. (I'd argue making people discover feeds is a pro more than a con, but it's a personal point of view and not relevant here).
 * Requires the correct generation of a lot of small files
 * Does not leave any customization of the UI available to instances as a feed reader will do the job of displaying notifications.
 * No push notification (which most people have for email now, making it kind of "real-time", even though one could argue that feeds are like emails in that you refresh them when you wish).

**Comment by rigelk** [comment]
@Phenitei as you accurately point out, RSS/Atom feeds are not suited for real-time. WebSub could be more fitting in that case (?), altough it could be overkill.

As for the channel/user new videos, they are already provided as RSS/Atom/JSON-feed.

**Comment by rezonant** [comment]
Web Notifications ? ServiceWorker should be investigated for other reasons too (which is what powers Web Notifications)

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by grizio** [comment]
Seeing the comment, I think there are two different parts in this ticket:

* Implementing a notification system (generic for all cases) and/or the rules to follow
  * Push vs Pull
  * Configuration system
  * Mail vs Desktop vs Web
  * Immediate actions
  * …
* Implementing notifications for each use case
  * Comments: when? how many times a day?
  * Video abuse
  * …

> maybe we should reach out to designers for that
> @rigelk 

:+1: This is more a UX issue than a technical one.

Having not this feature, for #510 and surely other use cases (like jobs or video abuses on the web app), we do not have any way to inform the user about some interactions without him looking at a specific page himself (when it exists).

I am not a designer so I cannot help on this matter for now. :disappointed:

**Comment by 22decembre** [comment]
This could also extend to other matters, such as admin : a new user just registrated (I see this one as a minimum, but other cases might be interesting). Should current users be notified or only admins ?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1513
