### ISSUE TITLE
Mark deleted comment with replies rather than removing completely

### ISSUE THREAD

**Issue by ChameleonScales** [Chocobozzz/PeerTube#507]
When you delete a comment that has replies, it also deletes the replies, which may not be ideal.
A suggestion would be to mark the comment with a "Removed by user" in order to keep its replies and not break the tree of comments.

**Comment by BO41** [comment]
I would like to try to solve this issue. But I don't find where the actual comment gets deleted.
somewhere at `server/controllers/api/videos/comment.ts`, am I right?

Instead of removing the comment and its thread, I should be able to change the owner or the content to "removed by user" and leave the thread as it is.

**Comment by Chocobozzz** [comment]
It's removed here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/videos/comment.ts#L146

You could add a boolean column to the video comment model (and create a new migration script) `deleted` for example.

**Comment by Chocobozzz** [comment]
Implemented by @alcalyn in https://github.com/Chocobozzz/PeerTube/commit/b5206dfc455c119b0dcb897bd7144be6ea4d999d & https://github.com/Chocobozzz/PeerTube/commit/69222afac8f8c41d90295b33f0695bbff352851e
