### ISSUE TITLE
Add comments system to videos

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#51]
* Subscribe system. When your server displays a video from another pod, it subscribes to the events of comments from this video. The original server then sends the events to servers which subscribed.

* Original server must also get comments from other servers, so... Two way subscription system ?

**Comment by rigelk** [comment]
I know there is ongoing work to make the comment system ActivityPub-compatible, and my propositions don't interfere with it. They are mainly display/metrics features on the PeerTube instance(s).

As suggested by [aluriak](https://framacolibri.org/u/aluriak):

> We should allow to replace the comment system per-video in case the author wants extra features (i.e.: a link to a framapad, framacolibri, framaforms, [arguman](http://en.arguman.org/) or [framindmap](https://framindmap.org/mindmaps/index.html)). It would be so powerful for content producers that have punctual and specific needs (Q&A, challenge, debate, etc.).

To keep things simple, we should *keep the traditional comment system working* and *advertise the link above*, as a per-video (or series or video if we make that happen) override.

> Why not let authors get comments as a file? It's so much simpler to count the number of participants to a game/competition in the comments with a text editor and Ctrl+f rather than with a web interface where you have to manually go through.

I don't agree with everything, but giving content creators a way to better communicate is definitely in the spirit of PeerTube. Give them a .csv (maybe capping to a size) for the simplest cases, and an API so that their fellow developer friends can build tools to help them deal with popularity.

> A tree-like system as seen on reddit.com? A search by filter system on the comments ?

A way to display comments that has worked well in reddit is the tree-like display where comments that are up-voted the most are shown closer to the video. It could be the default display format based on the number of cumulated boosts/favorites, for instance, with a fallback on inverse chronological ordering.

Then, search of comments might be of lower priority, especially since it's only a display feature that is superseded by the aforementioned API/file comment retrieval.

**Comment by Chocobozzz** [comment]
Working branch: https://github.com/Chocobozzz/PeerTube/tree/feature/comments

I'll do a simple comment system first, and then we'll add your proposals in other issues @rigelk.

Main goal -> tree-like system (Mastodon, Reddit...):
  * A video has 0..n comment threads
  * Each thread has 1..n comments
  * A comment could be a reply to another comment

**Comment by Chocobozzz** [comment]
Implemented. 

Demo: https://peertube.cpy.re/videos/watch/da2b08d4-a242-4170-b32a-4ec8cbdca701
