### ISSUE TITLE
Invalid Client error after docker installation WITHOUT Certbot/SSL

### ISSUE THREAD

**Issue by jtayler** [Chocobozzz/PeerTube#5129]
### Describe the problem

This is my first PeerTube install.

I am using Docker on Mac and had trouble generating SSL/CERTBOT certifications locally but was successful in turning off SSL in nginx and fussing with the config files

I enter from http://localhost:9000 and connect ok

I login and get the root user login error: "Invalid client: client is invalid"

I also notice a "Cannot retrieve OAuth Client credentials" which may relate or be caused by turning off the SSL

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by krautzone** [comment]
This message appears when the used host name (here: localhost) is not identical with the configured public PeerTube instance web server name (PEERTUBE_WEBSERVER_HOSTNAME). See for example #4960.

For local experiments, when you don't have the domain name registered yet, you could modify your local host file, so that the public web server host name correspondences to your local IP 127.0.0.1.
