### ISSUE TITLE
We are blasted with comments spam, here's how we could tame it

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5334]
### Describe the problem to be solved

Peertube instances are getting blasted with spambots that use the channel descriptions as their SEO and the comments section as their spam galore. And it is nearly impossible to fix. At least not with the tools we have now. Look at this:
![2022-10-08_16-49](https://user-images.githubusercontent.com/38043315/194713386-0206d998-7e85-4335-be79-25469df8f615.png)
And this is a tiny sample. This happens daily.

### Describe the solution you would like

Ok here's my proposal:

1. The same way that I can see all videos posted by the accounts of my instance, let me see all comments posted by the accounts on my instance, in order. So I can detect these spammers and remove their accounts.
2. For the registration provide a mandatory block where users are forced to explain why they want to join the instance. Spambots are bad at this, and they will fill up with random messages, it is easy to spot them and not approve their accounts.
3. Speaking of that, allow us to manually accept registrations, not just video uploads.
4. For 2 maybe add two options for registering: "I want to upload videos" and "I want to subscribe to other channels/post comments". Just to give the admins more info about whoever wants to create an account.

In any case please please let's fix this. It is becoming a mess.

**Comment by TeknikalDomain** [comment]
For point 1: you can add the `local:true` filter in that comments display to only show comments from your own instance, and typing in someone's **display** name (not **user** name) in the filter allows you to filter on that. Sort by date, which is done automatically. There's already "delete comment" / "delete all account comments" buttons under the "Actions" button.

For point 2: turn open registration off? I believe the "About This Instance" text shows up on the login page, and you could use that to say something along the lines of "To register an account on this instance, please send a message to <EMAIL> with your username and reasoning"

Though if 3 gets implemented, 2 + 3 would be nice.

4 could be done as a workaround for the moment by having all accounts have a 0 GiB upload quota, only those that request upload permissions manually (email / comment on an internal-only video / whatever you choose) have their accounts set to a proper quota?

---

However: As much as this helps local comments, how do we handle remote ones? Sure, account reports get sent to remote instance admins, but if they don't care, they don't care, and someone, as an instance admin, can't spend their free time filling up the instance's blocked channels and/or blocked instances lists.

What I think we *need* might be three administrative tools: a "disable uploads for user" button (besides just 0 quota, an actual, "your account has been restricted because ToS violations" box to warn them appropriately), and "disable comments for user" on the local side, and an addition to those comment actions - besides delete one and delete all, add a "delete all comments and mute user account" button?

**Comment by tio-trom** [comment]
> For point 1: you can add the `local:true` filter in that comments display to only show comments from your own instance, and typing in someone's **display** name (not **user** name) in the filter allows you to filter on that. Sort by date, which is done automatically. There's already "delete comment" / "delete all account comments" buttons under the "Actions" button.

Ah I see! That's very useful. Also am impressed on my instance 1,071 and 0 spam comments. That's encouraging.



> For point 2: turn open registration off? I believe the "About This Instance" text shows up on the login page, and you could use that to say something along the lines of "To register an account on this instance, please send a message to with your username and reasoning"

This seems way too cumbersome. A form for registration should be a better choice.

**Comment by TeknikalDomain** [comment]
Should be, true. But a workaround for the moment...

**Comment by Chocobozzz** [comment]
Hello,

Please create 1 feature request per issue.

> The same way that I can see all videos posted by the accounts of my instance, let me see all comments posted by the accounts on my instance, in order. So I can detect these spammers and remove their accounts.

Is already implemented

> For the registration provide a mandatory block where users are forced to explain why they want to join the instance. Spambots are bad at this, and they will fill up with random messages, it is easy to spot them and not approve their accounts.

See https://github.com/Chocobozzz/PeerTube/issues/2242

> Speaking of that, allow us to manually accept registrations, not just video uploads.

I created an issue for that use case: https://github.com/Chocobozzz/PeerTube/issues/5336 

A a side note, we released a plugin that uses the Akismet service and that may help you to deal with SPAM: https://www.npmjs.com/package/peertube-plugin-akismet

**Comment by tio-trom** [comment]
All sounds great @Chocobozzz ! Thank you very much! I will test the Akismet plugin too!
