### ISSUE TITLE
Add ability to create friendly url for video links

### ISSUE THREAD

**Issue by dedesite** [Chocobozzz/PeerTube#534]
I created this issue after reading [this french comment](https://framacolibri.org/t/ma-premiere-video-mise-sur-le-net-trop-bien-inclues-qq-infos-utiles-ou-pas/2855)  about peertube on framacolibri.

I think it would be create to add the ability to create friendly url for an uploaded.

Something similar as you could find on a CMS like wordpress.

* **PeerTube URL:**  https://peertube.video

* **What is the expected behaviour?**

Be able to create link like  https://peertube.video/videos/watch/my-super-video

Of course, if an url is already taken, then the upload interface tell the user to choose another url.
* **What do you see instead?**

Only link like https://peertube.video/videos/watch/10c1c52f-82f4-42b7-918b-93e3ad8760fc

**Comment by henke37** [comment]
Might need some permission checking to prevent abuse, but this is a good idea. If there is a risk of conflict, simply require that the path is prefixed with the username.

**Comment by DavidLibeau** [comment]
We should add friendly url for accounts to (http://peertube.video/@username and/or http://peertube.video/accounts/username) !

**Comment by Chocobozzz** [comment]
@DavidLibeau It's already the case (in develop for now) https://github.com/Chocobozzz/PeerTube/issues/584#issuecomment-391985410

**Comment by albjeremias** [comment]
its really a very big URL for sharing a link from peertube.. and ugly.. can't we just create an automatic slug from the title of the video? or have a smaller identifier? this hash is huge and ugly

**Comment by magicbrothers** [comment]
@Chocobozzz at least my MR/PR was not useless if this 'bad practice' will be fixed now ;)
Would it be an option to use (the first x characters of) a salted hash of that interal ID in the URL? We'd need a reverse lookup table for that, not pretty, but maybe required. Or, as @rigelk suggested:
> But if you add another field for videos, a very short random string could do (but would require adding it to the API, which is a bit more work)

**Comment by magicbrothers** [comment]
Or another, maybe better idea:
Use the internal ID in the link but append a 'crc32(id + secret)', so that a guessing of unlisted videos isn't possible.
What about that, @Chocobozzz , may I try to implement that?

**Comment by magicbrothers** [comment]
Thanks, @kontrollanten, for your support!
Unfortunately I am not only new to PeerTube development, but also to NodeJS :D (But not to programming in general)
So probably the best way for me is to wait for the implementation of #3680, so I can look through those commits and learn about how all that stuff works.
With that as a base I can imagine to implement my CRC short link idea.

**Comment by Chocobozzz** [comment]
Hello and sorry for the late answer.

I don't think `crc32(id + secret)` is an option, because we still want the id being valid on a different instance (so we want to derivate from the UUID, and not use a secret). 

Using https://github.com/oculus42/short-uuid with https://github.com/Chocobozzz/PeerTube/issues/3680 could be an idea (is `https://peertube.cpy.re/v/73WakrfVbNJBaAmhQtEeDv` short enough?)

**Comment by magicbrothers** [comment]
Hi,

being able to watch videos across different instances is of course what makes PeerTube great.
In my opinion, we really don't need a second cross-instance valid ID for short links. Simply because they're "short links", not "fully qualified video links". Maybe just see it as a feature that an instance offers.
The problem with just using the DB IDs was, that one could guess the links to unlisted videos, which is fixed by using CRC.

Short-UUIDs are still very long, so I think that's not a good solution. I'd say around 14 characters are acceptable.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4212
