### ISSUE TITLE
Use Docker installation error

### ISSUE THREAD

**Issue by iiiiiii1** [Chocobozzz/PeerTube#538]
Hello, when I use Docker, I get an error: ERROR: Service 'peertube' failed to build: The command '/bin/sh -c yarn install --pure-lockfile && npm run build' returned a non-zero code : 134

**Comment by mario26** [comment]
Hi !

I have the same problem, after compiling with docker when running peertube, here is the result:
```
sudo docker-compose up
WARNING: The PEERTUBE_HOSTNAME variable is not set. Defaulting to a blank string.
Building peertube
Step 1/21 : FROM node:8-stretch
 ---> f985f1287214
Step 2/21 : RUN set -ex;     if ! command -v gpg > /dev/null; then       apt-get update;       apt-get install -y --no-install-recommends         gnupg         dirmngr       ;       rm -rf /var/lib/apt/lists/*; fi
 ---> Using cache
 ---> 0ee44c68e290
Step 3/21 : RUN apt-get update     && apt-get -y install ffmpeg     && rm /var/lib/apt/lists/* -fR
 ---> Using cache
 ---> e63576e97e40
Step 4/21 : RUN groupadd -r peertube     && useradd -r -g peertube -m peertube
 ---> Using cache
 ---> 3070c88f51f0
Step 5/21 : ENV GOSU_VERSION 1.10
 ---> Using cache
 ---> 66029f833d99
Step 6/21 : RUN set -ex;         fetchDeps='ca-certificates wget';     apt-get update;     apt-get install -y --no-install-recommends $fetchDeps;     rm -rf /var/lib/apt/lists/*;         dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')";     wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch";     wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc";     export GNUPGHOME="$(mktemp -d)";     for server in $(shuf -e ha.pool.sks-keyservers.net                             hkp://p80.pool.sks-keyservers.net:80                             keyserver.ubuntu.com                             hkp://keyserver.ubuntu.com:80                             pgp.mit.edu) ; do         gpg --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || : ;     done;     gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;     rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc;     chmod +x /usr/local/bin/gosu;     gosu nobody true;         apt-get purge -y --auto-remove wget
 ---> Using cache
 ---> d7fa00410dee
Step 7/21 : WORKDIR /app
 ---> Using cache
 ---> 3d6938538cd7
Step 8/21 : COPY . ./
 ---> Using cache
 ---> cced408f27f7
Step 9/21 : RUN chown -R peertube:peertube /app
 ---> Using cache
 ---> 342d2ecc34ee
Step 10/21 : USER peertube
 ---> Using cache
 ---> 9adc329ded3e
Step 11/21 : RUN yarn install --pure-lockfile     && npm run build
 ---> Running in 830bac584746
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Lockfile not saved, no dependencies.
Done in 0.06s.
npm ERR! path /app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2018-05-07T08_06_15_351Z-debug.log
ERROR: Service 'peertube' failed to build: The command '/bin/sh -c yarn install --pure-lockfile     && npm run build' returned a non-zero code: 254
```
I tried this command:
```
sudo /bin/sh -c yarn install --pure-lockfile && sudo npm run build
yarn install v1.6.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[8/8] ⠄ youtube-dl
[7/8] ⠄ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.
[3/8] ⠄ rdf-canonize:    EVP_MD_CTX_create
[4/8] ⠄ sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvip
error /var/www/services/PeerTube/node_modules/rdf-canonize: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /var/www/services/PeerTube/node_modules/rdf-canonize
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/services/PeerTube/node_modules/rdf-canonize/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/services/PeerTube/node_modules/rdf-canonize',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/www/services/PeerTube/node_modules/rdf-canonize/build'
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
  CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
In file included from ../lib/native/MessageDigest.cc:10:0:
../lib/native/MessageDigest.h:14:14: error: field ‘context’ has incomplete type ‘EVP_MD_CTX {aka evp_md_ctx_st}’
   EVP_MD_CTX context;
              ^~~~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from ../lib/native/MessageDigest.h:9,
                 from ../lib/native/MessageDigest.cc:10:
/usr/include/openssl/ossl_typ.h:92:16: note: forward declaration of ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                ^~~~~~~~~~~~~
../lib/native/MessageDigest.cc: In destructor ‘RdfCanonize::MessageDigest::~MessageDigest()’:
../lib/native/MessageDigest.cc:35:3: error: ‘EVP_MD_CTX_cleanup’ was not declared in this scope
   EVP_MD_CTX_cleanup(&context);
   ^~~~~~~~~~~~~~~~~~
../lib/native/MessageDigest.cc:35:3: note: suggested alternative: ‘EVP_MD_CTX_create’
   EVP_MD_CTX_cleanup(&context);
   ^~~~~~~~~~~~~~~~~~
   EVP_MD_CTX_create
urdna2015.target.mk:103: recipe for target 'Release/obj.target/urdna2015/lib/native/MessageDigest.o' failed
make: Leaving directory '/var/www/services/PeerTube/node_modules/rdf-canonize/build'
make: *** [Release/obj.target/urdna2015/lib/native/MessageDigest.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/services/PeerTube/node_modules/rdf-canonize
```
So I'm stuck at this stage, can you help us?

Thank you

**Comment by rigelk** [comment]
@mario26 thanks for the detailed output. Being unable to compile `rdf-canonize` probably means you have an old gcc version. Make sure you have gcc >= 4.9 as can be seen in https://github.com/digitalbazaar/rdf-canonize/blob/master/.travis.yml

**Comment by Chocobozzz** [comment]
@iiiiiii1 Please retry, we updated the docker documentation :) https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md#run-a-preconfigured-setup-with-all-dependencies

**Comment by mario26** [comment]
Thank you for your answers !

I managed to run Peertube using the new method described in the documentation for Docker.

Docker start Peertube:
```
sudo docker-compose start
WARNING: The PEERTUBE_HOSTNAME variable is not set. Defaulting to a blank string.
Starting redis    ... done
Starting postgres ... done
Starting peertube ... done
```

Here is the gcc version of my system:

```
dpkg -l gcc
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                 Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  gcc                 4:7.3.0-3ubunt amd64          GNU C compiler

```

Now I have not yet managed to display Peertube in an internet browser, I'm not sure how to configure Nginx with the Peertube container ...

Here are the logs:

sudo docker-compose logs -f
WARNING: The PEERTUBE_HOSTNAME variable is not set. Defaulting to a blank string.
Attaching to production_peertube_1, production_postgres_1, production_redis_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | sh: locale: not found
postgres_1  | 2018-05-07 14:55:42.175 UTC [30] WARNING:  no usable system locales were found
redis_1     | 1:C 07 May 14:55:40.492 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
postgres_1  | performing post-bootstrap initialization ... ok
redis_1     | 1:C 07 May 14:55:40.492 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
postgres_1  | syncing data to disk ... ok
redis_1     | 1:C 07 May 14:55:40.492 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
peertube_1  | 
postgres_1  | 
redis_1     | 1:M 07 May 14:55:40.493 * Running mode=standalone, port=6379.
peertube_1  | > peertube@1.0.0-beta.4 start /app
redis_1     | 1:M 07 May 14:55:40.493 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
postgres_1  | Success. You can now start the database server using:
peertube_1  | > node dist/server
redis_1     | 1:M 07 May 14:55:40.493 # Server initialized
postgres_1  | 
peertube_1  | 
redis_1     | 1:M 07 May 14:55:40.493 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:46.831 info: Database peertube is ready.
redis_1     | 1:M 07 May 14:55:40.493 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
postgres_1  | 
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:49.738 info: Creating application account.
redis_1     | 1:M 07 May 14:55:40.493 * Ready to accept connections
postgres_1  | 
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:49.805 info: Generating a RSA key...
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2018-05-07 14:55:44.141 UTC [35] LOG:  listening on IPv4 address "127.0.0.1", port 5432
postgres_1  | 2018-05-07 14:55:44.141 UTC [35] LOG:  could not bind IPv6 address "::1": Address not available
postgres_1  | 2018-05-07 14:55:44.141 UTC [35] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
postgres_1  | 2018-05-07 14:55:44.208 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-05-07 14:55:44.317 UTC [36] LOG:  database system was shut down at 2018-05-07 14:55:42 UTC
postgres_1  | 2018-05-07 14:55:44.352 UTC [35] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | CREATE ROLE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | waiting for server to shut down...2018-05-07 14:55:45.215 UTC [35] LOG:  received fast shutdown request
postgres_1  | .2018-05-07 14:55:45.240 UTC [35] LOG:  aborting any active transactions
postgres_1  | 2018-05-07 14:55:45.241 UTC [35] LOG:  worker process: logical replication launcher (PID 42) exited with exit code 1
postgres_1  | 2018-05-07 14:55:45.241 UTC [37] LOG:  shutting down
postgres_1  | 2018-05-07 14:55:45.444 UTC [35] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2018-05-07 14:55:45.559 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2018-05-07 14:55:45.559 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2018-05-07 14:55:45.618 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-05-07 14:55:45.745 UTC [48] LOG:  database system was shut down at 2018-05-07 14:55:45 UTC
postgres_1  | 2018-05-07 14:55:45.779 UTC [1] LOG:  database system is ready to accept connections
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.042 info: Creating a default OAuth Client.
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.054 info: Client id: mgkt7xby3st2dcxe1yt8274d5pwvebum
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.054 info: Client secret: fABohvRc6xVGnGNtl5iahSH2VePpVSOz
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.061 info: Creating the administrator.
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.195 info: Generating a RSA key...
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.312 info: Generating a RSA key...
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.462 info: Username: root
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.463 info: User password: nawepotilagexipi
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.464 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.486 info: Server listening on 127.0.0.1:9000
peertube_1  | [peertube.devosi.org:443] 2018-05-07 14:55:50.486 info: Web server: https://peertube.devosi.org
redis_1     | 1:M 07 May 15:00:41.075 * 100 changes in 300 seconds. Saving...
redis_1     | 1:M 07 May 15:00:41.076 * Background saving started by pid 14
redis_1     | 14:C 07 May 15:00:41.105 * DB saved on disk
redis_1     | 14:C 07 May 15:00:41.105 * RDB: 0 MB of memory used by copy-on-write
redis_1     | 1:M 07 May 15:00:41.176 * Background saving terminated with success
redis_1     | 1:M 07 May 15:05:42.013 * 100 changes in 300 seconds. Saving...
redis_1     | 1:M 07 May 15:05:42.013 * Background saving started by pid 15
redis_1     | 15:C 07 May 15:05:42.036 * DB saved on disk
redis_1     | 15:C 07 May 15:05:42.037 * RDB: 0 MB of memory used by copy-on-write
redis_1     | 1:M 07 May 15:05:42.113 * Background saving terminated with success
redis_1     | 1:M 07 May 15:10:43.096 * 100 changes in 300 seconds. Saving...
redis_1     | 1:M 07 May 15:10:43.096 * Background saving started by pid 16
redis_1     | 16:C 07 May 15:10:43.132 * DB saved on disk
redis_1     | 16:C 07 May 15:10:43.132 * RDB: 0 MB of memory used by copy-on-write
redis_1     | 1:M 07 May 15:10:43.196 * Background saving terminated with success
redis_1     | 1:M 07 May 15:15:44.008 * 100 changes in 300 seconds. Saving...
redis_1     | 1:M 07 May 15:15:44.008 * Background saving started by pid 17
redis_1     | 17:C 07 May 15:15:44.052 * DB saved on disk
redis_1     | 17:C 07 May 15:15:44.052 * RDB: 0 MB of memory used by copy-on-write
redis_1     | 1:M 07 May 15:15:44.108 * Background saving terminated with success

I also do not know if the database is configured in docker automatically at the time of buld, or if i have to configuer also something with Postgres?

It lacks a lot of explanation for a noob like me, it's a shame, because I'm sure it will be possible to run a Peertube instance in a few minuts with Docker and a good documentation about ...?!

Regarding the Nginx, I have no explanation, nothing, except an example configuration Nginx which is useless if we do not know Docker and Nginx perfectly.

Thank you again for your support, great project !!

**Comment by Chocobozzz** [comment]
If you want to test quickly peertube in production, uncomment `ports` in docker compose: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L32

**Comment by mario26** [comment]
OK, thanks ! I managed to make Peertube work !!

I created a little tutorial based on the one available on [zeteo.me](https://zeteo.me/blog/technique/crer-son-instance-peertube-avec-docker-compose/): [https://wiki.devosi.org/doku.php?id=auto-hebergement:installer-peertube-avec-docker-compose-et-ubuntu-18.04-bionic](https://wiki.devosi.org/doku.php?id=auto-hebergement:installer-peertube-avec-docker-compose-et-ubuntu-18.04-bionic)

Thank you for your help, great project, continue! :)

**Comment by Yodan** [comment]
Hello, I have the same error.
@mario26 Finally, how did you solve this issue (your wiki is offline and the documentation didn't really help me) ?
