### ISSUE TITLE
Improve redis connection performance

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5382]
### Describe the problem to be solved

ioredis and bullmq are creating multiple connections to redis whom are not shared between the use cases (queues, etc). According to this disussion https://github.com/Chocobozzz/PeerTube/commit/760f620292c39771b03ca01a3fca92cc7672d3a4 this setup can lead to [HOL blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking).

@emansom wrote:

> Best case would be to have a Redis connection picked from a global connection pool per server feature.

> This would yield the lowest latency and highest interactivity on the web interface, as minimal stalling would occur when Node.js libuv decides to context switch in the middle of a HTTP response.

### Describe the solution you would like

bullmq has support for [reusing connections](https://docs.bullmq.io/bull/patterns/reusing-redis-connections) which means we can easily share one connection between all redis usages in PeerTube.

[Here's an article with performance benchmark for redis connections.](https://blog.opstree.com/2019/04/16/redis-best-practices-and-performance-tuning/)

## Questions
* Should we reuse redis connections? Any disadvantages with this implementation?
* Do we need to set `keepAlive` in the [redis connection](https://ioredis.readthedocs.io/en/latest/API/#new-redisport-host-options) to really take advantage of the reused connections?
* Should we implement a connection pool to be able to run multiple redis connections in parallel? According to [this SO question](https://stackoverflow.com/questions/21976270/node-js-redis-connection-pooling) it seems that the only advantage is when using the blocking commands `blpop` and `subscribe`, which we doesn't seem to use.

**Comment by Chocobozzz** [comment]
Using auto pipelining for the internal redis connection of peertube seems to be a good idea. I'm not really understand the "reuse redis connections" since we use nodejs, that just do 1 connection and keep it opened (unlike other threaded programs like classic PHP etc).

Regarding BullMQ, if maintaining multiple connections per queue doesn't bother system administrators, I don't think we should change this behaviour: I don't see how a pool to reuse the same connection with autopipelining would be more performant that separate TCP connections.
