### ISSUE TITLE
Peertube 5.0.0-RC1: error in Japanese

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5445]
### Describe the current behavior

When langage is set to Japanese, the following page has errors: `https://my_instance.tld/my-library/video-channels`

![image](https://user-images.githubusercontent.com/38844060/205969228-2966048b-da30-44f4-88dd-6a013845ba51.png)

The channel list is missing.

The error in the JS console:

```
ERROR Error: Unable to parse ICU expression in "<x id="ICU" xid="1730926218636655979" equiv-text="{getTotalVideosOf(videoChannel), plural, =0 {動画がありません} =1 {1動画} other {{{ getTotalVideosOf(videoChannel) }}動画}} <x id="ICU" xid="1730926218636655979" equiv-text="{getTotalVideosOf(videoChannel), plural, =0 {No videos} =1 {1 video} other {{{ getTotalVideosOf(videoChannel) }} videos}}"/> " message`
```

### Steps to reproduce

1. install v5.0.0-RC1
2. go to my-library

### Additional information

* PeerTube instance:
  * URL: https://videos.john-livingston.fr/my-library/video-channels
  * Version: 5.0.0-RC1

* Browser name, version and platforms on which you could reproduce the bug: firefox

**Comment by fusengum** [comment]
@Chocobozzz , @JohnXLivingston 
I also confirmed that problem.
[Target string weblate page](https://weblate.framasoft.org/translate/peertube/angular/ja/?checksum=5363f310d5d39966)
Caused by `<` is replaced by `&lt;` in japanese string.

Correct: `<x id="ICU" xid="1730926218636655979" equiv-text="{getTotalVideosOf(videoChannel), plural, =0 {動画がありません} =1 {1本の動画} other {{{ getTotalVideosOf(videoChannel) }}本の動画}}"/> `
this string: `&lt;x id="ICU" xid="1730926218636655979" equiv-text="{getTotalVideosOf(videoChannel), plural, =0 {動画がありません} =1 {1本の動画} other {{{ getTotalVideosOf(videoChannel) }}本の動画}}"/&gt; `

This japanese string is already fixed 4 days ago.
I think it'll be fine after applying that new string to v5.0.0-RC1.

**Comment by Chocobozzz** [comment]
Hi,

I updated the translations and confirm it's fixed. Thanks!
