### ISSUE TITLE
Slow query to fetch comments

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5516]
### Describe the current behavior

In Postgresql slow log I found that the queries for fetching comments is very slow (around 2000-4000 ms). I ran some `EXPLAIN (ANALYZE, BUFFERS)` analyzing on them:

https://explain.depesz.com/s/Tl62#html
<img width="513" alt="image" src="https://user-images.githubusercontent.com/6680299/210641801-4eb5acc3-aee5-442c-8386-abc47e32af7d.png">

https://explain.depesz.com/s/bZlR#html (without `LIMIT`)
<img width="463" alt="image" src="https://user-images.githubusercontent.com/6680299/210641858-44c91f5c-8d52-41d1-9cb6-d9b95a0cfb9e.png">

I removed all the reply counting and got an execution time at 1.991 ms (!). Maybe we should store the reply count in the table and live with the glitch that happens when someone you've blocked has replied.

* PeerTube instance:
  * Version: 4.3.1

**Comment by Chocobozzz** [comment]
Hi,

I've completely rewritten SQL queries for comments in https://github.com/Chocobozzz/PeerTube/commit/cde3d90ded5debb24281a444eabb720b721e5600

The old one was weird and not really optimized because we tried to still use Sequelize ORM. I think the new queries will fix your performance issues. If it's not the case don't hesitate to comment this issue: now we use raw SQL queries it will be easier to optimize them.

**Comment by Chocobozzz** [comment]
110ms is still a lot.

Can you send me the `json` file of the explain?

In `explain.sql` file:
```
EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) query
```

(`sudo -u postgres psql -qAt -f explain.sql peertube_prod > analyze.json`)

**Comment by Chocobozzz** [comment]
Thanks, I improved the SQL query and fixed the order by in https://github.com/Chocobozzz/PeerTube/commit/0b96a0fb77cee07abac185fb1fb704388498631b
