### ISSUE TITLE
Install plugins upon init

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5595]
### Describe the problem to be solved

Currently PeerTube assumes that the plugins “installed” (i.e. added in the database) also exists on the disk. In our case we’re creating a new server upon each PT update, which means we have to sync all the npm plugins to a S3 bucket to be able to get them to our new servers.

### Describe the solution you would like

Upon init, PT should generate a package.json file in the plugins folder and run yarn install. If the package.json file already exists nothing should be done, so this should not affect restart time.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but your use case is too specific and not officially supported by PeerTube. I think you should run the command in a pre-hook, before running PeerTube.

**Comment by Chocobozzz** [comment]
I agree with you that we need to support horizontal scalability in PeerTube. But at the moment we don't. It seems you have found a way to have some kind of load balanced PeerTube in your own infrastructure. Adding features in PeerTube in order to help you to build this kind of infrastructure is fine if it helps the project (redis reconnection for example), but we can't add features that don't help the current form of PeerTube.

In particular, reinstalling plugins every time PeerTube is started is not an expected behaviour. The server expects plugins to be already installed in the appropriate folder on the filesystem.

We can discuss a way to lazily install plugins on startup in another issue, but it would require much more work than a simple command run at startup: we would need to document the feature, the use case and add tests. Other admins may also have a different use case where we would have to adjust the feature specifications.

> but this is pretty simple and adds a lot of value

Every line of code added to PeerTube is a line of code that Framasoft has to maintain: fix any potential bugs it introduces, deal with side effects, refactor, document, maintain test etc. So even a simple feature or piece of code can still require a lot of work for years to come for us :)
