### ISSUE TITLE
Video status stuck in "To edit" after added outro

### ISSUE THREAD

**Issue by maninthemiddle01** [Chocobozzz/PeerTube#5649]
### Describe the current behavior

I uploaded a video and added another one in the Studio at the end. Both have different dimensions and audio rate (32000 kHz and 48000 kHz). Now the video status stuck in “To edit” in videos-overview and " The video is being edited, it may not work properly. " in the direct video link since 2 weeks or so. There is no error-message and the instance admin said there is no error on his side.

### Steps to reproduce

1. Add outro in Studio with different dimensions and different audio rate (32000 kHz and 48000 kHz)

### Describe the expected behavior

Studio 
- will give me an option to choose between the two different dimensions
- will attach the two videos into one without an error

### Additional information

* PeerTube instance: diode.zone
  * URL: https://diode.zone/w/37DXxEeywhpJXdnFhVtJdx
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: all browsers, it may be on the serverside software

**Comment by Chocobozzz** [comment]
Hello,

If the video is still in "to edit" mode, I see 2 options:
 * The task job is still waiting to be processed (can be viewed by the admin)
 * There was an error processing the task, can also be viewer by your admin in the job details/logs

I suggest you reproduce this issue and if the bug is still there, contact your admin to find errors in their log/job.

**Comment by maninthemiddle01** [comment]
I couldn't reproduce the error
