### ISSUE TITLE
Direct downloading a video on mobile device

### ISSUE THREAD

**Issue by El-Gavy** [Chocobozzz/PeerTube#571]
* **PeerTube version or URL:** any video on video.lqdn.fr for instance
* **Browser name/version:** Firefox Focus / Firefox Android

* **What is the expected behaviour?** When trying to direct download a video, i expected to be able to download the video.
* **What do you see instead?** Video opens instead (ok when downloading torrent file)

**Comment by Gnu-Bricoleur** [comment]
The issue has been reproduced both on smartphone and on desktop browser.
It is cause by the line 45 of this file : PeerTube/client/src/app/videos/+video-watch/modal/video-download.component.ts
`const link = this.downloadType === 'direct' ? file.fileUrl : file.torrentUrl
window.open(link)`
maybe replacing window.open(link) by window.open(link, "_blank") would fix the issue.
I'll test it tomorrow and make a formal merge request if it works.

**Comment by rigelk** [comment]
@Gnu-Bricoleur did you manage to do it?

**Comment by Gnu-Bricoleur** [comment]
@rigelk Sorry I should have updated, I tried but I ran into some errors when launching my docker.
I'am on it right now.
I also found a way to specify the the mime type of a file in javascript to force download (if you specify application/binary-stream as mimetype for your file, the navigator will download because he can't execute it).
I think the proper way to do this would be to modify the content-disposition in the header but then it would need to be done on the server side.

P.S. thanks for editing my post to add the code formating. I didn't found how to do it.

**Comment by Gnu-Bricoleur** [comment]
Ok I've spend some time on this issue and it's not as easy as it looks. 
What i mentioned earlier didn't work.
Currently I'am looking on another way to do this, by opening the file and putting it in a blob. 
I'll let you know if it works.

**Comment by strypey** [comment]
I strike this issue a lot with Firefox derived browsers; they will also try to use their internal player/ viewer when you click a link, rather than downloading. The workaround on a desktop OS is to right-click the link and select "save link as", I have no idea what people do on mobile devices because I don't have one.

It would be great if there was a way to tell the browser that a link is intended to be a download link, and to bypass the internal player. If you can figure this out, please let the folks from MediaGoblin know, and probably anyone working on a free code web application would be interested in your solution.

**Comment by rhaamo** [comment]
@Gnu-Bricoleur It needs to be sent with headers like that:
```
content-type: application/octet-stream
content-disposition: attachment; filename="blah.ext"
```

But yes it would be needed to be done server-side.

**Comment by Gnu-Bricoleur** [comment]
Glad it's fixed, I saw the patch and it went a little over my head.
I didn't knew how to put the code server side and i now understand why.
I'll try to understand your code and contribute on other issues now that I've got the site running.

**Comment by Chocobozzz** [comment]
@Gnu-Bricoleur Don't worry, I thought we could fix this issue directly in the client so it was a good first issue but in fact not really ^^ Don't hesitate to find another issue to resolve and ask questions if you need help to contribute ;)

**Comment by El-Gavy** [comment]
Thanks for fixing this !
