### ISSUE TITLE
Resume video when clicking on peertube link in embed

### ISSUE THREAD

**Issue by tdelmas** [Chocobozzz/PeerTube#577]
It would be useful to allow to link directly to a specific timestamp:
- To share it
- In embeded videos, when opening the peertube link

For example, to start the video at 1minute30: 

https://video.lqdn.fr/videos/watch/9772f4a0-c025-4238-bfff-2ca473eceb54#start=90
https://video.lqdn.fr/videos/watch/9772f4a0-c025-4238-bfff-2ca473eceb54#start=90s
https://video.lqdn.fr/videos/watch/9772f4a0-c025-4238-bfff-2ca473eceb54#start=1m30
https://video.lqdn.fr/videos/watch/9772f4a0-c025-4238-bfff-2ca473eceb54#start=1:30

For videos on peertube:
- The settings button could have a new entry "Copy the video link with the timestamp"

For videos embeded:
- The settings button could have a two new entry "Copy the video link" and "Copy the video link with the timestamp"
- The "Peertube" button that open the video in a new tab, it should add the parameters to continue the video where it was

**Comment by rigelk** [comment]
Hi @tdelmas ! Please look out for related issues before creating one, as #468 already covers this. You can then detail further your use case there.

**Comment by tdelmas** [comment]
Hi @rigelk !

> Please look out for related issues before creating one

Thank you, I did but I didn't saw #468 

> as #468 already covers this

Thank you for pointing that issue! however, I have to disagree, #468 covers the ability for the webpage to control the embedded video.

This issue covers the ability for anybody to link to a specific timestamp in the video (and using that ability to improve the link from the embedded to the fullpage) 

https://github.com/Chocobozzz/PeerTube/issues/468#issuecomment-378947354 did mention that, and @Chocobozzz did point out to https://github.com/Chocobozzz/PeerTube/commit/f37bad639b36d35c29a464dc52123a1e7c9cd28a 

I think that commit covers my first point (having a parameter to specify the start timestamp).

But I think this issue should stay open as:
- The `start` parameter seams to only accepts seconds
- The other points about links still stands

What do you think @rigelk ? Maybe I missed something

**Comment by rigelk** [comment]
The fact is, both what you and the other issue suggest are closely related. Maybe the name of the other issue is misleading considering the content that followed. Building on existing issues allows to document and keep track of things. But what is done is done, so if you want to support your difference let's do this :)

1. supporting seconds only in the `start` parameter was done as a matter of simplicity. I guess adding minute/hour support wouldn't hurt.
2. I'm pretty sure adding a link to copy the current timestamp in the embed is a tough UI question, since there are already a lot of buttons that compete for the user's attention. Keeping it low profile is important, especially considering upcoming subtitles/chapter selection buttons. But then a custom embed is not out of the question (I guess? @Chocobozzz ?)
3. having the "Peertube" link in the embed open the video in a new tab at the current timestamp should be a quickfix and is a good idea.
4. your idea of "copy link with the current video timestamp" is also a quickfix in the "Share" modal.

3 and 4 should be easy to do, if you want to take the assignment too @tdelmas

**Comment by tdelmas** [comment]
> Building on existing issues allows to document and keep track of things.

Of course, I completely agree

> 2. I'm pretty sure adding a link to copy the current timestamp in the embed is a tough UI question, since there are already a lot of buttons that compete for the user's attention. Keeping it low profile is important, especially considering upcoming subtitles/chapter selection buttons. But then a custom embed is not out of the question (I guess? @Chocobozzz ?)

For the link I was thinking maybe in the menu of the settings button, to avoid adding a new icon. But with your suggestion of adding it the share modal, maybe just a "share" entry in the settings menu - which open the share modal - could be enough

> 4. your idea of "copy link with the current video timestamp" is also a quickfix in the "Share" modal.

I agree, good idea

> 3 and 4 should be easy to do, if you want to take the assignment too @tdelmas

I think so, I'll see if I can do something.

**Comment by Chocobozzz** [comment]
Thanks for the issue @tdelmas 

I created a [dedicated issue](https://github.com/Chocobozzz/PeerTube/issues/582) for points 2 and 4.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/fc73684adad4fdc6bb8a196bd54ef8ecec4e7391
