### ISSUE TITLE
One shot upgrade from very old version

### ISSUE THREAD

**Issue by dav64** [Chocobozzz/PeerTube#5831]
### Describe the problem

Didn't found anything in the upgrade instructions [Here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade) so I think I might ask here

I'm using a very old Peertube version (3.0.1, but the question is open to any versions), do I need version-by-version upgrade 
`3.0.1 -> 3.1.0 -> 3.2.0 -> ... -> 5.0.1 -> 5.1.0`
(It look like to be long and cumbersome)

Can I do it in one-shot?
`3.0.1 -> 5.1.0`

### Additional information

* Classic Installation
* PeerTube version: 3.0.1

Others information not relevant

**Comment by Chocobozzz** [comment]
Upgrade to 3.4, 4.3 and 5.1 should be safe and would not require too much work.
But don't forget to follow the "IMPORTANT NOTES" of every release :)

**Comment by dav64** [comment]
You message is a little ambiguous as which of proposed solution I should use

Can I do the update directly from 3.0.1 to latest (5.1) in one shot ?

**Comment by oe1rsa** [comment]
JFYI: I have done the upgrade from v3.4.0 to 6.3.0, however not in a single step, but from version to version.

So: it is doable, however there are some traps to look for. 

* You are best off if you happen to "live" on a file system that supports snapshots. Make a snapshot before every step.
* Do not upgrade NodeJS before the release not say it. This is tricky, because between NodeJS 12 (which is installed for v3.4.0) must not be upgraded to the latest supported version i.e. 18. You need to locate e.g. Version 14. I am using Debian, and although there is no provided link available it is easy to guess the link by replacing 18 by 14. (Your mileage may vary.) Ignore the warnings about "version not supported" - you need this version just for a short time anyways.
* The old upgrade.sh scripts try to locate a zip file from the web. zip files are available once you are at version 4. You need to edit the files to use tar.xz files.
* You can (and should) upgrade postgresql to the newest version. However you need to upgrade the database for use with the newer version within postgres, else the peertube scripts won't work.
* Assuming you are using Debian, you should not upgrade to bookworm too early. Look at the realease dates and synchronize the upgrades of peertube and Debian.
* Plan for enough time, you might need rollbacks if you made an error.

Considering the above: If your database and videos is not large, consider extracting the videos and do a fresh install. Afterwards insert the videos again. This however depends also on how many users you have. Fresh entry of all the data also will consume considerable time.

Whatever someone reading this will decide to do: Good luck! And a great thank you to Chocobozzz because everything is really there that is needed.
