### ISSUE TITLE
Make PeerTube recognize ffmpeg git version

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5972]
### Describe the problem to be solved

It's a minor issue, Peertube complain about ffmpeg installed from git
Error: Could not find ffmpeg version in ffmpeg version N-112098-g156f53e987

### Describe the solution you would like

if version contains "^N-" so Peertube should recognize it's a GIT version and
warn like "Detected GIT version of ffmpeg, so you must know what you are doing. If not please install the release version >= 4.3"

**Comment by vid-bin** [comment]
What version of peer tube are you on?

This was fixed a while ago. #5917

**Comment by ROBERT-MCDOWELL** [comment]
5.2.1

**Comment by vid-bin** [comment]
Huh yeah just checked my error log and it still exists, bummer.

**Comment by vid-bin** [comment]
paging @SethFalco

**Comment by SethFalco** [comment]
That's because 5.2.1 doesn't include my changes.
Not sure why they weren't included in the latest release though, I'm not well-versed enough in the release process. 🤔 

Check in 5.2.1 (0c302acb3c358b4d4d8dee45aed1de1108ea37ea):
https://github.com/Chocobozzz/PeerTube/blob/v5.2.1/shared/ffmpeg/ffmpeg-version.ts#L13

Check in develop (a1d93180668a265d5f7bc595e8e864db10e356b6):
https://github.com/Chocobozzz/PeerTube/blob/develop/packages/ffmpeg/src/ffmpeg-version.ts#L16

**Comment by vid-bin** [comment]
Thanks! Looking forward to seeing those changes in the next release.

**Comment by Chocobozzz** [comment]
I confirm the fix will be included in v6, and was not in 5.2.1
