### ISSUE TITLE
Better resolution label for videos with different video aspect

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#6047]
### Describe the problem to be solved

If the video has `21/9` aspect, we display `818p` resolution label instead of `1080p` because PeerTube considers the height as resolution label (so `1920p / (21/9) ~= 818p`)

### Describe the solution you would like

Should be easier for users to see `1080p`, even if it's not the real video height.

Might be interesting to see how vimeo or youtube handle this kind of use case.

**Comment by vid-bin** [comment]
Sure, this sounds good to me!

**Comment by AlexJade23** [comment]
In order to help people use the most accurate resolution, would it be possible to replace the resolution by a label of the type of screen ?
For example, do you use a Phone, a Tablet, a TV, a HomeCinema, or a Cinema, and to make it correspond to
Phone up to 480p (DVD), Tablet up to 720p (HD Ready), TV up to 1080p (Full HD), HomeCinema up to 2160 (UHD4K) and Cinema over 2160

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/21215122a8f5b8222133843c14de3e901fda01ee

@AlexJade23 I preferred to keep the `1080p` etc. labels as other video platforms (youtube, vimeo...) also use this convention. But don't hesitate to create another issue for this. Adding an admin config can be interesting for some use cases.
