### ISSUE TITLE
After upgrading to v6.0.0: Older videos no longer work, error message "Failed to play video"

### ISSUE THREAD

**Issue by CorpulentBrony** [Chocobozzz/PeerTube#6061]
### Describe the current behavior

When attempting to play a video that was uploaded before the URLs were shortened, the attempt fails with a 404 and the user receives the error "Failed to play video."

I've only noticed this behavior since upgrading to v6.0.0.

(Yes, all required nginx config changes were made as part of the upgrade.  Newer videos uploaded since the change in URLs but before the upgrade to v6.0.0 play fine.)

### Steps to reproduce

1. Install an old version of PeerTube (before v3.3.0)
2. Upload videos
3. Upgrade to PeerTube v6.0.0
4. Attempt to play any older videos

### Describe the expected behavior

Videos should play whether or not they were uploaded back when videos had long URLs or short URLs.

### Additional information

* PeerTube instance:
  * URL: https://pony.tube
  * Version: v6.0.0
  * NodeJS version: v18.18.2
  * Ffmpeg version: N-67789-g08e97dae20-static (latest build)

* Browser name, version and platforms on which you could reproduce the bug: Any
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ee6844d718e97c64af637c57438840b713dca5d3 and https://github.com/Chocobozzz/PeerTube/commit/6c89755d04e5e7737132cd0ea0ead864c2d181d6

To summarize and if you use the classic installation paths, you need to update your `production.yaml` to `web_videos: '/var/www/peertube/storage/web-videos/'` and move the directory on the filesystem: `sudo -u peertube mv '/var/www/peertube/storage/videos/' '/var/www/peertube/storage/web-videos/'`
