### ISSUE TITLE
s3 uploading support for preview images

### ISSUE THREAD

**Issue by 3unjee** [Chocobozzz/PeerTube#6092]
Greetings PeerTube,

Currently the s3 support seems to cover videos and playlists.

Would it be feasible to add "preview images" uploading in the future, to offlload the instance as much as possible ?

Best regards,

**Comment by kontrollanten** [comment]
Hi! I like this proposal, to offload the instance even more it could be possible to move even more files to s3.

https://github.com/Chocobozzz/PeerTube/blob/cf843c3f12fa506d1acdf61051dc2c85062ecd3e/config/default.yaml#L148-L175

logs, cache, tmp and tmp_persistent may not be in s3. plugins folder is a bit special since it contains node_modules folder with a lot of files (which isn't efficient when using s3), but that folder can be excluded and downloaded on the instance with a Peertube CLI command.
