### ISSUE TITLE
Help to install Peertube with Docker

### ISSUE THREAD

**Issue by Arthurin** [Chocobozzz/PeerTube#628]
Hello, I installed Docker (on windows 7 with DockerToolbox), followed the Get started tutorial and then the Docker guide for Peertube. I wasn't able to complete the installation of Peertube, any help to fix this is appreciated.
* Is it normal to get "404: Not Found" on this page : https://raw.githubusercontent.com/Chocobozzz/PeerTube/master/support/docker/production/.env ?

* Here is what I get when I try to build my own Docker image
![18-06-06 at 19 40](https://user-images.githubusercontent.com/6535135/41060379-c9c9f60c-69cf-11e8-9905-7bb7b3beb6d1.PNG)

Have a good day

**Comment by rigelk** [comment]
Hello @Arthurin ! I assume you followed from here onwards: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md#build-your-own-docker-image | that's the way to go

Your log shows network errors. Maybe the "Fetching packages" of your `yarn install --pure-lockfile` failed because of these network errors. It could be that, or the typical node-gyp build error that happens with outdated version of gcc. Either way, could you edit the Dockerfile to make `yarn install --verbose --pure-lockfile` instead? That would help clear out the doubt.

P.S.: the right URL is https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/support/docker/production/.env

**Comment by Arthurin** [comment]
Thanks ! 
Yes I used this link and that's where I got the broken URL.
I made the edit to the Dockerfile, here is what I got :
![18-06-06 at 22 20](https://user-images.githubusercontent.com/6535135/41063914-4d03458c-69da-11e8-9ab2-356e938bdf80.PNG)

**Comment by rigelk** [comment]
Ah I see the erroring URL in the doc now! Thanks for spotting it, I'll correct that.

let me summon @Chocobozzz for the build error.

As for traefik, you can replace it with any reverse proxy of your liking (i.e. nginx) - we just provide it as an example. If you want to configure it to be accesible from the outside, you will have to edit https://github.com/Chocobozzz/PeerTube/blob/fa40cbc3b26e2a7b01a6273def62fa8bb552c7b6/support/docker/production/config/traefik.toml#L60 and set the corresponding variable in the compose file to the same domain at https://github.com/Chocobozzz/PeerTube/blob/fa40cbc3b26e2a7b01a6273def62fa8bb552c7b6/support/docker/production/docker-compose.yml#L46

I know it's not ideal, but docker is all about compromise… ;)

**Comment by Chocobozzz** [comment]
Closing since getting the image from docker hub works, and now we provide configuration for the reverse proxy.
