### ISSUE TITLE
Translation missing (although it's already done on weblate)

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#6319]
### Describe the current behavior

On indymotion.fr, we miss the translation of "request an account" and "why do you want to join <instance name>" although they are translated in weblate.framasoft.org. 
Maybe there is a problem in the translation update process? 

### Steps to reproduce

1. install peertube 6.0.4
2. set language to FR-fr 
3. enable registration
4. see the missing translations in the button "request an account" (top left) and some other strings.

### Describe the expected behavior

I expect that the translations in weblate are pushed into production ;)

**Comment by vincib** [comment]
Also, is there a way to recompile the files on a running instance to update strings? 
eg: if I change some strings in client/dist/locale/angular.fr-FR.xlf this does not compile into client/dist/fr-FR/3000.aedc6c9df63e3640.js and therefore this does not appear in the running instance.

I'd like to be able to either 
- change the source file and be able to recompile the angular or other parts of Peertube (I guess we miss some documentation, is it even possible?)
- or update the files from weblate and recompile (same process, + the weblate update one?)

**Comment by Chocobozzz** [comment]
> I expect that the translations in weblate are pushed into production ;)

`Request an account` was translated after 6.0 release and so is not included in 6.0.x versions. New translated strings are not injected in patch versions because badly translated strings can break the build/client.

> Also, is there a way to recompile the files on a running instance to update strings?

Yes, you can change string in the source code and rebuild the application: https://docs.joinpeertube.org/install/unofficial#git
I think you can also update strings directly in the built file `client/dist/fr-FR/3000.aedc6c9df63e3640.js`
