### ISSUE TITLE
Direct access to your private video from the main left panel

### ISSUE THREAD

**Issue by Saineim8** [Chocobozzz/PeerTube#641]
Hi, 

It seems that you can only watch your private video from your : your settings / my video.
Is it possible to make a shortcut on the main left panel to see a nice presentation of your private video ? Browsing your private videos the same way you browse public videos will be a nice enhancement !

Thx

**Comment by Chocobozzz** [comment]
I don't understand: the **My videos** panel is like the main panel except the videos are displayed horizontally, with the same information than **Trending** or **Recently Added" for example. Maybe what you really want is a filter in the **My videos** page to filter videos by privacy? And therefore, only display private videos?

**Comment by Tagadda** [comment]
What I understand here is something like this : 
![image](https://user-images.githubusercontent.com/36127788/41233324-68faf98a-6d89-11e8-8acc-9ddab452540d.png)

A new `/video/my` page listing my own videos, with the same "view" that other public pages (`/videos/local` for example).

**Comment by Chocobozzz** [comment]
Thanks @Tagadda 

I disagree to add this in the videos section, because it would be confusing: "Trending", "Recently added" and "Local" display videos in a different way than "My videos". Moreover, I would prefer to group all "My stuff" here:

![screen_2018-06-11-17 21 27](https://user-images.githubusercontent.com/5180488/41240922-ef2a7f1e-6d9b-11e8-80ac-fb9661358798.png)

Maybe we could add the "My videos" section inside the account dropdown.

@rigelk Do you have an opinion on this?

**Comment by Saineim8** [comment]
Hi everybody,

@Tagadda : yes That's what i was wondering. Just a direct link called "My private video" for instance with the same nice presentation than public videos.

**Comment by rigelk** [comment]
:thinking: tough question. I do see the interest of having an easier access to one's own videos. But so far the video section has only shown public videos as seen by anybody else on the instance, so I wouldn't mix things.

For me, either @Chocobozzz or @Saineim8 would work. Now, if we really want to keep things simple, @Chocobozzz's version is the way to go. But it's not like we don't have space in the left panel. Obviously we're gonna use this space sooner or later, and it probably will be for something related to a user's own videos/playlists/channels.

**Comment by dumptyd** [comment]
We could go with something like this, a whole section dedicated to personal/account related links. 
![image](https://user-images.githubusercontent.com/16368429/41658878-6556d9f6-74b5-11e8-8c10-e58702568748.png)


But this requires the sidebar to be more responsive than it is right now. If the viewport height is less than that of sidebar, the overflowed contents are hidden.

**Comment by grizio** [comment]
I would have started to develop on the project and the issue seems interesting.
However, the final solution is not quite clear.

* Do you only want to have a direct access link to the existing page?
* Should we create a new page using the view like public video lists?
* Where put this link? On the left (as @dumptyd screen)? On the « My stuff » button?

Thanks for you clarification.

**Comment by BO41** [comment]
Am I wrong or was @Chocobozzz solution
>Maybe we could add the "My videos" section inside the account dropdown.

implemented and therefore this issue can be closed?

**Comment by rigelk** [comment]
Indeed. #641 solved it if I recall.

**Comment by BO41** [comment]
@rigelk you linked this issue and not the solving PR.
But thanks for closing :)

**Comment by rigelk** [comment]
Ah right :') I must be tired. Here: #968
