### ISSUE TITLE
Search too strict in returning results

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6582]
### Describe the current behavior

The search system seems to be treating all queries as exact phrase match?

### Steps to reproduce

1. Go to fedi.video and search for orion splashdown, observe no results
2. On same instance search for splashdown, observe result which contains words orion and splashdown

### Describe the expected behavior

Results should show any videos containing matching keywords, even if there are other words between them in actual result.

(If the user actually wants an exact phrase match, they should be using quotation marks around the search terms.)

### Additional information

* PeerTube instance: fedi.video
  * URL: https://fedi.video
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi & thanks for the issue.

We use exact phrase match **and** similarity match. But in your case the search is too small compared to the video title to have a good match between the two strings.

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e18ac0a46810b9d33e87eaca57468b3fd50ab7fe where use PostgreSQL `word_similarity` function (instead of `similarity`): https://www.postgresql.org/docs/current/pgtrgm.html
