### ISSUE TITLE
Add support for deployment on Windows/Windows Server 

### ISSUE THREAD

**Issue by steskalja** [Chocobozzz/PeerTube#6594]
### Describe the problem to be solved

There is no deployment option for Windows/Windows server

### Describe the solution you would like

It would be amazing if there was a build for Windows since it supports both nginx and postgres out of the box.

**Comment by MadMan247** [comment]
I think (not reliable info!!!) that, when I was first attempting to set up peer tube, I used docker on windows with WSL. The docker installation guide did not specify that it was docker for linux only. I was being stupid, don't get me wrong, but I really tried to get it to work. I got surprisingly close. I think the only roadblock was that I didn't have any certificate, self-signed or otherwise. it showed that it was trying to work and erroring out due to some ssl nginx errors.
The majority of my effort was going through the commands, and swapping the /'s for \\'s.
I did give up at this point, so I never got it to work, but if you're really hankering for your own peertube instance and absolutely refuse to install linux on a machine (or, alternatively, run a linux virtual machine on windows. Not recommended, but it works.), I think this route currently is a pretty good bet.

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but Framasoft, the non profit that develops PeerTube, doesn't have enough resource to add support for Windows and Windows server :/

**Comment by emansom** [comment]
From a security perspective, putting anything directly facing the internet on Windows is asking for disaster. Like a bright neon bar in Skidrow "please steal my stuff".

Additionally, it is antithetical to be running a whole open source and freedom respecting stack, on a operating system which only goal is to ensure Billie Gates his pension fund.

**Comment by stevespaw** [comment]
You could probably deploy with Docker for Windows..... I have not tried, but should work.
