### ISSUE TITLE
Mark whole instance as NSFW

### ISSUE THREAD

**Issue by Luclu7** [Chocobozzz/PeerTube#664]
For specific instances, it would be great if it is possible to mark all instance videos like NSFW.

**Comment by skid9000** [comment]
If we could do the same for specifics videos that would be great.

**Comment by Chocobozzz** [comment]
@Luclu7 I don't understand, you mean when someone uploads a video the NSFW checkbox is automatically checked? Or you want to tag another instance as NSFW?

@skid9000 Why don't you just blacklist the videos if you think they need to be NSFW?

**Comment by Chocobozzz** [comment]
IMHO, if a video is NSFW **but** is **not** tagged NSFW, it's an abuse and the video should be blacklisted and reported. But you're not the first person to ask this kind of feature, so maybe I'm wrong.

**Comment by Luclu7** [comment]
I meant as a function for instances' owners, if they always post NSFW content, it would be great to auto-check the box.

**Comment by phoe** [comment]
I can see a situation where a whole instance is dedicated to NSFW content. An opt-out NSFW checkbox would then be preferable to an opt-in.

**Comment by Chocobozzz** [comment]
:+1:

@skid9000 So it's a different feature request than yours, maybe you could create another issue? :)

**Comment by roipoussiere** [comment]
Yes, an NSFW tag at the instance level is an important feature (as an option that the instance admin enables) imho.

For example, https://joinpeertube.org/ displays a random list of PeerTube instances, but any of them host NSFW content, so people who just want to try few instances only to discover PeerTube may see this NSFW content (even if it's fuzzy), giving to this curious persons a bad opinion about PeerTube.

With a NSFW tag at the instance level, it could be easy to solve this problem, just by adding a filter to the joinpeertube's instances list, in order to display only non-NSFW instances.

Also, if I am going to join an instance, I would like to know if NSFW content will be published on this one or not. In particular because if I share a video, I don't want that viewers find NSFW content when they try to go to the main page of the instance.

Or, as an admin who want to improve my video network, I would like to quickly know if an instance is going to publish NSFW content, because this content will appears on my instance as federated videos.

**Comment by artlog** [comment]
I discover this issue after discussing such issue on mastodon.
an example of non flagged problem :( warning NSFW porn ) : https://peertube.live/videos/watch/20a6dfba-2b21-433f-857c-1c61ff8b5b86 .There are two comments requesting it to be flagged NSFW while the whole instance is for sure nsfw some video are not.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/f8802489bbc2c0363b5668e47de7c35f573342e1

**Comment by artlog** [comment]
thanks for removal of nsfw exemple, but i still think such exemple was necessary to show that, well, it happens.
