### ISSUE TITLE
No FAQ on example instances - newbie questions

### ISSUE THREAD

**Issue by slrslr** [Chocobozzz/PeerTube#673]
Hello,

as a newbie i browsed a few instances like https://peertube.video

i am surprised that the sites does not have any FAQ section where they explain:

1. how the site work
2. when i become peer or seeder and which conditions i have to meet to continue being one
3. where is stored data i downloaded when watching videos and how to delete them
4. why there is size limit per the user/registration if the site is just a "tracker" where i thought no video files are stored

Thank you

**Comment by rigelk** [comment]
@slrslr we are in the process of writing a user documentation (actually, it's already done, and just needs translation) and are planning to release it soon. We didn't want to rush it since the interface could change and will change until the first stable release in october.

In the meantime, I might just as well answer your questions :)

2. You become a peer by viewing the video with your browser. To continue being one, you have to keep the tab open and stay on the video.
3. Data you downloaded to see the video are stored on disk, and is deleted automatically once you close the tab/go to another page.
4. A PeerTube instance is not just a BitTorrent tracker. It also hosts the videos, and can transcode them when they are uploaded.

If you have any other question, feel free to ask!

**Comment by slrslr** [comment]
Thank you, in the light of this i would like to bring your attention to similar project, only it works the way that the peers does not need to keep tab or browser open in order to help seed the videos. It is [ZeroNet](https://github.com/HelloZeroNet/ZeroNet) based site [KopyKate big](https://github.com/misses-robot/KopyKate-Big)

People are connected using torrent trackers and when they DL some video or a web page, they start seeding it to others (a distributed web). No need to keep any server running, all peers are equal.

**Comment by rigelk** [comment]
Ah right! I don't know this site - I'll have a look at it. But from my past experience of ZeroNet, it's to be expected data can be shared outside an opened tab, as the ZeroNet daemon can share data downloaded on a page so long as it has not been purged in ZeroNet's interface.

I'm curious how they publish the videos though. I'll have a look tomorrow.
