### ISSUE TITLE
Enable P2P client-side only above server-side throughput threshold

### ISSUE THREAD

**Issue by Insoleet** [Chocobozzz/PeerTube#684]
Current behaviour of Peertube is to enable P2P client-side by default. 

This cause privacy problems since all users IPs are being publicly displayed. Also, P2P is not even needed when you are alone watching a video : in this case the user IP should remain privately shared only with the Peertube server.

I think it would be better to use the Web Torrent system only when required : 
 - The server output bandwith is getting above a given threshold
 - The video number of current viewers is above a given threshold, and the P2P mode will ease the load on the server

This way, attacks around monitoring a web torrent tracker to reveal a user IP would be made much more difficult, since the tracker would contain many IPs and not only the user being attacked. 

One could still monitor the tracker but it seems that it would be a good balance between 100% privacy and sharing all watchers IPs even when unneeded.

**Comment by paulcmal** [comment]
I think what you want is change the [default setting client-side](https://github.com/Chocobozzz/PeerTube/issues/685) rather than "disable" Webtorrent on the server side completely, because as @benrob0329 pointed out, having the server seed at all times is very useful.

I see 4 main reasons for which the default setting should stay as it is, though:
- **transit/peering costs:** bittorrent/webtorrent helps reduce bandwidth costs for server operator, so the default should respect this concern
- **encouraging distributed physical infrastructure:** p2p distribution encourages true federation and network neutrality on the side of network operators (more peering between operators and more p2p systems = more overall bandwidth and less operating costs, less legal/financial stress from Google & other big players)
- **ecology**: the direct consequence of less centralized distribution is a big save in energy consumption because packets don't necessarily have to travel so far (less routers to go through), and you therefore need a much lighter infrastructure server-side
- **resilience**: when you need to switch to torrent mode by default, it will take time for peers to find one another and fetch your content, which could make your content unavailable for a while

Adding an option for sysadmins to completely opt out of Webtorrent and federation ⁽¹⁾ is a reasonable idea, especially when it comes to LANs with high bandwidth. Otherwise, maybe consider adding an option to make Webtorrent opt-in client-side under certain conditions.

⁽¹⁾ I think stopping Webtorrent only makes sense if you stop federating as well. Otherwise, implementing server-side redundancy may become a complete mess. How would other servers help serve the content further throughout the internet if not as seeders of the torrent?

**Comment by Insoleet** [comment]
Yes my point is about "enabling the seeding client-side only when the server needs it". I edited the title to make it clearer.

**Comment by DontUseGithub** [comment]
That's a great suggestion! I was about to open a similar issue myself. :heart:

**Comment by Chocobozzz** [comment]
Closing this interesting issue, but out of the scope of PeerTube. I think it can be implemented using the plugin system.

**Comment by toon462** [comment]
ในวันที่ พ. 12 พ.ค. 2021 14:53 น. Chocobozzz ***@***.***>
เขียนว่า:
