### ISSUE TITLE
Copyright issues?

### ISSUE THREAD

**Issue by n00bundercover** [Chocobozzz/PeerTube#713]
I love finally having a foss youtube alternative. And I am impressed of how polished and stable PeerTube already is. Kudos!

However, I am a little bit scared about the whole copyright aspect of it. I am not only streaming in the end, but also uploading to other users, it's torrent technology after all. When casually browsing PeerTube, how am I supposed to check the copyright of videos? How to deal with the issue arising sooner or later: Users playing copyrighted material and getting sued? Most likely not even aware of the fact that they are seeding?

(I posted the same thing to reddit, but was told this is a better place to do so. So this is just a lazy c&p.)

**Comment by Chocobozzz** [comment]
I don't think we should be scared by this, because the video is originally on a particular server, with a specific domain name. If it contains copyrighted videos, people (police, copyright owner/rightholder, lawyers) should contact the instance administrator so he removes the file.

PeerTube is not a classic P2P network: if you delete the origin video it disappears from the videos list.

**Comment by n00bundercover** [comment]
I don't know about other countries, but in germany there are many lawyers connecting into p2p networks like torrent, logging IPs of people seeding copyrighted material, and then admonishing them (of course asking for rather large amounts of money).
Often there would be better ways to get the file "offline": But it is their business model...

But I hope you are right! :-)
