### ISSUE TITLE
Best torrent client on external servers?

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#714]
Wondering what is the best torrent client to run on external servers with support? Other than Webtorrent

Needs to have a Linux version too.

**Comment by rigelk** [comment]
You could try [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) for the command line, or any of the GUI torrent clients listed in https://github.com/webtorrent/webtorrent/issues/369

> with support

Not sure what you mean. We'll gladly help, but we can't do the support for other projects :wink: 

As for the "best", I don't really know. It really depends on what you want. I like the CLI one because I can script with it…

**Comment by hellomotow** [comment]
@rigelk With WebRTC support. Only the webtorrent-hybrid version works I thought?

**Comment by rigelk** [comment]
Ah, right, my mistake. I meant https://github.com/webtorrent/webtorrent-hybrid indeed!

**Comment by hellomotow** [comment]
@rigelk What are the other supported torrent clients? Only that and Vuze? I am having trouble with webtorrent upload speeds.

**Comment by rigelk** [comment]
As said in the linked issue, there is also Brave and Playback.
