### ISSUE TITLE
Add subtitles system

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#72]
Like previews (https://github.com/Chocobozzz/PeerTube/issues/47), maybe we should use an "on-demand" system: our server asks the file to the origin server and stores it in a cache.

- [x] adding subtitles in the video update view (.srt and .vtt)
- [x] proper UI refactoring

**Comment by ryliejamesthomas** [comment]
You shouldn't even need to I think? It's easy to package closed captions and other kinds of subtitles inside a video container. I understand if you want to make that easier for people to do though, as well as add support to add closed captions after upload.

Support for closed captions and subtitles is very important, I hope this gets more support!

**Comment by mkody** [comment]
Without some extra work, we can't select tracks inside a video container.
Some browsers ([IE/Edge and Safari](https://caniuse.com/#feat=audiotracks)) can select _audio_ tracks, but never heard the same about the caption/subtitles.

**Comment by raphaeljolivet** [comment]
Support for subtitles is clearly a a MUST.
Being a decentralised video player, we should also provide collaborative subtitling of videos : 
I kno several deaf people : subtitling is a major concern for accessibility.

**Comment by rigelk** [comment]
Decentralized and collaborative are two different things though… and adding collaborative editing is tricky, and that it's coming from someone who worked at the http://www.comin-ocw.org/ project (which by the way can be a source of inspiration if we ever dedicate resources to collaborative editing).

**Comment by SaintDI** [comment]
How about to start to upload a video with .srt files and store them together?
Then scan directory with `<video_name>.<lang>.srt` mask.

For instance:

```
video.mp4
video.fr.srt
video.en.srt
video.ru.srt
etc.
```

**Comment by henke37** [comment]
I mean that the usecases overlap. For example, someone who is hard at hearing might also not understand one of the secondary languages.

**Comment by JigmeDatse** [comment]
I'm just setting up PeerTube, and it seems that at least some of this stuff is going to be important to me.  This is my understanding at this time:

- Video containers can contain captions
- There are ways to implement captions outside of video containers (should they be added to the container?)
- There is a desire to support both
- There are issues with the players, when using WebTorrent and not enough support.

The providing "external" captions is helpful.  I personally like both closed and open captions, for different reasons.  

Closed because that stores the captions as text, and that means that the person "following" them can use that text in different ways (could be converted to Braille for example).  

Open are helpful for people who are wanting the caption to be viewed visibly, and don't want to deal with the issues we are talking about here (you don't need to have support for them, because they are right on the video track).  

Of course those are the advantages, the disadvantages can be important as well.  If providing both, without support for positioning for the closed captions, you can have each of the captions interacting negatively (ie. you could have both displaying in the same space).  

While in *most* cases, the closed captions and open captions are not *likely* to be both wanted at the same time (ie. if the closed captions are overtop of the open captions, and are still readable it's not a problem) there probably (I'm thinking of some cases myself) are cases where you may want to see both at the same time.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/40e87e9ecc54e3513fb586928330a7855eb192c6 & https://github.com/Chocobozzz/PeerTube/commit/16f7022b06fb76c0b00c23c970bc8df605b0ec63 & https://github.com/Chocobozzz/PeerTube/commit/f4001cf408a99049d01a356bfb20a62342de06ea & https://github.com/Chocobozzz/PeerTube/commit/772d5642ba617865519ca5e590061adf174866d4

The UI could be better but please create another issue if you have ideas on how to improve it.
