### ISSUE TITLE
High throughput consumption when watching video

### ISSUE THREAD

**Issue by zorun** [Chocobozzz/PeerTube#75]
Hey,

First, thanks for the project, it's quite impressive :)

There is one issue though: the javascript client tries to download the whole video as fast as possible, which is very wasteful network-wise!  This is especially true when a user skips the end of the video, or when the video is really large.  Also, the video continues to download at full speed even when it's paused.

Most "commercial" video platforms have adopted a solution to this issue: first, buffer the start of the video as fast as possible, and then alternate between doing nothing (because there is enough data in the buffer) and downloading the next "chunk" to fill the buffer.  It's not completely easy to do it "right" (avoid stalls), but I think there are research papers on the subject.

**Comment by Chocobozzz** [comment]
Hi @zorun 

Yes you're right, we should probably add this system. But we need to keep in mind that even if the user does not watch the video it is useful that he downloads it anyway so he can send it to other peers.

**Comment by Zig-03** [comment]
> But we need to keep in mind that even if the user does not watch the video it is useful that he downloads it anyway so he can send it to other peers.



What if we first check for peers (I mean users/humans peers) and:

- if the result is 0 this means we are the first to watch the video and we can easily implement [these suggestions](https://github.com/Chocobozzz/PeerTube/issues/1109#issuecomment-424270945). If while we are watching, someone else starts watching as well, then we can just dismiss all the settings described in [that](https://github.com/Chocobozzz/PeerTube/issues/1109#issuecomment-424270945) same thread and buffer the whole video. This is needed because the next user who starts watching the video, might skip somewhere in the middle of the video where we haven't buffered yet.
- if the result is 1 or more then we buffer the whole video.

**Comment by Chocobozzz** [comment]
Fixed with the new experimental HLS player.
