### ISSUE TITLE
Automatically import videos from other platforms

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#754]
In order to simplify the PeerTube adoption from current Youtubers, it's important to simplify the importing process.

The [import script](https://github.com/Chocobozzz/PeerTube/blob/master/server/tools/import-videos.ts) is a good step in this direction, but it is possible to do better: automatically import Youtube videos, so the PeerTube import can be totally transparent for the Youtuber.

We can do this without the Youtube API, by using atom feeds: `https://www.youtube.com/feeds/videos.xml?channel_id=<channel_id>`.

I'm not used with TypeScript but I wrote a small Python script as a proof-of-concept example, available [here](https://framagit.org/snippets/1891).

Used with the import script and a 5min-cronjob, a PeerTube user could feed its instance by only specifying its Youtube channel name.

Note that we also need a way to check if the video is not already on the PeerTube instance, can we provide the youtube video id in some video metadata?

**Comment by rigelk** [comment]
Since it's a auto import, we can assume videos previously imported have the same title as on YT. We could just check against titles for a first implementation.

**Comment by rezonant** [comment]
Maybe for a POC, but speaking as someone who does these sort of automated import ops at my day job (I work for a large YouTube channel) I can say that titles can and are modified after publishing, especially within the first hour after publishing. Can't we store the YouTube video ID in some form of metadata entry on the PeerTube video and look it up to see if we've already imported it?

**Comment by rigelk** [comment]
Ah, right :/

I guess it's not a problem to add this metadata, since it's something that doesn't need to be federated (meaning we don't break things if we add a field to the video model).

My concern is more as to how to make that metadata structure broad enough to be reused for imports from the other platforms supported by youtube-dl. I guess a HashMap is fine there.

**Comment by roipoussiere** [comment]
> My concern is more as to how to make that metadata structure broad enough to be reused for imports from the other platforms supported by youtube-dl. I guess a HashMap is fine there.

Why do you want to generate the id instead of using the unique Youtube video id? This "remote video" id could be empty if is not imported from Youtube.

**Comment by roipoussiere** [comment]
> My concern is more as to how to make that metadata structure broad enough to be reused for imports from the other platforms supported by youtube-dl. I guess a HashMap is fine there.

But not all platforms supported by youtube-dl provides an Atom/RSS feed.

Note that a unique item id [is mandatory](https://tools.ietf.org/html/rfc4287#section-4.1.2) for Atom feed:

> atom:entry elements MUST contain exactly one atom:id element.

... but [is optional](https://cyber.harvard.edu/rss/rss.html#ltguidgtSubelementOfLtitemgt) for RSS feed:

> <guid> is an optional sub-element of <item>. guid stands for globally unique identifier. It's a string that uniquely identifies the item.

Related: The [RSS bridge project](https://github.com/RSS-Bridge/rss-bridge) provides Atom/RSS for many websites, including video providers.

In fact we could simply use the video URL as a unique identifier, it is supported by all platforms and supposed to be unique.

**Comment by roipoussiere** [comment]
> An example is the 4-5 different ways to express a YouTube URL (YouTube.be, mobile.youtube.com/watch, gaming.youtube.com/watch, music.youtube.com/watch, YouTube.com/watch)

Hmm yes, good point. provider and providerID could be fine.

---

Note that Vimeo and DailyMotion also officially provide feeds, where we can find video unique ids:
- <feed> <entry> <yt:videoId>
- `<rss> / <channel> / <item> / <dm:id>` for DailyMoton ([example](https://www.dailymotion.com/rss/user/dialhainaut/1));
- `<rss> / <channel> / <item> / <guid>` ([example](https://vimeo.com/channels/wineaftercoffee/videos/rss))

So we could easily implement auto-download for all these platforms.

**Comment by Bugsbane** [comment]
This is an important idea for boosting the amount of content on the Peertube network. Once included, I would go as far as to as to ask for new users channels elsewhere that they'd like to set up for auto-import, when they're registering.

That way, creators from other platforms who make an account on a PeerTube instance "just to try it out" will automatically get up and running quickly and the network gets a ton of ongoing new content, even if they forget about their PeerTube channel and don't touch it again.

Beyond the scope of this issue, but worth considering later, would be actually doing a full import of someone's channel (not just videos), ie their channel description, avatar etc.

**Comment by McFlat** [comment]
I don't think that checking against the video title/name would be good, because users can upload different videos having the same name. it's better to store the original url for the imported video and check against the imported video url.

This is how it's done for the frontend when a user imports a video, but for the video-import script it doesn't set the original video url that's imported(targetUrl). So really it is a bug in the `./server/tools/peertube-import-videos.ts` because it's not performing the same steps as the video import from the frontend, it also doesn't create entries in the videoImport table when using the script, but it does do it when done by a user from the frontend.

<img width="608" alt="screen shot 2018-10-10 at 12 02 51 pm" src="https://user-images.githubusercontent.com/43896676/46753183-c0f79300-cc84-11e8-840c-5545c67f2887.png">

**Comment by McFlat** [comment]
Next I want to work on the videos import script to be like the frontend one because, the difference really affects me in a big way. I need it to check the targetUrl instead of a name/title of the video to keep out any duplicates.

**Comment by McFlat** [comment]
I think using a generic target url, converted from the many different possibilities would be best instead of doing `provider:id`, that way you can just use the url the way it is, instead of having to do a conversion all the time to fetch it

**Comment by gnouts** [comment]
(Maybe out of scope but) In the meantime I personnaly use @roipoussiere's Python script with small improvement and a cron job.
Here is my code : https://taboulisme.com/git/nouts/peertube-import
Though, it can only be set by the instance admin. I'm using it for duplicating some YouTube channels at https://alttube.fr/videos/local

**Comment by aliceinwire** [comment]
@gnouts I like your project but it would be more intuitive to have it on peertube anyway
It would improve discovery and usage of such tool

**Comment by fflorent** [comment]
@gnouts I would like to report an issue (in node arguments, `-l` is for license whereas your intent is to specify language, so this should be `-L` or `--language`). Where may I report a bug? :)

**Comment by gnouts** [comment]
@fflorent Thanks, I set up a github clone here : https://github.com/gnouts/peertube-import
@aliceinwire Sure, I agree. In the meantime it works for my usecase and actually I can't do better with my time and knowledge.

**Comment by fflorent** [comment]
While I remember having used this script to import a whole YT channel, I recently tried again and failed to run it for that purpose.

But the documentation seems to tell that we can pass the ID of a channel: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#peertube-import-videosjs

I also see that youtube-dl supports downloading a whole channel. I wonder if that's possible to use a cron script to automatically synchronize a YT channel. I'll investigate that but if anyone can tell me more about it, I would be very grateful! :)

**Comment by fflorent** [comment]
OK, so I could run the `peertube-import-video` script in order to upload a whole YT channel to Peertube. Also I figured out that we cannot rely on video names in order to detect whether a video has already been uploaded (if the YT owner renames a video, that creates duplicates…). Rather than that, in order to synchronize a YT channel with a PT one, I propose to rely on a `--since` parameter and use a crontab job.

For that purpose, I opened this PR: https://github.com/Chocobozzz/PeerTube/pull/1991

Even if that's WIP, feedback welcome :).

Florent

**Comment by Bugsbane** [comment]
Aren't all YouTube video ID's unique? If so, couldn't the import just store the YouTube video ID and then check there aren't already any videos imported with that same ID?

**Comment by fflorent** [comment]
@Bugsbane Yes, it has already been suggested here: https://github.com/Chocobozzz/PeerTube/pull/1991#issuecomment-515936253

But it requires more efforts for implementing this.

If you are willing to contribute, please do so. I would personally appreciate this improvement :).

**Comment by Bugsbane** [comment]
> If you are willing to contribute, please do so.

I'm more than happy to contribute... however my personal skills though lie in design. UX, communications and marketing rather than coding. :P

**Comment by mister-monster** [comment]
I actually found this issue (and multiple others) after i had almost completed a Python tool to do this, so i figured i would comment about it here.

https://github.com/mister-monster/YouTube2PeerTube

This is a tool that watches YouTube channels, and when new videos are found it mirrors them to a PeerTube channel.

**Comment by Chocobozzz** [comment]
@mister-monster Don't hesitate to make a MR to add you script in the documentation website: https://docs.joinpeertube.org/#/use-third-party-application

**Comment by 0lhi** [comment]
What I wrote on Twitch at #4713 :

> **Describe the solution you would like:**
> 
> An ability to connect PeerTube with a Twitch Account, and to enable automatic imports of VODs, Clips and/or Highlights.
> 
> The user should be able to decide which kind of video should be uploaded to which Channel. There should be a default set of tags which can be changed later if need be. One Tag should be the Twitch Category, another could be the Streamer Name, and "Twitch" itself would seem appropriate, too.
> 
> Description can be something basic like:
> 
> "_Source: https;//twitch,tv/videoID_"
> 
> For Clips:
> 
> "_\[Clipped by TwitchUser12](https;//clips,twitch,tv/ClipID)_"
> 
> There should be a setting to decide from what date onward videos should be imported, to avoid duplicate uploads.
> 
> There should also be an option to have a delay between making the VOD/Highlight, and the automated Import, to give the Streamer some time to make a proper description/thumbnail.

**Comment by fflorent** [comment]
UI/UX mockups, feel free to comment:

# Channel management
## Information tab

We add a tab for managing the channel information:

![new information tab](https://user-images.githubusercontent.com/371705/157459882-d07c476c-3389-42b2-8e36-f12c3cd6bdd5.png)


## Synchronization tab

## Filling the frequency and the URL

![Frequency and URL](https://user-images.githubusercontent.com/371705/157467171-7ec05545-d113-4ce7-9ceb-63f09f38bf83.png)
 

## With CRON custom value
![Capture d’écran 2022-03-09 à 16 05 45](https://user-images.githubusercontent.com/371705/157469001-26984cbc-148f-423a-95fa-ef1f6fe22847.png)

## After fetching list of videos

## After fetching videos from the external platform

![Capture d’écran 2022-03-09 à 16 27 44-fullpage](https://user-images.githubusercontent.com/371705/157473489-0465bee3-58c9-43ee-86df-55dd789ffafa.png)

# Administration: Allowing the feature

![2022-03-09_16-33](https://user-images.githubusercontent.com/371705/157474614-eb7c1450-71e5-43e0-9374-6a4fa422a211.png)

# Others

If the user is not granted for uploading videos (because their quota is set to 0) or the admin did not allow the synchronization, the tab elements should be disabled with a message indicating the reason.

**Comment by Chocobozzz** [comment]
Hi,

Thanks a lot for these mockups!

Some remarks:
 * I think we should display an "import sync" recap in the "My importations page", above the current table. It would display already configured import syncs (URL, channel destination). A button would allow to delete an already configured sync, and another one to create an import synchronization. We can also add another link in the channel page or the channels list page to create an import synchronization 
 * I don't think we should allow users to choose sync frequency, but instead provide it as an admin configuration
 * The cron setting is too complex for users
 * I'm not sure we should implement the "preview list of videos". It would require additional REST API route, tests etc so I don't think it's worth it

**Comment by fflorent** [comment]
@Chocobozzz Thanks a lot for your feedback.

As your feedback are either trivial to visualize or remove some elements of the mockups, I'd start implementing the feature, unless you suggest to rework my mockups.

**Comment by fflorent** [comment]
A little update of the work in progress.

I pushed a version which:
 - let the owner of a channel fill the external channel to sync with;
 - disallow through the UI the owner of a channel to fill the external channel field and explain why. 2 possible reasons: the admin disallows the HTTP video import or the user is granted a quota of 0 (so s/he is not allowed to upload anything);
 - succeeds to fetch regularly (every 15 minutes) the last 3 videos of an external channel;
 - fetches in the database the list of the video imports to filter the videos already imported among the last 3 videos;
 - [technical considerations] the API don't check whether the user is allowed to sync channels (according to the criteria of the 2nd point of this list), instead the check is made while the `video-channels-sync` is run (we filter directly the user having a quota ≠ 0 through the sequelize request);
 - **Feedback welcome**: I assume the HTTP video import is enough to tell whether the synchronization is allowed or not for users who can publish videos, so I finally chose to not [implement the option in this mockup](https://user-images.githubusercontent.com/371705/157474614-eb7c1450-71e5-43e0-9374-6a4fa422a211.png) (unless you express the need of it);

You should be able to give this commit a try: https://github.com/fflorent/PeerTube/commit/ce36e4368b232bbfa99d062e7c6de7bca0372d85

Next steps:
 - [ ] Finish the `video-channels-sync`:
   - [ ] Continue the synchronization (the `video-channels-sync` job) even when the synchronization of a channel fails;
   - [ ] Continue the synchronization of a channel even when the fetch of a video fails;
   - [ ] Reverse the playlist fetched by youtube-dl to conform with the chronological order;
 - [ ] Allow the admin to change the synchronization (`video-channels-sync` job) interval, and maybe change the default value: youtube-dl can be very slow;
 - [ ] Chocobozzz proposal: "I think we should display an "import sync" recap in the "My importations page", above the current table";
 - [ ] Check it works also with these platforms: Vimeo and Dailymotion; 
 - [ ] Implement unit/integration tests;

After this feature request, I would also propose these enhancements:
 - [ ] For a channel, specify a default license: this not only applies to channel synchronization, but also to any imported videos (user license choice for specific video > channel default license > instance default license);
 - [ ] Less frequently by default (like every 24h), check the meta-data of every videos of a synced channel and, when needed, update the captions, the descriptions, etc. (this would help a user of my instance who has captioned old videos on Youtube), the license will not be synchronized (because YT only give few choices for video licenses; I have not checked other platforms);

**Comment by Chocobozzz** [comment]
Hi,

Just a small comment about the global schema: I think we should provide a dedicated form where you can import any channel into any channel. This way, you may import multiple youtube channels into the same peertube channel (I'm sure we'll have this feature request in the future).

**Comment by fflorent** [comment]
> Hi,
> 
> Just a small comment about the global schema: I think we should provide a dedicated form where you can import any channel URL (input text) into any PeerTube channel (select filled with your channels). **This way, you may import multiple youtube channels into the same peertube channel (I'm sure we'll have this feature request in the future).**

Thanks for your feedback!

I am not sure why users would import multiple YT channels into one PT channel, as they can create as many channels as they want with their account.

Though if you insist, I will conform to your idea based on your intuitions (as I don't have as many input from users as you and you will probably maintain this feature more than I will do).

**Comment by Chocobozzz** [comment]
> Though if you insist, I will conform to your idea based on your intuitions (as I don't have as many input from users as you and you will probably maintain this feature more than I will do).

You may want to create a channel on a specific theme, and automatically aggregate multiple remote channels in it. Since I don't think it will make the UI more complex and will be more difficult to implement in the backend, I think we should support this use case so we don't have to change the way it works in the future. Plus, we may also support playlist synchronisation (and so it's also a valid use case to sync multiple playlists in a specific channel).

**Comment by drzraf** [comment]
Do you mind explaining how duplication is avoided? Are Youtube video IDs stored locally as a peertube video metadata so that these are automatically ignored from subsequent syncs?

**Comment by fflorent** [comment]
> Do you mind explaining how duplication is avoided?

There is a table named `videoImport` which stores all the url of the videos imported (thus we can use it to avoid duplications)

**Comment by GlassedSilver** [comment]
> > Do you mind explaining how duplication is avoided?
> 
> There is a table named `videoImport` which stores all the url of the videos imported (thus we can use it to avoid duplications)

Are these normalized? Cause otherwise adding a video through the shortened YT link for example will create a duplicate when it's queued using the long URL again.

**Comment by fflorent** [comment]
> So, this functions now and available for instances (presumably after updates)?

No. It will be available once v5 is out

**Comment by Seyferto** [comment]
When will it be released?

**Comment by fflorent** [comment]
By the end of 2022

**Comment by Seyferto** [comment]
Why not something advised?

**Comment by fflorent** [comment]
> Why not something advised?

In production, because of some bugs or unstable / broken features in develop.

**Comment by Seyferto** [comment]
Testing takes 4 months?

**Comment by Booteille** [comment]
> Testing takes 5 months?

PeerTube minor releases are made every 3 months or so. Major releases are made every year.

**Comment by Seyferto** [comment]
Is this minor? It should have really been there since the beginning, though, as doing them one by one is so tedious...

**Comment by Chocobozzz** [comment]
@Seyferto Next minor release is planned for September. If you're not happy with this ETA you can use nightly builds at your own risks: https://builds.joinpeertube.org/nightly/

Complaining about the time a feature is released in a free software project without a thank you when @fflorent took a lot of its own free time to develop is quite annoying. See also the section of our FAQ regarding this kind of remark: https://joinpeertube.org/faq#peertube-does-not-contain-all-the-tools-i-need-to-manage-my-instance

**Comment by Seyferto** [comment]
I did actually like it when I noticed it was being done, but was disappointed if it was going to be released by the end of the year... if it's next month then that is better... so, nightly has this feature? Do you suppose others' instances usually use nightlies, though, or do most people typically wait for a release?

**Comment by emansom** [comment]
> In production, because of some bugs or unstable / broken features in develop.

@fflorent For people wanting to help test this new feature; are you referring to active bugs with this new functionality or more as in a general statement/warning?

**Comment by fflorent** [comment]
@emansom That's a general statement, yes :)

**Comment by Seyferto** [comment]
Is this being tested anywhere as of now?

**Comment by Seyferto** [comment]
@fflorent Is this being tested anywhere as of now?
