### ISSUE TITLE
Video is not federated until encoding is finished

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#788]
* **PeerTube version or URL:** 1.0.0-beta.9

* **What is the expected behaviour?**
When choosing to publish a video immediatly after upload it without waiting end of enconding job, video should be federated at the same time.

* **What do you see instead?**
Since the 1.0.0-beta.9 and the new feature to wait the end of enconding job for publishing the video, even if you choose to immediatly publish the video, it will be federated (broadcasted) to the following instances only at the end of all the encoding job for the video.

Exemple : 
<img width="1021" alt="capture d ecran 2018-07-10 a 08 26 09" src="https://user-images.githubusercontent.com/9108457/42492896-1755e66e-841b-11e8-9979-666f26451933.png">

<img width="944" alt="capture d ecran 2018-07-10 a 08 26 58" src="https://user-images.githubusercontent.com/9108457/42492904-1f50d2b6-841b-11e8-8d8f-943d759fb1fa.png">

For all the new video on this instance, we have this message « The video is being transcoded, it may not work properly. ».

**Comment by Chocobozzz** [comment]
I think it has always been the default behaviour: if the server enabled transcoding, peertube waits the first transcoding job (the one that transcodes the original video file) before federating the video (optimization and avoid potential issues, because this job **replaces** the original file that could have been in another format etc).

The wait transcoding checkbox will publish the video on **your** instance, and will federate the video after the original file optimization **and** 1 transcoding job in another resolution.

**Comment by gegeweb** [comment]
Not sure it was the default. ;)
So it doesn't seem to be a bug or regression, I close the ticket.
