### ISSUE TITLE
Video player embed options

### ISSUE THREAD

**Issue by raphaelbastide** [Chocobozzz/PeerTube#790]
Here are some possible options that can be useful for an advanced use of the embed video player. Those are proposals and I am curious about your thoughts. Let me know!

Title | [Sass class name](https://codepen.io/heff/pen/EarCt) | Description | Default value
------------ | -------------| -------------| -------------|
Width | none | Value in px. Width of the player | `560`
Height | none | Value in px. Height of the player | `315`
Title | none | Boolean, display or not the video title | `true`
Subtitle | none | Boolean, display or not the video subtitle | `true` 
Bar icons | none | `full` `minimal` or `none`, 3 levels of icons displayed on the bottom bar: `full`: Play, Time, Volume, Settings, PeerTube logo, Fullscreen.  `minimal`: Play, Volume, Fullscreen. `none`: no icons. | `full`
Background color |  primary-background-color | Changes the play button and the bottom bar background color | A linear gradient
Foreground color |  primary-foreground-color | Changes the play button and the bottom bar icons color | `#ffffff`
Peertube button | none  | Boolean, display or not the peertube button in control bar | `true`

Also some questions I have in mind:
- What is the current player skin based on?
- What led to the design choices?
- Can instance admin change the player CSS skin, if yes how easily?

**Comment by miblodelcarpio** [comment]
I could probably make use of all these proposed options! May I also add to the list:

Title | [Sass class name](https://codepen.io/heff/pen/EarCt) | Description
-- | -- | --
Playback speed | none | Value in %. 100% (default) is the speed of the original recording; 200% twice the original speed, so the video takes half the original duration to elapse

**Comment by raphaelbastide** [comment]
@miblodelcarpio Interesting, what would be the use case?

**Comment by miblodelcarpio** [comment]
If you check out the "Previous Episodes" area [here](https://handmadehero.org/watch) and click through to one of the episodes, you can put this in context.

I know at least one viewer likes to watch this stuff sped up, to 200% I think. As far as I know, YouTube's API doesn't currently let me a) Give them controls for this in one of my menus / bound to keys; or b) Store their preferred playback speed in localStorage. I'd like to combine your proposed `Bar icons: none / minimal` with my own playback speed controls.

**Comment by rezonant** [comment]
I think adding a playback rate option to the embed would be really easy. Also worth noting that the new PeerTube Embed API does let you control that programmatically, at least, so there's a lot of context I'm the codebase for how to implement it (check out client/src/standalone/videos/embed.ts).

Width and height are unnecessary, just size your iframe from outside the embed and it will adapt as needed.

The rest of the options all affect videojs (the playback component PT uses) and surely possible, but perhaps the ability to wholesale replace the player skin might be a better way to accomplish those.

**Comment by rezonant** [comment]
Note that YouTube _does_ offer the ability to control playback rates both in it's regular embed (gear menu -> Speed, see https://developers.google.com/youtube/youtube_player_demo) as well as programmaticly via their embed API for those who want to build their own player controls on top of YouTube:
```
player.setPlaybackRate(suggestedRate:Number):Void
```
https://developers.google.com/youtube/iframe_api_reference#Playback_controls

**Comment by Anton-Latukha** [comment]
1. `Width` & `Height` options

"Width and height are unnecessary, just size your iframe from outside the embed and it will adapt as needed."

Yes, it is definitely superior approach. We live in HTML5 era. Site creator should pick frame size and player is able to adapt to that size, because it is HTML5. Also video scaling is not a problem nowadays, in browsers, as in desktop media players.

---

1. The embedded player should check for iframe size. And pick by this rule:

```
if bestStreamResolution >= iframeSize
  then stream streamResolution >= iframe scaled video size
  else stream bestStreamResolution
```

Explanation:

1.a. Streaming best 1080p stream to `320x240` window is wasting everyone's resources.

1.b. If any upscaling happens by default - it degrades perception&picture quality. Compression artifacts seen more on upscaling.

1.c. So stream should have nearest optimal best quality to play 1:1 or be downscaled by browser.

Relatively good article: https://rigor.com/blog/2016/03/size-and-quality-optimizations-for-html5-video

I am talking out of my lawn, I am not a Web-dev. Maybe it is already works like that.

---

2. `Playback speed` option - `Would should be the case?`

I watch/watched a:

2.a. Long hours shows/podcasts. That have important information, that is not to complex. 150%.

2.b. Some game streamers can go up to 18-20 hours (https://www.twitch.tv/zhakaron/videos/all), and be drunk and silly and exhausted in the end, and it can be fun to put them in background, to pick when real lulz moments happen and watch them being silly. They flip out/change/impersonate voice, you can pick that on even 175-200-300% speeds.

2.c. Show episodes/content that are "ok", and occasionally have interesting/important information for you. You can fast-listen through, to pick up important. 150-200%.

2.d. If person has a trait on time-management/efficiency (business people, C-level managers).

2.e. If person has _a really fast verbal perception_ (I know a person that listens everything on 300%, because he has that ability).

**Comment by Chocobozzz** [comment]
> The embedded player should check for iframe size. 

I think this is already implemented: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/peertube-videojs-plugin.ts#L370

**Comment by Anton-Latukha** [comment]
* Subtitles are obviously an important feature for good 1.0.
* Good _main design_ is an important feature for good 1.0.
* Possibility of logo/branding is an important feature for 1.0. It is important for companies, businesses and content creators. And since people host their instances, they would want to be able to put branding on UI.
* Any _custom_-design features (icons, color picking, skins) - are very _optional_ features for 1.0.

**Comment by henke37** [comment]
Subtitle as in subtitles or just as in a second title?

**Comment by Anton-Latukha** [comment]
Yes, `raphaelbastide` meant subtitle, and overlooked that; I stated about subtitles.

**Comment by dieudo4** [comment]
I have included [subtitles to a PeerTube video](http://cerclesrestauratifs.org/wiki/Dominic_Barter/Aspects_syst%C3%A9miques#Via_PeerTube), and I would like the subtitles to be automatically selected. Is it possible to add an instruction to the basic iframe script ? :
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube.social/videos/embed/ed808b24-5357-41c7-9875-8f572f63aaad" frameborder="0" allowfullscreen></iframe>`

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/5efab5467cacb4cce584e2d36e4133a701d8c983

**Comment by fufik** [comment]
I upload a MKV video to a PeerTube 2.0 instance and I can't see any subtitles. What's the problem?

**Comment by Chocobozzz** [comment]
PeerTube does not automatically import subtitles from MKV format. You need to upload them manually

**Comment by fufik** [comment]
> PeerTube does not automatically import subtitles from MKV format. You need to upload them manually

Okay, but I hope you implement ass (lmao) with all the cool features. I'm not yet of much help to you, but I'm on my way to decentralising everything. Good Luck, heroes!

**Comment by miroR** [comment]
> > Subtitle as in subtitles or just as in a second title?
> 
> I meant a second title sorry for the confusion. I am talking about the sentence “Uses P2P others may know your IP is donloading this video” that I find sometimes annoying. I think it should be optional.

_Uses P2P, others may know you are downloading this video_ should go away into somewhere less annoying.

What would it look like if the Stasitube put a note on every video saying:
_We track you every link you open and wherever you browse and whatever you download_

And PeerTube is innocence and honesty in comparison to them. That note should go somewhere less conspicuous.

**Comment by DontUseGithub** [comment]
> That note should go somewhere less conspicuous.

IMHO the warning should be removed only if the player doesn't make use of p2p.
