### ISSUE TITLE
[Request] Official snap package

### ISSUE THREAD

**Issue by Strit** [Chocobozzz/PeerTube#819]
Snaps have become more and more popular these days and many developers use it to deploy their applications to servers around the world.

I would like to request an official snap of the Peertube application.

I'm in no way a developer and since I failed setting up Peertube with Docker (yeah I'm that big a noob), I would love other options, like a snap.

[Snapcraft](https://snapcraft.io/)

Snaps are very easy to install on any distribution that supports snaps, which as you can see in the link above, is almost all server distributions.

**Comment by rigelk** [comment]
Hi @Strit - we maintain no official package, because we have already seen how much time even just supporting Docker takes us.

I also agree that our Docker setup could be simpler : as a matter of fact, we're refactoring it at the moment (see #813).

But adding Snaps (or any other packaging) can also have a side effect (which we have learned with Docker and personally with my Debian package): hiding complexity from the user also makes debugging and helping the user more difficult. That means our support is also less effective on these packages.

I suggest you use a community package and ask for support to their respective authors, or ask for help on IRC/Matrix (see README) while installing through the [regular install](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md), which we support best.

**Comment by Strit** [comment]
Thanks for the heads up.

Guess I just need to realize, that I can't do everything. 😄
