### ISSUE TITLE
Bulk edit video support field

### ISSUE THREAD

**Issue by yPhil-gh** [Chocobozzz/PeerTube#827]
## How it works now

Right now - apparently - when the "support" link is filled at the channel level, only future new videos on this channel will display it, not the existing ones.

## Problem

The only way for existing videos to display this link is to duplicate it at the video level.

## Solution proposal

- If the "support" link is filled at the channel level and is empty at the video level, display it, otherwise display the video level link ;
- If you don't want a support link on a particular video, ~~either enter something else in the video level link, or~~ put it in another channel.

~~The channel "support" link should be displayed in the channel's "about" page, too.~~

**Comment by Chocobozzz** [comment]
And what if you don't want the support field for a particular video? I don't like implicit things like "if empty then fill with ...". Maybe a mechanism to update old videos when updating the video channel support field would be better.

> The channel "support" link should be displayed in the channel's "about" page, too.

It is (but only if the support field is filled).

**Comment by Nautigsam** [comment]
Does something like video edition in batch is in the backlog? If yes, then this case could be addressed. One could add channel's support link to a bunch of videos uploaded before the link was added on the channel.

**Comment by benrob0329** [comment]
I really don't understand why the support field isn't shared across all the channels videos. It's set up so that you see it when configuring a channel, and it makes you think it's global. But then it's actually per-video, even though the standard per-video information is the description.

This makes the majority of use-cases a huge PITA because you have to manually update (or bulk-select if that feature comes around) all the old videos, which for a field who's whole purpose is per-channel support information (monetary or otherwise) which _will change_ over time, this is really stupid.

Yes, that one person for that one video might want a different support field, but that doesn't warrant making everyone else's lives more difficult because of one edge case that is probably better suited to the video description anyways.

Sorry if this comes off a little strong, it's just a really backwards user and creator experience for me.

**Comment by Chocobozzz** [comment]
@benrob0329 The support field is how I could support the creator(s) of the video. This is not the same than the video description field. The publisher is not always the creator, so it's the reason why we have a support field per video, that is automatically filled by the support field of the channel.

Anyway, this is fixed by https://github.com/Chocobozzz/PeerTube/commit/1e66b987cd578fc97471cc429199af453a5daba6 & https://github.com/Chocobozzz/PeerTube/commit/7d14d4d2ca82cc43c93b45bb1f90af975cfbf67c. These commits add a checkbox in the video channel edit page to automatically update all your videos support field.
