### ISSUE TITLE
Show last commit hash with server version

### ISSUE THREAD

**Issue by Nautigsam** [Chocobozzz/PeerTube#835]
Currently we show the current version of Peertube but in some cases it is not precise enough. Users should be able to give the last commit hash when they report an issue so that we can identify what exact version they run.

**Comment by rigelk** [comment]
We could use `git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null | sed -n 's/^\([^^~]\{1,\}\)\(\^0\)\{0,1\}$/\1/p'` to check if a tag (since we bind tags to releases) is associated with the current HEAD. If not, we can display the commit alongside the latest version name and get the commit hash via `require('child_process').execSync('git rev-parse --short HEAD').toString().trim()`.

**Comment by KRtekTM** [comment]
I am building peertube by myself so I added this to my building script: https://github.com/KRtekTM/PeerTube-scripts/blob/master/add-hash-to-version.sh
