### ISSUE TITLE
Hardware acceleration for video transcoding

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#938]
I'm running PeerTube on a server with a GPU that I was hoping to use for transcode acceleration. In my particular case I'd really be interested in nvenc and cuvid.

Honestly I was hoping to see some way to generically customize the ffmpeg parameters for each transcode level; maybe that sort of configuration functionality could allow admins to tweak video quality and bandwidth settings as well as supporting platform-specific codecs?

I'd love some guidance on how other folks would like to see this support implemented, but I'm happy to do the work.

**Comment by scanlime** [comment]
> That isn't a so good idea because the player require a very specific encoding, bandwidth, ... to allow scrolling in the video. This is why this isn't implemented :)

Ah, that makes sense! I was surprised not to at least see a way to control bit rate or overall encoding quality though. On my system at least, the ffmpeg command line doesn't include any rate or quality info, and I was hoping for a way to tune that or at least see what the current bandwidth results form.

(sample ffmpeg command line I'm seeing now...)

/usr/local/bin/ffmpeg -i /var/www/peertube/storage/videos/a3fba5cd-fd18-4db3-ab4a-c80849d29c93-1080.mp4 -y -vcodec libx264 -r 60 -threads 4 -movflags faststart -b_strategy 1 -bf 16 /var/www/peertube/storage/videos/3-transcoded.mp4

When you say hardware accels can be simply added, do you mean there's already way to do this, or are you saying it could be a simple new feature to implement?

Thanks again!

-micah

**Comment by scanlime** [comment]
Thanks again,

Good point about the potential quality trade off. I’ll have to try manually
re-transcoding some of these videos just to convince myself the quality is
worthwhile still.

Even with software encoding though, hardware decode seems like it could
help a lot, especially when the source video is high bitrate.

**Comment by karibuTW** [comment]
Hello guys,
My server is taking quite some time to transcode some large videos and GPU acceleration would be super good to see!
Any way to implement this?

Thank you

**Comment by Jorropo** [comment]
> Hello guys,
> My server is taking quite some time to transcode some large videos and GPU acceleration would be super good to see!
> Any way to implement this?
> 
> Thank you

Il have been a while since I looked in the souce code but from what I remember ffmpeg already have gpu acceleration enabled.

**Comment by karibuTW** [comment]
I see, I guess my system is not ready neither. I need to install NVENC.
Let me give it a try!

**Comment by Jorropo** [comment]
@karibuTW it's also that ffmpeg is CPU focused, don't except any huge improvement by GPU acceleration.
If you would use 100% of your GPU an OpenCL or Vulkan CL transcoder would be better (but that would require some relatively beaffy GPUs wich the average server doesn't have).

**Comment by karibuTW** [comment]
I see, I have only a G710 in the server, so i don't expect big speed neither...It might may be even be counterproductive in this case. I need to find another way.

My Xeon E3 1220v5 (4C/4T) @3 GHz is taking ages to encode... (I've asked only 360p and 720p) and have configured it with 4 threads.
I just realized that FFMPEG is taking 150% of CPU but probably the nice is too gentle. I have some CPU intensive application (BOINC) to leverage the "unused" cycle with a nice of 19. If I stop BOINC, FFMPEG goes to 350% (Not yet 400%, but better!).
May be I need to adjust the nice (15 now)

**Comment by Jorropo** [comment]
> May be I need to adjust the nice (15 now)

@karibuTW 
Idealy you would like to have FFMPEG running at a lower nice than boinc, so it's boinc waiting for ffmpeg not the inverse.
Also depending of the boinc project it may have huge time beetween releasing to the kernel (if it does lots of computation it can happend seconds beetween syscalls).
I know there is an option to only run when the cpu is only used bellow a certain threashold in boinc. If you do that when FFMPEG is running boinc will pause it self and run latter.
(Also nice shouldn't really care about the difference beetween 2 process, just if that lower or higher (if you have boinc at 19 and ffmpeg at 5 it should be the same as boinc as 19 and ffmpeg as 15), but I've seen some case where this where actualy important)

**Comment by karibuTW** [comment]
Make sense Jorropo, thanks for all those sharing!

**Comment by scanlime** [comment]
> @karibuTW it's also that ffmpeg is CPU focused, don't except any huge improvement by GPU acceleration.
> If you would use 100% of your GPU an OpenCL or Vulkan CL transcoder would be better (but that would require some relatively beaffy GPUs wich the average server doesn't have).

This is not true, video encoding does not require a particularly beefy GPU. Plenty of older mid-range nvidia chips can encode multiple HD streams in real time.

My understanding is that it would be relatively easy to suppprt hardware accel at this point (it's just a few ffmpeg options) but this involves a quality tradeoff and it might be more acceptable to do for specific formats than as a general default.

**Comment by scanlime** [comment]
fwiw even servers without a discrete GPU often have some hardware video encoding built into the CPU (intel quick sync) which ffmpeg does support

**Comment by scanlime** [comment]
it's also maybe worth mentioning that both hardware decode and harware encode support could be advantageous, and hardware decoding doesn't change the output quality at all so it's "free" to implement on any environment that has the hardware and library support

**Comment by Avatat** [comment]
I would like to put in my two cents :)
As I understand, by default, `ffmpeg-utils.ts` uses `libx264` codec to encode video. If I'm right, all encoding (and decoding too) will happen on a CPU: https://trac.ffmpeg.org/wiki/Encode/H.264
Of course, CPU transcoding is very slow and heavy.

I think that [hardware acceleration](https://trac.ffmpeg.org/wiki/HWAccelIntro) is a "must-have" for real-use PeerTube instances.

Hardware acceleration needs three things:
1. **Hardware capable** of de/encoding
2. **Drivers and libraries** which will support used hardware
3. **FFmpeg compiled with hardware-accelerated codecs**, and use of these codecs in the command line

At this moment, I have a small experience with NVIDIA's accelerated transcoding, so I can speak only about it.
To use **NVIDIA's acceleration**, you have to choose a [**supported GPU**](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix). For [my experiment](https://github.com/Avatat/sandbox/blob/master/tests/nvenc.md) I have chosen an old **K2200 GPU**, because it was cheap, it has **full support for H.264** codec, and **supports an unlimited number of concurrent de/encoding sessions**.
NVIDIA K2200 is capable to transcode 1080p30 (H.264) movie to 720p, 540p, and 480p (H.264) simultaneously at **almost 12x speed**. For example, it will transcode 60 minutes long movie in 5 minutes, to three different resolutions. And it uses almost no CPU when transcoding!
I have to notice, that **GTX/RTX GPUs has limited encoding capabilities** to 3 concurrent sessions, but [some hacks exist](https://github.com/keylase/nvidia-patch) to omit this limit.

In the future, I plan to learn how to do Intel and AMD acceleration - then I could write more about it.

I would like to add or help in adding a hardware-accelerated transcoding feature to PeerTube.

**Comment by scanlime** [comment]
I hope you mean "must support" rather than "must have"... I too am enthusiastic about hardware encoding but there are some big limitations to keep in mind:

- Lots of people are running on servers without GPUs
- Hardware transcodes may be lower quality than libx264
- Hardware transcoders may have bugs that need to be worked around for specific formats/videos

Ideally we'd have some kind of pluggable support for transcoders running elsewhere; until then, it seems necessary to give admins a lot of control over when hardware transcoding happens and what settings it uses.

**Comment by Avatat** [comment]
Definitely - we have to implement in a pluggable and fully configurable way.

**Comment by Avatat** [comment]
I had made some Intel-based transcoding and created a new page with the results: https://github.com/Avatat/sandbox/blob/master/tests/ffmpeg_transcoding.md

**Comment by Chocobozzz** [comment]
In the next release, you'll be able to create plugins to change transcoding options/encoders (and so use an encoder that supports hardware acceleration): https://docs.joinpeertube.org/contribute-plugins?id=add-new-transcoding-profiles

**Comment by snakeeater4526** [comment]
hi, sorry to pick that old issue but.... i try to make work VAAPI in peertube for transcoding.

the vaapi plugin give me input/output error.

and the transcoding-profile-debug , i tried that:

{
  "vod": [
    {
      "encoderName": "aac",
      "profileName": "test",
      "outputOptions": []
    },
    {
      "encoderName": "h264_vaapi",
      "profileName": "test",
      "outputOptions": []
    }
  ],

  "live": []
}

and it give me error 1 : conversion failed....


If anyone have an idea.... i would be really happy to hear it.... i'm not someone that like asking help but here i searched everywhere on google and i'm working on that particular project since non stop 48h 

THANK YOU

**Comment by Avatat** [comment]
I would start from running plain `ffmpeg` using `h264_vaapi` encoder - I believe it will fail too.
