### ISSUE TITLE
Transcription widget as in youtube

### ISSUE THREAD

**Issue by Rational-pi** [Chocobozzz/PeerTube#979]
# Transcription widget as in youtube
**User story**
I use frequently the Transcription UI combined with the browser search functionality to find back when in a video something were said. It then allow me to better source information back to a video with a timestamp.

**Advantages for PeerTube**
Easing the sourcing to PeerTube could promote it (Timestamped sourcing would be better).
The lack of this functionality would make me stick whit YouTube for conference watching at least. witch could be detrimental to PeerTube at my scale.

**Existing version**
![](https://i.ytimg.com/vi/yjYWAT4D1tg/maxresdefault.jpg)

**Comment by NoMoreCRAPTion** [comment]
This need to be integrated for deafblind users.

## Accessibility

Here is the W3C protocols: https://www.w3.org/WAI/media/av/transcripts/

Netflix's extremely wonky implementation of this feature: https://assets.nflxext.com/ffe/siteui/accessibility/DeafUDescriptiveTranscript.htm

Here you see a news channel providing transcript alongside subtitles: https://www.dailymoth.com/blog/deaf-asl-professor-at-liberty-university-charged-with-sexual-battery-and-abduction. It is not uncommon to see people upload transcripts externally to Tumblr or Google Drive.

Other people pin transcript in the comment section or paste them into the video description. 

Part of this is because YouTube hides the transcript in a very inaccessible GUI:

![youtube-transcript](https://user-images.githubusercontent.com/95659233/145448606-f3d9f4e2-fa7f-48c7-a9dc-950c00464749.jpg)

## Content Moderation and Search/Discovery Algothrim

I think up until like 3 years ago, YouTube's algorithm heavily relies on automatically-generated transcripts since 2008. YouTube now uses [Cloud Vision API f](https://cloud.google.com/vision)or content recommendation.

I believe prior to using Cloud VIsion API in 2018 for content moderation, a good video transcript account for something like 25% of traffic to a video. Good subtitles or closed captions account for about 10%.

**Comment by NoMoreCRAPTion** [comment]
Treating subtitle tracks as interactive transcripts exists as plugins for video.js according to W3C.

Original: https://www.npmjs.com/package/videojs-transcript-ac (https://github.com/walsh9/videojs-transcript)
Forked: https://www.npmjs.com/package/@packt/videojs-transcript

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/be4bf80883f693b701789b6c0167576da1f57daa (will be released in next peertube version, 6.3)

Documentation already available on https://docs.joinpeertube.org/use/watch-video#transcription-widget
